"use strict";
(()=>{
  const $=id=>document.getElementById(id),params=new URLSearchParams(location.search),requestedId=params.get("id"),freshToken=params.get("new");
  const safe=s=>String(s||"").replace(/[&<>"']/g,"");
  const moduleOf=p=>p?.module||p?.recipe?.module;
  const pages=()=>FenixCore.getCart().filter(p=>moduleOf(p)==="hidden-objects-studio");
  const makeSeed=()=>`fenix-hidden-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;
  function roleCards(cls){return [...document.querySelectorAll(`#assetGrid .asset-card.${cls}`)]}
  function namesFor(cls){return roleCards(cls).map(c=>c.querySelector("strong")?.textContent||"").filter(Boolean)}
  function updateSummary(){const targetNames=namesFor("target"),distNames=namesFor("distractor");if($("summaryTargets"))$("summaryTargets").textContent=String(targetNames.length);if($("summaryDistractors"))$("summaryDistractors").textContent=String(distNames.length);if($("selectedTargetsText"))$("selectedTargetsText").textContent=targetNames.length?targetNames.join(", "):"Brak";if($("selectedDistractorsText"))$("selectedDistractorsText").textContent=distNames.length?distNames.join(", "):"Brak";if($("summaryDensity")){const d=$("density");$("summaryDensity").textContent=d?.selectedOptions?.[0]?.textContent||"—"}if($("summaryPages"))$("summaryPages").textContent=String(pages().length);if($("previewInfo"))$("previewInfo").textContent=requestedId?"Edytujesz zapisaną stronę Hidden Objects":"Nowa strona Hidden Objects"}
  function pageThumb(page){const ref=page.recipe?.content?.targets?.[0]?.assetRef||page.recipe?.content?.distractors?.[0]?.assetRef,asset=ref?FenixCore.getAsset(ref):null;if(asset?.dataUrl)return`<div class="studio-page-thumb"><img src="${asset.dataUrl}" alt=""></div>`;return'<div class="studio-page-thumb">⌕</div>'}
  function renderPages(){const list=pages(),box=$("studioPagesList");if(!box)return;$("studioPagesCount").textContent=`${list.length} ${list.length===1?"strona":"stron"}`;if($("summaryPages"))$("summaryPages").textContent=String(list.length);if(!list.length){box.innerHTML='<div class="studio-pages-empty">Nie zapisano jeszcze żadnej strony Hidden Objects.</div>';return}box.innerHTML=list.map((p,i)=>{const settings=p.recipe?.settings||{},targets=p.recipe?.content?.targets||[],dist=p.recipe?.content?.distractors||[];return`<article class="studio-page${p.id===requestedId?" current":""}">${pageThumb(p)}<div class="studio-page-copy"><strong>Hidden Objects #${String(i+1).padStart(2,"0")} · ${safe(p.title||"Find the Hidden Objects!")}</strong><small>${targets.length} celów · ${dist.length} typów dystraktorów · ${safe(settings.density||"medium")}${p.id===requestedId?" · EDYCJA":""}</small></div><div class="studio-page-actions"><button type="button" data-edit="${p.id}">Edytuj</button><button type="button" class="delete" data-delete="${p.id}">Usuń</button></div></article>`}).join("");box.querySelectorAll("[data-edit]").forEach(btn=>btn.onclick=()=>{location.href=`${location.pathname}?id=${encodeURIComponent(btn.dataset.edit)}`});box.querySelectorAll("[data-delete]").forEach(btn=>btn.onclick=()=>{const page=FenixCore.getCart().find(p=>p.id===btn.dataset.delete);if(!page)return;if(!confirm(`Usunąć stronę „${page.title||"Hidden Objects"}” z projektu?`))return;FenixCore.removePage(btn.dataset.delete);if(btn.dataset.delete===requestedId){location.href=location.pathname;return}renderPages();updateSummary()})}
  function guardSaveButton(){const cart=$("cart");if(!cart||cart.dataset.saveGuard==="1")return;const original=cart.onclick;if(typeof original!=="function")return;cart.dataset.saveGuard="1";let busy=false;cart.onclick=async event=>{if(busy){event?.preventDefault?.();return}busy=true;cart.disabled=true;cart.setAttribute("aria-busy","true");const oldText=cart.textContent;cart.textContent=requestedId?"Zapisywanie zmian…":"Zapisywanie…";try{await original.call(cart,event)}finally{busy=false;cart.disabled=false;cart.removeAttribute("aria-busy");if(cart.textContent==="Zapisywanie…"||cart.textContent==="Zapisywanie zmian…")cart.textContent=oldText}}}
  function startNewPage(){const url=new URL(location.href);url.search="";url.searchParams.set("new",Date.now().toString());location.href=url.toString()}
  function findAssetCard(ref){const asset=FenixCore.getAsset(ref);if(!asset)return null;return [...document.querySelectorAll("#assetGrid .asset-card")].find(card=>card.querySelector("img")?.src===asset.dataUrl)||null}
  function ensureRole(card,wanted){if(!card)return false;for(let i=0;i<3;i++){if(card.classList.contains(wanted))return true;card.click()}return card.classList.contains(wanted)}
  async function forceRestore(){if(!requestedId)return;const page=FenixCore.getCart().find(p=>p.id===requestedId&&moduleOf(p)==="hidden-objects-studio");if(!page)return;const s=page.recipe?.settings||{},c=page.recipe?.content||{};const set=(id,val)=>{const el=$(id);if(el&&val!==undefined&&val!==null)el.value=val};set("density",s.density||"medium");set("minSize",s.minSize??70);set("maxSize",s.maxSize??110);set("rotate",s.rotate||"yes");set("seed",s.seed||page.recipe?.seed||"fenix-hidden");set("title",s.title||page.title||"Find the Hidden Objects!");set("instructions",s.instructions||"Find all the objects shown below.");set("titleSize",s.titleSize??48);set("instructionSize",s.instructionSize??24);
    for(const item of c.targets||[])ensureRole(findAssetCard(item.assetRef),"target");
    for(const item of c.distractors||[])ensureRole(findAssetCard(item.assetRef),"distractor");
    await new Promise(r=>setTimeout(r,40));
    for(const item of c.targets||[]){const asset=FenixCore.getAsset(item.assetRef);if(!asset)continue;const row=[...document.querySelectorAll("#targetList .target-row")].find(r=>r.querySelector("img")?.src===asset.dataUrl);const input=row?.querySelector("input");if(input){input.value=Math.max(1,Math.min(12,Number(item.count)||3));input.dispatchEvent(new Event("input",{bubbles:true}))}}
    ["density","minSize","maxSize","rotate","seed","title","instructions","titleSize","instructionSize"].forEach(id=>$(id)?.dispatchEvent(new Event($(id).tagName==="SELECT"?"change":"input",{bubbles:true})));
    await new Promise(r=>setTimeout(r,220));
    $("generate")?.click();if($("cart"))$("cart").textContent="Zapisz zmiany w projekcie";if($("status"))$("status").textContent="Wczytano dokładny zapis strony Hidden Objects.";updateSummary();
  }
  async function init(){await FenixCore.ready;const newBtn=$("newPage"),seed=$("seed"),cart=$("cart"),status=$("status");if(newBtn)newBtn.onclick=startNewPage;if(!requestedId&&freshToken&&seed){seed.value=makeSeed();seed.dispatchEvent(new Event("input",{bubbles:true}));if(cart)cart.textContent="Dodaj stronę do projektu";if(status)status.textContent="Nowa strona gotowa — wygenerowano nowy układ."}if(requestedId&&cart)cart.textContent="Zapisz zmiany w projekcie";guardSaveButton();renderPages();await forceRestore();updateSummary();$("density")?.addEventListener("change",updateSummary);const observer=new MutationObserver(updateSummary);if($("assetGrid"))observer.observe($("assetGrid"),{subtree:true,childList:true,attributes:true,attributeFilter:["class"]});window.addEventListener("fenix-state-change",()=>{renderPages();updateSummary()})}
  void init();
})();