"use strict";
(()=>{
  const $=id=>document.getElementById(id),canvas=$("page"),ctx=canvas.getContext("2d");
  const state={assets:[],library:[],roles:new Map(),counts:new Map(),images:new Map(),view:"task",layout:null,currentId:null,loading:false,saving:false};
  const safe=s=>String(s||"").replace(/[&<>"']/g,"");
  const requestedId=new URLSearchParams(location.search).get("id");
  function allLibrary(){const active=FenixCore.getActiveProjectId(),seen=new Set(),out=[];for(const p of FenixCore.getProjects())for(const a of Object.values(p.assets||{})){const key=a.dataUrl||`${a.filename}|${a.sizeBytes}`;if(seen.has(key))continue;seen.add(key);out.push({...a,_projectId:p.id,_projectName:p.name,_active:p.id===active})}return out}
  function status(t,e=false){$("status").textContent=t;$("status").dataset.type=e?"error":"ok"}
  function role(a){return state.roles.get(a.id)||"none"}
  function setRole(a,r){for(const [id,rr] of state.roles)if(id===a.id&&rr===r){state.roles.delete(id);renderAssets();renderTargets();schedule();return}state.roles.set(a.id,r);if(r==="target"&&!state.counts.has(a.id))state.counts.set(a.id,3);renderAssets();renderTargets();schedule()}
  function card(a,library=false){const b=document.createElement("button");b.type="button";const r=role(a);b.className=`asset-card ${r}`;b.innerHTML=`<img src="${a.dataUrl}" alt=""><strong>${safe(a.name||a.filename||"Asset")}</strong><small>${library?safe(a._projectName||""):r==="target"?"Cel do znalezienia":r==="distractor"?"Dystraktor":"Kliknij: cel → dystraktor → wyłącz"}</small>${r!=="none"?`<span class="badge">${r==="target"?"CEL":"TŁO"}</span>`:""}`;b.onclick=()=>{if(library&&!a._active){const existing=state.assets.find(x=>x.dataUrl===a.dataUrl);if(existing)return setRole(existing,role(existing)==="none"?"target":role(existing)==="target"?"distractor":"none");const copy=FenixCore.putAsset({name:a.name,filename:a.filename,mime:a.mime,dataUrl:a.dataUrl,source:"fenix-library",tags:a.tags||["content"],meta:{...(a.meta||{}),librarySourceProject:a._projectName}});state.assets=FenixCore.listAssets();setRole(copy,"target");return}const next=r==="none"?"target":r==="target"?"distractor":"none";setRole(a,next)};return b}
  function renderAssets(){state.assets=FenixCore.listAssets();const g=$("assetGrid");g.innerHTML="";state.assets.forEach(a=>g.appendChild(card(a)));$("assetEmpty").hidden=!!state.assets.length}
  function renderLibrary(){state.library=allLibrary();const g=$("libraryGrid");g.innerHTML="";state.library.forEach(a=>g.appendChild(card(a,true)));$("libraryEmpty").hidden=!!state.library.length}
  function renderTargets(){const box=$("targetList");box.innerHTML="";for(const a of state.assets.filter(a=>role(a)==="target")){const row=document.createElement("div");row.className="target-row";row.innerHTML=`<img src="${a.dataUrl}"><strong>${safe(a.name||a.filename||"Asset")}</strong><label>Ile? <input type="number" min="1" max="12" value="${state.counts.get(a.id)||3}"></label>`;row.querySelector("input").oninput=e=>{state.counts.set(a.id,Math.max(1,Math.min(12,Number(e.target.value)||1)));schedule()};box.appendChild(row)}if(!box.children.length)box.innerHTML='<p class="note">Kliknij asset w sekcji 1, aby oznaczyć go jako CEL.</p>'}
  function seeded(seed){let h=2166136261;for(const c of seed)h=Math.imul(h^c.charCodeAt(0),16777619);return()=>((h=Math.imul(h^h>>>15,2246822507)^Math.imul(h^h>>>13,3266489909))>>>0)/4294967296}
  function load(a){if(state.images.has(a.id))return state.images.get(a.id);const p=new Promise((res,rej)=>{const im=new Image();im.onload=()=>res(im);im.onerror=rej;im.src=a.dataUrl});state.images.set(a.id,p);return p}
  function intersects(a,b,pad=12){return !(a.x+a.w+pad<b.x||b.x+b.w+pad<a.x||a.y+a.h+pad<b.y||b.y+b.h+pad<a.y)}
  function currentSettings(){return{density:$("density").value,minSize:Number($("minSize").value)||70,maxSize:Number($("maxSize").value)||110,rotate:$("rotate").value,seed:$("seed").value||"fenix-hidden",title:$("title").value||"Find the Hidden Objects!",instructions:$("instructions").value||"Find all the objects shown below.",titleSize:Number($("titleSize").value)||48,instructionSize:Number($("instructionSize").value)||24}}
  function currentContent(){const targets=[],distractors=[];for(const a of state.assets){const r=role(a);if(r==="target")targets.push({assetRef:a.id,count:state.counts.get(a.id)||3});else if(r==="distractor")distractors.push({assetRef:a.id})}return{targets,distractors}}
  async function build(){const targets=state.assets.filter(a=>role(a)==="target"),dist=state.assets.filter(a=>role(a)==="distractor");if(!targets.length||!dist.length){state.layout=null;drawEmpty();return status("Wybierz co najmniej 1 cel i 1 dystraktor.",true)}const s=currentSettings(),distCount=s.density==="easy"?12:s.density==="hard"?32:22,rand=seeded(s.seed),items=[];for(const a of targets)for(let i=0;i<(state.counts.get(a.id)||3);i++)items.push({a,target:true});for(let i=0;i<distCount;i++)items.push({a:dist[i%dist.length],target:false});items.sort(()=>rand()-.5);const placed=[];for(const item of items){let ok=null;for(let t=0;t<500;t++){const scale=(s.minSize+(s.maxSize-s.minSize)*rand())/100,w=105*scale,h=105*scale,x=70+rand()*(710-w),y=300+rand()*(700-h),box={...item,x,y,w,h,rot:s.rotate==="yes"?(rand()-.5)*.5:0};if(!placed.some(p=>intersects(box,p,8))){ok=box;break}}if(ok)placed.push(ok)}state.layout={placed,targets};await Promise.all(placed.map(p=>load(p.a)));draw();status(`Podgląd gotowy · ${placed.filter(x=>x.target).length} celów · ${placed.filter(x=>!x.target).length} dystraktorów · bez nakładania.`)}
  function drawEmpty(){canvas.width=850;canvas.height=1100;ctx.fillStyle="#fff";ctx.fillRect(0,0,850,1100);ctx.fillStyle="#66717d";ctx.textAlign="center";ctx.font="700 28px Arial";ctx.fillText("Wybierz cele i dystraktory z biblioteki assetów",425,550)}
  async function draw(){if(!state.layout)return drawEmpty();const s=currentSettings();canvas.width=850;canvas.height=1100;ctx.fillStyle="#fff";ctx.fillRect(0,0,850,1100);ctx.fillStyle="#111";ctx.textAlign="center";ctx.font=`800 ${s.titleSize}px Arial`;ctx.fillText(s.title,425,85);ctx.font=`500 ${s.instructionSize}px Arial`;ctx.fillText(s.instructions,425,135);let tx=90;for(const a of state.layout.targets){const im=await load(a),count=state.counts.get(a.id)||3;ctx.drawImage(im,tx,170,58,58);ctx.font="700 22px Arial";ctx.textAlign="left";ctx.fillText(`× ${count}`,tx+62,205);tx+=145}for(const p of state.layout.placed){const im=await load(p.a);ctx.save();ctx.translate(p.x+p.w/2,p.y+p.h/2);ctx.rotate(p.rot);ctx.drawImage(im,-p.w/2,-p.h/2,p.w,p.h);ctx.restore();if(state.view==="solution"&&p.target){ctx.strokeStyle="#111";ctx.lineWidth=5;ctx.beginPath();ctx.ellipse(p.x+p.w/2,p.y+p.h/2,p.w*.62,p.h*.62,0,0,Math.PI*2);ctx.stroke()}}ctx.textAlign="left"}
  async function frozenSnapshots(){const original=state.view;state.view="task";await draw();const preview=canvas.toDataURL("image/png");state.view="solution";await draw();const solution=canvas.toDataURL("image/png");state.view=original;await draw();return{preview,solution}}
  let timer;const schedule=()=>{if(state.loading)return;clearTimeout(timer);timer=setTimeout(build,160)};
  function showSource(which){$("projectPane").hidden=which!=="project";$("libraryPane").hidden=which!=="library";$("tabProject").classList.toggle("active",which==="project");$("tabLibrary").classList.toggle("active",which==="library");if(which==="library")renderLibrary()}
  function findPage(id){return id?FenixCore.getCart().find(page=>page.id===id&&((page.module||page.recipe?.module)==="hidden-objects-studio")):null}
  async function restorePage(page){if(!page)return;state.loading=true;state.currentId=page.id;const s=page.recipe?.settings||{},c=page.recipe?.content||{};$("density").value=s.density||"medium";$("minSize").value=s.minSize??70;$("maxSize").value=s.maxSize??110;$("rotate").value=s.rotate||"yes";$("seed").value=s.seed||page.recipe?.seed||"fenix-hidden";$("title").value=s.title||page.title||"Find the Hidden Objects!";$("instructions").value=s.instructions||"Find all the objects shown below.";$("titleSize").value=s.titleSize??48;$("instructionSize").value=s.instructionSize??24;state.roles.clear();state.counts.clear();for(const item of c.targets||[]){if(item?.assetRef){state.roles.set(item.assetRef,"target");state.counts.set(item.assetRef,Math.max(1,Math.min(12,Number(item.count)||3)))}}for(const item of c.distractors||[]){if(item?.assetRef)state.roles.set(item.assetRef,"distractor")}renderAssets();renderTargets();state.loading=false;await build();$("cart").textContent="Zapisz zmiany w projekcie";status("Wczytano zapisaną stronę Hidden Objects.")}
  async function savePage(){if(state.saving)return;if(!state.layout)return status("Najpierw przygotuj poprawny podgląd.",true);state.saving=true;const btn=$("cart");if(btn)btn.disabled=true;try{const before=FenixCore.getCart(),beforeIds=new Set(before.map(p=>p.id)),s=currentSettings(),content=currentContent(),shots=await frozenSnapshots();const data={module:"hidden-objects-studio",title:s.title,seed:s.seed,recipe:{module:"hidden-objects-studio",seed:s.seed,title:s.title,settings:s,content,meta:{moduleVersion:5,renderer:"hidden-objects-v5",snapshotFirst:true}},preview:{imageData:shots.preview},solution:{available:true,imageData:shots.solution},source:{app:"fenix-desktop",version:"0.34.0",format:"native"}};if(state.currentId){FenixCore.updatePage(state.currentId,data);status("✓ Zapisano dokładny obraz zadania i Solution Hidden Objects.")}else{FenixCore.addPage(data);const after=FenixCore.getCart(),saved=after.find(p=>!beforeIds.has(p.id)&&((p.module||p.recipe?.module)==="hidden-objects-studio"));if(!saved)throw new Error("Fenix nie potwierdził dodania strony.");state.currentId=saved.id;$("cart").textContent="Zapisz zmiany w projekcie";status("✓ Dodano stronę Hidden Objects — zadanie i Solution zapisane 1:1.")}}catch(e){console.error("Hidden Objects save",e);status(`Błąd zapisu: ${e.message||e}`,true)}finally{state.saving=false;if(btn)btn.disabled=false}}
  $("tabProject").onclick=()=>showSource("project");$("tabLibrary").onclick=()=>showSource("library");$("generate").onclick=build;$("taskTab").onclick=()=>{state.view="task";draw()};$("solutionTab").onclick=()=>{state.view="solution";draw()};$("png").onclick=()=>FenixCore.downloadCanvas(canvas,`hidden-objects-${state.view}-${Date.now()}.png`);$("cart").onclick=savePage;
  ["density","minSize","maxSize","rotate","seed","title","instructions","titleSize","instructionSize"].forEach(id=>$(id).addEventListener($(id).tagName==="SELECT"?"change":"input",schedule));
  window.addEventListener("fenix-state-change",event=>{if(state.loading)return;if(event.detail?.assets||event.detail?.activeProject){renderAssets();renderLibrary();renderTargets();schedule()}});
  const p=FenixCore.getActiveProject();$("projectInfo").textContent=`Aktywny projekt: ${p.name} · ${p.format}`;renderAssets();renderLibrary();renderTargets();showSource("project");drawEmpty();
  const page=findPage(requestedId);if(page)restorePage(page);
})();