"use strict";
(()=>{
  const $=id=>document.getElementById(id),requestedId=new URLSearchParams(location.search).get("id");
  const safe=s=>String(s||"").replace(/[&<>"']/g,"");
  const moduleOf=p=>p?.module||p?.recipe?.module;
  const pages=()=>FenixCore.getCart().filter(p=>moduleOf(p)==="hidden-objects-studio");
  function roleCards(cls){return [...document.querySelectorAll(`#assetGrid .asset-card.${cls}`)]}
  function namesFor(cls){return roleCards(cls).map(c=>c.querySelector("strong")?.textContent||"").filter(Boolean)}
  function updateSummary(){const targetNames=namesFor("target"),distNames=namesFor("distractor");if($("summaryTargets"))$("summaryTargets").textContent=String(targetNames.length);if($("summaryDistractors"))$("summaryDistractors").textContent=String(distNames.length);if($("selectedTargetsText"))$("selectedTargetsText").textContent=targetNames.length?targetNames.join(", "):"Brak";if($("selectedDistractorsText"))$("selectedDistractorsText").textContent=distNames.length?distNames.join(", "):"Brak";if($("summaryDensity")){const d=$("density");$("summaryDensity").textContent=d?.selectedOptions?.[0]?.textContent||"—"}if($("summaryPages"))$("summaryPages").textContent=String(pages().length);if($("previewInfo"))$("previewInfo").textContent=requestedId?"Edytujesz zapisaną stronę Hidden Objects":"Nowa strona Hidden Objects"}
  function pageThumb(page){const ref=page.recipe?.content?.targets?.[0]?.assetRef||page.recipe?.content?.distractors?.[0]?.assetRef,asset=ref?FenixCore.getAsset(ref):null;if(asset?.dataUrl)return`<div class="studio-page-thumb"><img src="${asset.dataUrl}" alt=""></div>`;return'<div class="studio-page-thumb">⌕</div>'}
  function renderPages(){const list=pages(),box=$("studioPagesList");if(!box)return;$("studioPagesCount").textContent=`${list.length} ${list.length===1?"strona":"stron"}`;if($("summaryPages"))$("summaryPages").textContent=String(list.length);if(!list.length){box.innerHTML='<div class="studio-pages-empty">Nie zapisano jeszcze żadnej strony Hidden Objects.</div>';return}box.innerHTML=list.map((p,i)=>{const settings=p.recipe?.settings||{},targets=p.recipe?.content?.targets||[],dist=p.recipe?.content?.distractors||[];return`<article class="studio-page${p.id===requestedId?" current":""}">${pageThumb(p)}<div class="studio-page-copy"><strong>Hidden Objects #${String(i+1).padStart(2,"0")} · ${safe(p.title||"Find the Hidden Objects!")}</strong><small>${targets.length} celów · ${dist.length} typów dystraktorów · ${safe(settings.density||"medium")}${p.id===requestedId?" · EDYCJA":""}</small></div><div class="studio-page-actions"><button type="button" data-edit="${p.id}">Edytuj</button><button type="button" class="delete" data-delete="${p.id}">Usuń</button></div></article>`}).join("");box.querySelectorAll("[data-edit]").forEach(btn=>btn.onclick=()=>{location.href=`${location.pathname}?id=${encodeURIComponent(btn.dataset.edit)}`});box.querySelectorAll("[data-delete]").forEach(btn=>btn.onclick=()=>{const page=FenixCore.getCart().find(p=>p.id===btn.dataset.delete);if(!page)return;if(!confirm(`Usunąć stronę „${page.title||"Hidden Objects"}” z projektu?`))return;FenixCore.removePage(btn.dataset.delete);if(btn.dataset.delete===requestedId){location.href=location.pathname;return}renderPages();updateSummary()})}
  function guardSaveButton(){const cart=$("cart");if(!cart||cart.dataset.saveGuard==="1")return;const original=cart.onclick;if(typeof original!=="function")return;cart.dataset.saveGuard="1";let busy=false;cart.onclick=async event=>{if(busy){event?.preventDefault?.();return}busy=true;cart.disabled=true;cart.setAttribute("aria-busy","true");const oldText=cart.textContent;cart.textContent=requestedId?"Zapisywanie zmian…":"Zapisywanie…";try{await original.call(cart,event)}finally{busy=false;cart.disabled=false;cart.removeAttribute("aria-busy");if(cart.textContent==="Zapisywanie…"||cart.textContent==="Zapisywanie zmian…")cart.textContent=oldText}}}
  async function init(){await FenixCore.ready;const newBtn=$("newPage");if(newBtn)newBtn.onclick=()=>{location.href=location.pathname};if(requestedId&&$("cart"))$("cart").textContent="Zapisz zmiany w projekcie";guardSaveButton();renderPages();updateSummary();$("density")?.addEventListener("change",updateSummary);const observer=new MutationObserver(updateSummary);if($("assetGrid"))observer.observe($("assetGrid"),{subtree:true,childList:true,attributes:true,attributeFilter:["class"]});window.addEventListener("fenix-state-change",()=>{renderPages();updateSummary()})}
  void init();
})();