"use strict";
(()=>{
  const $=selector=>document.querySelector(selector),module=document.body.dataset.module,definition=FenixEndingRenderers.DEFINITIONS[module],canvas=$("#page"),sections=$("#endingSections"),status=$("#status"),saveStatus=$("#saveStatus");
  const escape=value=>String(value??"").replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]));
  const pages=()=>FenixCore.getCart(),requestedId=new URLSearchParams(location.search).get("id");
  const existing=()=>pages().find(page=>page.id===requestedId&&FenixPageSchema.moduleOf(page)===module)||pages().find(page=>FenixPageSchema.moduleOf(page)===module)||null;
  const field=name=>sections.querySelector(`[data-field="${name}"]`);
  function inputHtml(spec){
    const [name,label,type,option]=spec;if(type==="textarea")return `<label data-control="${name}">${escape(label)}<textarea data-field="${name}" rows="5" maxlength="${option}"></textarea></label>`;
    if(type==="select")return `<label data-control="${name}">${escape(label)}<select data-field="${name}">${option.map(([value,text])=>`<option value="${escape(value)}">${escape(text)}</option>`).join("")}</select></label>`;
    if(type==="checkbox")return `<label class="option-toggle" data-control="${name}"><input data-field="${name}" type="checkbox"><span><strong>${escape(label)}</strong><small>${escape(option||"")}</small></span></label>`;
    if(type==="asset")return `<div class="qr-asset-control" data-control="${name}"><div class="qr-asset-preview" id="qrAssetPreview"><span>Nie wybrano assetu QR</span></div><div class="qr-asset-picker"><label><span>${escape(label)}</span><select data-field="${name}" aria-label="${escape(label)}"><option value="">— Wybierz asset QR —</option></select></label><label class="qr-asset-upload">+ Dodaj QR z komputera<input id="qrAssetFile" type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml,.svg" hidden></label></div><small class="qr-asset-help">${escape(option||"")}</small><p id="qrAssetStatus" class="qr-asset-status" aria-live="polite">Asset zostanie zapisany lokalnie w aktywnym projekcie.</p></div>`;
    if(type==="number")return `<label data-control="${name}">${escape(label)}<input data-field="${name}" type="number" min="${option?.[0]??1}" max="${option?.[1]??999}"></label>`;
    return `<label data-control="${name}">${escape(label)}<input data-field="${name}" type="${type}" maxlength="${option}"></label>`;
  }
  function build(){
    const saveStep=definition.groups.length+1;
    sections.innerHTML=definition.groups.map((group,index)=>`<details data-section="${index+1}" ${index===0?"open":""}><summary><span><strong>${escape(group.title)}</strong><small>${escape(group.hint)}</small></span></summary><div class="ending-panel-body ${group.fields.length>2?"ending-grid":""}">${group.fields.map(inputHtml).join("")}</div></details>`).join("")+`<details open class="save-section"><summary><span class="save-summary-copy"><b class="save-step">${saveStep}</b><span class="save-summary-text"><strong>Projekt i zapis</strong><small>Ostatni krok — zapisz stronę w aktywnym projekcie</small></span></span><em id="pageState">NIE DODANO</em></summary><div class="ending-panel-body save-panel-body"><div class="save-explainer"><strong id="saveHeadline">Ta strona nie jest jeszcze częścią książki.</strong><span id="saveExplanation">Włącz przełącznik poniżej, aby od razu dodać ją do projektu.</span></div><label class="include-page"><input id="includePage" type="checkbox"><span><strong id="includeTitle">Dodaj stronę do projektu</strong><small id="includeHelp">Po zapisaniu Book Builder umieści ją automatycznie we właściwym miejscu.</small></span></label><div class="panel-actions save-actions"><button id="resetPage" type="button" class="ghost">Przywróć propozycję</button><button id="savePage" type="button" class="primary">Dodaj stronę do projektu</button></div></div></details>`;
  }
  const loadImage=source=>new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(new Error("Nie udało się odczytać obrazu QR."));image.src=source});
  const readFile=file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result||""));reader.onerror=()=>reject(new Error("Nie udało się odczytać pliku QR."));reader.readAsDataURL(file)});
  function refreshQrAssets(preferred=""){if(module!=="qr-studio")return;const select=field("qrAssetRef");if(!select)return;const selected=preferred||select.value,assets=FenixCore.findAssets({tag:"qr"});select.innerHTML='<option value="">— Wybierz asset QR —</option>'+assets.map(asset=>`<option value="${escape(asset.id)}">${escape(asset.name||asset.filename)} · ${asset.width||"?"}×${asset.height||"?"}</option>`).join("");select.value=assets.some(asset=>asset.id===selected)?selected:"";updateQrAssetCard()}
  function updateQrAssetCard(){if(module!=="qr-studio")return;const preview=$("#qrAssetPreview"),message=$("#qrAssetStatus"),asset=FenixCore.getAsset(field("qrAssetRef")?.value);if(!preview||!message)return;if(!asset?.dataUrl){preview.innerHTML="<span>Nie wybrano assetu QR</span>";message.textContent="Dodaj gotowy kod QR z komputera albo wybierz go z aktywnego projektu.";message.dataset.status="warning";return}preview.innerHTML=`<img src="${escape(asset.dataUrl)}" alt="Podgląd assetu QR"><span>${escape(asset.name)}</span>`;const square=asset.width&&asset.height?Math.abs(asset.width/asset.height-1)<=.08:true,largeEnough=!asset.width||!asset.height||Math.min(asset.width,asset.height)>=500;message.textContent=!square?"Uwaga: asset nie jest kwadratowy — sprawdź obszar bezpieczeństwa kodu.":!largeEnough?"Uwaga: asset ma mniej niż 500 px i może być zbyt mały do druku.":"Asset QR jest wybrany i zostanie użyty w podglądzie oraz finalnym PDF.";message.dataset.status=square&&largeEnough?"ok":"warning"}
  async function importQrAsset(file){if(!file)return;const message=$("#qrAssetStatus"),allowed=/\.(png|jpe?g|webp|svg)$/i.test(file.name)||["image/png","image/jpeg","image/webp","image/svg+xml"].includes(file.type);if(!allowed)throw new Error("Wybierz plik PNG, JPG, WEBP albo SVG.");if(file.size>5*1024*1024)throw new Error("Asset QR może mieć maksymalnie 5 MB.");message.textContent="Dodaję asset QR do aktywnego projektu…";message.dataset.status="working";const dataUrl=await readFile(file),image=await loadImage(dataUrl),width=image.naturalWidth||image.width||0,height=image.naturalHeight||image.height||0,square=width&&height?Math.abs(width/height-1)<=.08:true,largeEnough=!width||!height||Math.min(width,height)>=500,status=square&&largeEnough?"ok":"warning",messages=[];if(!square)messages.push("Asset QR nie jest kwadratowy.");if(!largeEnough)messages.push("Rozdzielczość assetu QR jest mniejsza niż 500 px.");const asset=FenixCore.putAsset({name:`QR · ${file.name.replace(/\.[^.]+$/,"")}`,filename:file.name,mime:file.type||"image/png",dataUrl,source:"qr-studio",width,height,sizeBytes:file.size,aspectRatio:width&&height?Number((width/height).toFixed(4)):null,tags:["qr","content"],validation:{status,messages,metrics:{width,height,square}},meta:{role:"qr",studio:"qr-studio"}});refreshQrAssets(asset.id);field("qrAssetRef").value=asset.id;updateQrAssetCard();queue()}
  function values(){const result={};definition.groups.flatMap(group=>group.fields).forEach(([name,,type])=>{const input=field(name);result[name]=type==="checkbox"?input.checked:type==="number"?Math.max(Number(input.min)||1,Math.min(Number(input.max)||999,Number(input.value)||Number(definition.defaults[name])||1)):input.value.trim()});return result}
  function fill(settings){definition.groups.flatMap(group=>group.fields).forEach(([name,,type])=>{const input=field(name),value=settings[name]??definition.defaults[name]??"";if(type==="checkbox")input.checked=Boolean(value);else input.value=value})}
  const STRUCTURAL_MODULES=new Set(["intro-studio","blank-page","certificate-studio","congratulations-studio","qr-studio","solutions-studio"]);
  function detectedActivityCount(){return FenixCore.getCart().filter(page=>!STRUCTURAL_MODULES.has(FenixPageSchema.moduleOf(page))).length}
  function syncCongratulationsFields(){if(module!=="congratulations-studio")return;const mode=field("countMode"),count=field("activityCount");if(!mode||!count)return;const automatic=mode.value==="auto";count.disabled=automatic;if(automatic)count.value=detectedActivityCount()||definition.defaults.activityCount;count.title=automatic?`Wykryto w projekcie: ${detectedActivityCount()} aktywności.`:"Liczba ustawiona ręcznie."}
  let renderSequence=0;async function render(){const sequence=++renderSequence;status.textContent="Aktualizuję…";try{const settings=values(),page=FenixEndingRenderers.page(module,settings,existing()),asset=module==="qr-studio"&&settings.qrAssetRef?FenixCore.getAsset(settings.qrAssetRef):null,qrAssetImage=asset?.dataUrl?await loadImage(asset.dataUrl):null,rendered=FenixEndingRenderers.render(page,{width:2550,height:3300,qrAssetImage});if(sequence!==renderSequence)return;const ctx=canvas.getContext("2d");ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(rendered,0,0);status.textContent=module==="qr-studio"&&!qrAssetImage?"Dodaj asset QR":"Podgląd aktualny"}catch(error){if(sequence===renderSequence)status.textContent=error.message}}
  let timer;const queue=()=>{syncCongratulationsFields();clearTimeout(timer);timer=setTimeout(render,100);if(existing()){saveStatus.textContent="Masz niezapisane zmiany — kliknij „Aktualizuj stronę”.";saveStatus.classList.add("unsaved");$("#savePage").classList.add("needs-save")}};
  function state(){const page=existing(),included=Boolean(page);$("#includePage").checked=included;$("#pageState").textContent=included?"✓ W PROJEKCIE":"NIE DODANO";$("#pageState").classList.toggle("included",included);$("#saveHeadline").textContent=included?"Ta strona jest już częścią książki.":"Ta strona nie jest jeszcze częścią książki.";$("#saveExplanation").textContent=included?"Po zmianie treści użyj przycisku „Aktualizuj stronę”, aby zapisać nową wersję.":"Włącz przełącznik poniżej albo kliknij przycisk, aby dodać ją do projektu.";$("#includeTitle").textContent=included?"Strona uwzględniona w projekcie":"Dodaj stronę do projektu";$("#includeHelp").textContent=included?"Wyłączenie przełącznika usunie stronę z projektu.":"Book Builder umieści ją automatycznie we właściwym miejscu.";$("#savePage").textContent=included?"Aktualizuj stronę":"Dodaj stronę do projektu";$("#savePage").classList.remove("needs-save");saveStatus.classList.remove("unsaved")}
  function save(){const settings=values();if(module==="qr-studio"&&!settings.qrAssetRef)return alert("Najpierw dodaj lub wybierz asset kodu QR.");const original=existing(),page=FenixEndingRenderers.page(module,settings,original);if(original)FenixCore.updatePage(original.id,page);else FenixCore.addPage(page);state();saveStatus.textContent=original?`✓ Zaktualizowano „${page.title}”.`:`✓ Dodano „${page.title}” do projektu.`;saveStatus.classList.add("saved");setTimeout(()=>saveStatus.classList.remove("saved"),1800)}
  build();const initialSettings=FenixEndingRenderers.fromPage(existing(),module);refreshQrAssets(initialSettings.qrAssetRef);fill(initialSettings);updateQrAssetCard();syncCongratulationsFields();state();render();
  sections.querySelectorAll("input:not(#includePage):not([type=file]),textarea,select").forEach(input=>input.addEventListener("input",()=>{if(input.dataset.field==="qrAssetRef")updateQrAssetCard();queue()}));
  if(module==="qr-studio"){$("#qrAssetFile").onchange=async event=>{const file=event.target.files?.[0];try{await importQrAsset(file)}catch(error){$("#qrAssetStatus").textContent=error.message;$("#qrAssetStatus").dataset.status="error"}finally{event.target.value=""}};window.addEventListener("fenix-assets-change",()=>refreshQrAssets(field("qrAssetRef")?.value))}
  $("#savePage").onclick=save;$("#resetPage").onclick=()=>{fill(definition.defaults);syncCongratulationsFields();render();saveStatus.textContent="Przywrócono propozycję. Zapisz, aby zaktualizować projekt."};
  $("#includePage").onchange=event=>{const page=existing();if(event.target.checked){save();return}if(page&&confirm(`Usunąć stronę „${page.title}” z projektu?`)){FenixCore.removePage(page.id);state();saveStatus.textContent="Usunięto stronę z projektu."}else state()};
  $("#downloadPng").onclick=async()=>{await render();FenixCore.downloadCanvas(canvas,`${definition.file}-300dpi.png`)};
})();
