"use strict";
(()=>{
  const $=selector=>document.querySelector(selector),module=document.body.dataset.module,definition=FenixEndingRenderers.DEFINITIONS[module],canvas=$("#page"),sections=$("#endingSections"),status=$("#status"),saveStatus=$("#saveStatus");
  const escape=value=>String(value??"").replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]));
  const pages=()=>FenixCore.getCart(),requestedId=new URLSearchParams(location.search).get("id");
  const existing=()=>pages().find(page=>page.id===requestedId&&FenixPageSchema.moduleOf(page)===module)||pages().find(page=>FenixPageSchema.moduleOf(page)===module)||null;
  const field=name=>sections.querySelector(`[data-field="${name}"]`);
  function inputHtml(spec){
    const [name,label,type,option]=spec;if(type==="textarea")return `<label>${escape(label)}<textarea data-field="${name}" rows="5" maxlength="${option}"></textarea></label>`;
    if(type==="select")return `<label>${escape(label)}<select data-field="${name}">${option.map(([value,text])=>`<option value="${escape(value)}">${escape(text)}</option>`).join("")}</select></label>`;
    return `<label>${escape(label)}<input data-field="${name}" type="${type}" maxlength="${option}"></label>`;
  }
  function build(){
    sections.innerHTML=definition.groups.map((group,index)=>`<details ${index===0?"open":""}><summary><span><strong>${escape(group.title)}</strong><small>${escape(group.hint)}</small></span></summary><div class="ending-panel-body ${group.fields.length>2?"ending-grid":""}">${group.fields.map(inputHtml).join("")}</div></details>`).join("")+`<details open class="save-section"><summary><span class="save-summary-copy"><b class="save-step">3</b><span class="save-summary-text"><strong>Projekt i zapis</strong><small>Ostatni krok — zapisz stronę w aktywnym projekcie</small></span></span><em id="pageState">NIE DODANO</em></summary><div class="ending-panel-body save-panel-body"><div class="save-explainer"><strong id="saveHeadline">Ta strona nie jest jeszcze częścią książki.</strong><span id="saveExplanation">Włącz przełącznik poniżej, aby od razu dodać ją do projektu.</span></div><label class="include-page"><input id="includePage" type="checkbox"><span><strong id="includeTitle">Dodaj stronę do projektu</strong><small id="includeHelp">Po zapisaniu Book Builder umieści ją automatycznie we właściwym miejscu.</small></span></label><div class="panel-actions save-actions"><button id="resetPage" type="button" class="ghost">Przywróć propozycję</button><button id="savePage" type="button" class="primary">Dodaj stronę do projektu</button></div></div></details>`;
  }
  function values(){const result={};definition.groups.flatMap(group=>group.fields).forEach(([name])=>result[name]=field(name).value.trim());return result}
  function fill(settings){definition.groups.flatMap(group=>group.fields).forEach(([name])=>{field(name).value=settings[name]??definition.defaults[name]??""})}
  function render(){status.textContent="Aktualizuję…";try{const page=FenixEndingRenderers.page(module,values(),existing());const rendered=FenixEndingRenderers.render(page,{width:2550,height:3300}),ctx=canvas.getContext("2d");ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(rendered,0,0);status.textContent="Podgląd aktualny"}catch(error){status.textContent=error.message}}
  let timer;const queue=()=>{clearTimeout(timer);timer=setTimeout(render,100);if(existing()){saveStatus.textContent="Masz niezapisane zmiany — kliknij „Aktualizuj stronę”.";saveStatus.classList.add("unsaved");$("#savePage").classList.add("needs-save")}};
  function state(){const page=existing(),included=Boolean(page);$("#includePage").checked=included;$("#pageState").textContent=included?"✓ W PROJEKCIE":"NIE DODANO";$("#pageState").classList.toggle("included",included);$("#saveHeadline").textContent=included?"Ta strona jest już częścią książki.":"Ta strona nie jest jeszcze częścią książki.";$("#saveExplanation").textContent=included?"Po zmianie treści użyj przycisku „Aktualizuj stronę”, aby zapisać nową wersję.":"Włącz przełącznik poniżej albo kliknij przycisk, aby dodać ją do projektu.";$("#includeTitle").textContent=included?"Strona uwzględniona w projekcie":"Dodaj stronę do projektu";$("#includeHelp").textContent=included?"Wyłączenie przełącznika usunie stronę z projektu.":"Book Builder umieści ją automatycznie we właściwym miejscu.";$("#savePage").textContent=included?"Aktualizuj stronę":"Dodaj stronę do projektu";$("#savePage").classList.remove("needs-save");saveStatus.classList.remove("unsaved")}
  function save(){const original=existing(),page=FenixEndingRenderers.page(module,values(),original);if(original)FenixCore.updatePage(original.id,page);else FenixCore.addPage(page);state();saveStatus.textContent=original?`✓ Zaktualizowano „${page.title}”.`:`✓ Dodano „${page.title}” do projektu.`;saveStatus.classList.add("saved");setTimeout(()=>saveStatus.classList.remove("saved"),1800)}
  build();fill(FenixEndingRenderers.fromPage(existing(),module));state();render();
  sections.querySelectorAll("input:not(#includePage),textarea,select").forEach(input=>input.addEventListener("input",queue));
  $("#savePage").onclick=save;$("#resetPage").onclick=()=>{fill(definition.defaults);render();saveStatus.textContent="Przywrócono propozycję. Zapisz, aby zaktualizować projekt."};
  $("#includePage").onchange=event=>{const page=existing();if(event.target.checked){save();return}if(page&&confirm(`Usunąć stronę „${page.title}” z projektu?`)){FenixCore.removePage(page.id);state();saveStatus.textContent="Usunięto stronę z projektu."}else state()};
  $("#downloadPng").onclick=()=>{render();FenixCore.downloadCanvas(canvas,`${definition.file}-300dpi.png`)};
})();
