"use strict";

(async()=>{
  const script=document.currentScript||[...document.scripts].find(s=>/\/modules\/studio-engine\.js(?:\?|$)/.test(s.src));
  const load=(relative,test)=>new Promise((resolve,reject)=>{if(test())return resolve();const node=document.createElement("script");node.src=new URL(relative,script?.src||location.href).href;node.onload=resolve;node.onerror=()=>reject(new Error(`Nie udało się załadować ${relative}`));document.head.appendChild(node)});
  await load("../config/module-registry.js",()=>Boolean(window.FenixModuleRegistry));
  await load("../core/page-schema.js",()=>Boolean(window.FenixPageSchema));
  await load("../core/production-profile.js",()=>Boolean(window.FenixProduction));
  await load("shared/standard-renderers.js",()=>Boolean(window.FenixStandardRenderers));

  const slug=document.body.dataset.module||"",cfg=FenixModuleRegistry.get(slug);if(!cfg||cfg.engine!=="standard")throw new Error(`Nieobsługiwane Studio: ${slug}`);
  const $=selector=>document.querySelector(selector),val=(selector,fallback)=>{const el=$(selector);return el&&el.value!==""?el.value:fallback},clamp=(n,min,max)=>Math.max(min,Math.min(max,n));
  const INSTRUCTIONS={"logic-studio":{sequence:"Continue the sequence.",odd:"Circle the one that does not belong.",matrix:"Complete the matrix.",sudoku:"Complete the picture sudoku.",analogy:"Complete the analogy."},"math-studio":{operations:"Solve the problems.",missing:"Write the missing number.",compare:"Insert >, < or =.",count:"Count and write the answer.",pyramid:"Complete the number pyramids.",sequence:"Write the missing number in each sequence."},"alphabet-studio":{"letter-day":"Practice the letter.",trace:"Trace the letters.",find:"Find and circle the letter.","match-case":"Match uppercase and lowercase letters.",missing:"Write the missing letters.",words:"Copy the words."},"tracing-studio":{waves:"Trace the lines.",zigzag:"Trace the zigzags.",loops:"Trace the loops.",paths:"Follow the paths.",shapes:"Trace the shapes.",mixed:"Practice different lines."},"matching-studio":{identical:"Match identical items.","shape-shadow":"Match each item to its shadow.","number-quantity":"Match numbers to quantities.","letter-case":"Match uppercase and lowercase letters.","operation-result":"Match each operation to its result.",category:"Match items from the same category."},"hidden-objects-studio":{symbols:"Find the hidden symbols.",numbers:"Find the hidden numbers.",letters:"Find the hidden letters.",pairs:"Find the matching pairs.",different:"Find the different item."},"dot-to-dot-studio":{circle:"Connect the dots.",star:"Connect the dots.",heart:"Connect the dots.",flower:"Connect the dots.",spiral:"Connect the dots."},"coloring-studio":{mandala:"Color the picture.",animals:"Color the picture.",flowers:"Color the flowers.",space:"Color the space scene.",patterns:"Color the pattern.","color-number":"Color by number."}};
  const instructionFor=type=>INSTRUCTIONS[slug]?.[type]||"Complete the activity.";
  function options(){const type=val("#type",cfg.types[0]?.[0]||"");return{type,title:val("#title",cfg.name),instructions:val("#instructions",instructionFor(type)),seed:val("#seed","fenix"),difficulty:val("#difficulty","medium"),age:val("#age","5-7"),language:val("#language","en"),count:clamp(parseInt(val("#count",1),10)||1,1,20),range:clamp(parseInt(val("#range",20),10)||20,5,100),extra:val("#extra","A")}}

  const state={pages:[],index:0};let refreshTimer=null;
  function setStatus(text,error=false){const el=$("#status");if(!el)return;el.textContent=text;el.dataset.type=error?"error":"ok"}
  function updateInfo(){const type=val("#type",cfg.types[0]?.[0]),item=cfg.types.find(([id])=>id===type)||cfg.types[0];let info=$("#exerciseInfo");if(!info){info=document.createElement("div");info.id="exerciseInfo";info.className="exercise-info";$("#type")?.closest("label")?.insertAdjacentElement("afterend",info)}if(info&&item)info.innerHTML=`<strong>${item[1]}</strong><span>${item[2]||""}</span><small>Podgląd aktualizuje się automatycznie.</small>`}
  function show(){const current=state.pages[state.index],target=$("#page");if(!current||!target)return;target.width=850;target.height=1100;target.getContext("2d").drawImage(current.pageCanvas,0,0,850,1100);$("#pageCounter").textContent=`${state.index+1} / ${state.pages.length}`;$("#prev").disabled=state.index===0;$("#next").disabled=state.index===state.pages.length-1}
  function build(){try{const o=options();state.pages=[];for(let i=0;i<o.count;i++){const seed=`${o.seed}-${i+1}`,rendered=FenixStandardRenderers.render(slug,{...o,instructions:o.instructions||instructionFor(o.type)},seed,i,1);state.pages.push({...rendered,seed,options:{...o,instructions:o.instructions||instructionFor(o.type)}})}state.index=0;updateInfo();show();setStatus(`Wygenerowano ${state.pages.length} stron.`)}catch(error){console.error(error);setStatus(`Błąd generatora: ${error.message}`,true)}}
  function scheduleBuild(){clearTimeout(refreshTimer);refreshTimer=setTimeout(build,120)}
  function pagePayload(item,index){const o=item.options,project=FenixCore.getActiveProject(),production=FenixProduction.profile(project.format,project.bleed),validation=FenixProduction.validation(production);return FenixPageSchema.normalize({module:slug,title:o.title,seed:item.seed,recipe:{module:slug,seed:item.seed,title:o.title,settings:{type:o.type,difficulty:o.difficulty,age:o.age,language:o.language,range:o.range,extra:o.extra,instructions:o.instructions,pageIndex:index},meta:{createdWith:"FENIX PC",moduleVersion:3,production}},preview:{imageData:null},solution:{available:Boolean(item.hasSolution),imageData:null},validation:{kdp:validation},production,source:{app:"fenix-desktop",version:"0.17.0",format:"native"}})}
  function addToCart(){if(!state.pages.length)build();if(!state.pages.length)return;state.pages.forEach((item,index)=>FenixCore.addPage(pagePayload(item,index)));setStatus(`Dodano ${state.pages.length} stron do projektu „${FenixCore.getActiveProject().name}”.`)}
  function exportPng(){const current=state.pages[state.index];if(!current)return;const project=FenixCore.getActiveProject(),high=FenixStandardRenderers.render(slug,current.options,current.seed,state.index,3),fitted=FenixProduction.fitCanvas(high.pageCanvas,project.format,project.bleed);FenixCore.downloadCanvas(fitted.canvas,`${slug}-${String(current.seed).replace(/[^a-z0-9_-]+/gi,"-")}.png`)}
  function randomSeed(){const input=$("#seed");if(!input)return;input.value=`fenix-${slug.replace(/-studio$/,'')}-${Date.now().toString(36)}`;build()}
  function applyPreset(){const preset=val("#preset","");if(!preset)return;const values={preschool:{age:"3-5",difficulty:"easy",range:10},early:{age:"5-7",difficulty:"medium",range:20},advanced:{age:"7-9",difficulty:"hard",range:50}}[preset];if(!values)return;if($("#age"))$("#age").value=values.age;if($("#difficulty"))$("#difficulty").value=values.difficulty;if($("#range"))$("#range").value=values.range;build()}

  document.title=`${cfg.name} — FENIX`;if($("#studioName"))$("#studioName").textContent=cfg.name;if($("#studioSubtitle"))$("#studioSubtitle").textContent="Generator produkcyjny · 300 DPI przy eksporcie";
  const type=$("#type");if(type){type.innerHTML=cfg.types.map(([id,label])=>`<option value="${id}">${label}</option>`).join("");type.disabled=false}
  const projectInfo=$("#projectInfo"),renderProject=()=>{if(projectInfo){const p=FenixCore.getActiveProject(),prod=FenixProduction.profile(p.format,p.bleed);projectInfo.textContent=`Aktywny projekt: ${p.name} · ${p.format==="a4"?"A4":p.format} · ${p.bleed==="bleed"?"ze spadami":"bez spadów"} · ${prod.width}×${prod.height}px`}};renderProject();window.addEventListener("fenix-state-change",event=>{if(event.detail?.activeProject||event.detail?.projects){renderProject();scheduleBuild()}});
  $("#generate").onclick=build;$("#randomSeed").onclick=randomSeed;$("#png").onclick=exportPng;$("#cart").onclick=addToCart;$("#prev").onclick=()=>{if(state.index>0){state.index--;show()}};$("#next").onclick=()=>{if(state.index<state.pages.length-1){state.index++;show()}};$("#preset")?.addEventListener("change",applyPreset);
  ["type","difficulty","age","count","range","title","instructions","seed","extra","language"].forEach(id=>$("#"+id)?.addEventListener(id==="title"||id==="instructions"||id==="seed"||id==="extra"?"input":"change",scheduleBuild));
  build();
})().catch(error=>{console.error(error);const status=document.querySelector("#status");if(status)status.textContent=`FENIX Studio nie uruchomiło się: ${error.message}`});
