"use strict";
(()=>{
 const base=window.FenixMaze;if(!base)return;
 const VERSION="0.33.0",clone=v=>v==null?v:typeof structuredClone==="function"?structuredClone(v):JSON.parse(JSON.stringify(v));
 const clamp=(v,a,b,f)=>{v=Number(v);return Math.max(a,Math.min(b,Number.isFinite(v)?v:f))},key=(x,y)=>`${x},${y}`;
 function settingsOf(page){return{...(page?.settings||{}),...(page?.recipe?.settings||{})}}
 function rng(seed){let s=(Number(seed)||1)>>>0;return()=>{s=(Math.imul(s,1664525)+1013904223)>>>0;return s/4294967296}}
 function shuffle(a,r){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
 const DIRS=[[0,-1,0,2],[1,0,1,3],[0,1,2,0],[-1,0,3,1]];
 function neighbors(maze,x,y){return DIRS.map(([dx,dy,w,o])=>({nx:x+dx,ny:y+dy,w,o})).filter(p=>p.nx>=0&&p.ny>=0&&p.nx<maze.cols&&p.ny<maze.rows)}
 function degree(maze,x,y){return maze.cells[y][x].w.reduce((n,w)=>n+(w?0:1),0)}
 function turns(path){let n=0;for(let i=2;i<path.length;i++){const a=path[i-2],b=path[i-1],c=path[i];if((b[0]-a[0])!==(c[0]-b[0])||(b[1]-a[1])!==(c[1]-b[1]))n++}return n}
 function footprint(image,scalePct,baseSize=.82){const pct=clamp(scalePct,40,180,100)/100,iw=image?.naturalWidth||image?.width||1,ih=image?.naturalHeight||image?.height||1,ratio=iw/ih;let w=baseSize*pct,h=baseSize*pct;if(ratio>1)h/=ratio;else w*=ratio;return{w:Math.max(1,Math.min(4,Math.ceil(w+.65))),h:Math.max(1,Math.min(4,Math.ceil(h+.65)))}}
 function rectCells(z){const out=[];for(let y=z.y;y<z.y+z.h;y++)for(let x=z.x;x<z.x+z.w;x++)out.push([x,y]);return out}
 function overlaps(a,b,pad=0){return a.x-pad<b.x+b.w&&a.x+a.w+pad>b.x&&a.y-pad<b.y+b.h&&a.y+a.h+pad>b.y}
 function endpointRoom(ep,dims,cols,rows,role){let x=0,y=0;if(ep.side==="top"){x=Math.round(ep.x-(dims.w-1)/2);y=0}else if(ep.side==="bottom"){x=Math.round(ep.x-(dims.w-1)/2);y=rows-dims.h}else if(ep.side==="left"){x=0;y=Math.round(ep.y-(dims.h-1)/2)}else{x=cols-dims.w;y=Math.round(ep.y-(dims.h-1)/2)}x=Math.max(0,Math.min(cols-dims.w,x));y=Math.max(0,Math.min(rows-dims.h,y));const z={role,x,y,w:dims.w,h:dims.h,side:ep.side};z.cx=x+(dims.w-1)/2;z.cy=y+(dims.h-1)/2;return z}
 function roomAround(anchor,dims,cols,rows,role,zones){for(let rad=0;rad<6;rad++)for(let dy=-rad;dy<=rad;dy++)for(let dx=-rad;dx<=rad;dx++){const x=Math.max(1,Math.min(cols-dims.w-1,Math.round(anchor[0]-(dims.w-1)/2)+dx)),y=Math.max(1,Math.min(rows-dims.h-1,Math.round(anchor[1]-(dims.h-1)/2)+dy)),z={role,x,y,w:dims.w,h:dims.h,cx:x+(dims.w-1)/2,cy:y+(dims.h-1)/2};if(!zones.some(q=>overlaps(z,q,1)))return z}return null}
 function allZoneKeys(zones){return new Set(zones.flatMap(z=>rectCells(z).map(([x,y])=>key(x,y))))}
 function openWall(maze,x,y,n){maze.cells[y][x].w[n.w]=false;maze.cells[n.ny][n.nx].w[n.o]=false}
 function openBetween(maze,a,b){const dx=b[0]-a[0],dy=b[1]-a[1],d=DIRS.find(q=>q[0]===dx&&q[1]===dy);if(d)openWall(maze,a[0],a[1],{nx:b[0],ny:b[1],w:d[2],o:d[3]})}
 function portalCandidates(z,cols,rows){const out=[];for(const [x,y] of rectCells(z))for(const [dx,dy,w,o] of DIRS){const nx=x+dx,ny=y+dy;if(nx<0||ny<0||nx>=cols||ny>=rows)continue;if(nx>=z.x&&nx<z.x+z.w&&ny>=z.y&&ny<z.y+z.h)continue;out.push({x,y,nx,ny,w,o})}return out}
 function preferredEndpointPortal(z,cols,rows){const c=portalCandidates(z,cols,rows);const want=z.side==="top"?2:z.side==="bottom"?0:z.side==="left"?1:3;return c.filter(p=>p.w===want).sort((a,b)=>Math.abs(a.x-z.cx)+Math.abs(a.y-z.cy)-Math.abs(b.x-z.cx)-Math.abs(b.y-z.cy))[0]||c[0]}
 function constrainedBuild(cols,rows,seed,endpoints,zones){const r=rng(seed),cells=Array.from({length:rows},()=>Array.from({length:cols},()=>({v:false,w:[true,true,true,true]}))),maze={cols,rows,cells,seed,start:null,end:null,assetZones:clone(zones)},blocked=allZoneKeys(zones),free=[];for(let y=0;y<rows;y++)for(let x=0;x<cols;x++)if(!blocked.has(key(x,y)))free.push([x,y]);const visited=new Set();for(const first of free){if(visited.has(key(...first)))continue;const stack=[first];visited.add(key(...first));while(stack.length){const[x,y]=stack[stack.length-1],choices=[];for(const[dx,dy,w,o]of DIRS){const nx=x+dx,ny=y+dy,k=key(nx,ny);if(nx>=0&&ny>=0&&nx<cols&&ny<rows&&!blocked.has(k)&&!visited.has(k))choices.push({nx,ny,w,o})}if(!choices.length){stack.pop();continue}const n=choices[Math.floor(r()*choices.length)];openWall(maze,x,y,n);visited.add(key(n.nx,n.ny));stack.push([n.nx,n.ny])}}
  for(const z of zones){for(const[x,y]of rectCells(z))for(const[dx,dy,w,o]of DIRS){const nx=x+dx,ny=y+dy;if(nx>=z.x&&nx<z.x+z.w&&ny>=z.y&&ny<z.y+z.h&&nx>=0&&ny>=0&&nx<cols&&ny<rows)openWall(maze,x,y,{nx,ny,w,o})}
   const pc=portalCandidates(z,cols,rows).filter(p=>!blocked.has(key(p.nx,p.ny))),rr=rng(seed+(z.x+1)*7919+(z.y+1)*104729),ordered=shuffle(pc,rr);let portals=[];if(z.role==="start"||z.role==="goal"){const p=preferredEndpointPortal(z,cols,rows);if(p&&!blocked.has(key(p.nx,p.ny)))portals=[p]}else if(z.role==="checkpoint")portals=ordered.slice(0,Math.min(2,ordered.length));else portals=ordered.slice(0,Math.min(1,ordered.length));for(const p of portals)openWall(maze,p.x,p.y,p);z.portals=portals.map(p=>({x:p.x,y:p.y,nx:p.nx,ny:p.ny}))
  }
  const sz=zones.find(z=>z.role==="start"),gz=zones.find(z=>z.role==="goal");function boundaryCell(z,ep){if(ep.side==="top")return[Math.max(z.x,Math.min(z.x+z.w-1,Math.round(z.cx))),z.y,0];if(ep.side==="bottom")return[Math.max(z.x,Math.min(z.x+z.w-1,Math.round(z.cx))),z.y+z.h-1,2];if(ep.side==="left")return[z.x,Math.max(z.y,Math.min(z.y+z.h-1,Math.round(z.cy))),3];return[z.x+z.w-1,Math.max(z.y,Math.min(z.y+z.h-1,Math.round(z.cy))),1]}
  const bs=boundaryCell(sz,endpoints.start),bg=boundaryCell(gz,endpoints.end);cells[bs[1]][bs[0]].w[bs[2]]=false;cells[bg[1]][bg[0]].w[bg[2]]=false;maze.start={x:bs[0],y:bs[1],wall:bs[2],side:endpoints.start.side};maze.end={x:bg[0],y:bg[1],wall:bg[2],side:endpoints.end.side};return maze}
 function bfs(maze,start,end,blocked=new Set()){const q=[start],seen=new Set([key(...start)]),prev=new Map();while(q.length){const[x,y]=q.shift();if(x===end[0]&&y===end[1])break;for(const[dx,dy,w]of DIRS){const nx=x+dx,ny=y+dy,k=key(nx,ny);if(nx<0||ny<0||nx>=maze.cols||ny>=maze.rows||maze.cells[y][x].w[w]||seen.has(k)||blocked.has(k))continue;seen.add(k);prev.set(k,[x,y]);q.push([nx,ny])}}if(!seen.has(key(...end)))return[];const p=[];let cur=end;while(cur){p.push(cur);if(cur[0]===start[0]&&cur[1]===start[1])break;cur=prev.get(key(...cur))}return p.reverse()}
 function roomCenterCell(z){return[Math.max(z.x,Math.min(z.x+z.w-1,Math.round(z.cx))),Math.max(z.y,Math.min(z.y+z.h-1,Math.round(z.cy)))]}
 function solveVia(maze,zones){const hazards=zones.filter(z=>z.role==="hazard"),blocked=new Set(hazards.flatMap(z=>rectCells(z).map(([x,y])=>key(x,y)))),targets=[...zones.filter(z=>z.role==="checkpoint").map(roomCenterCell),[maze.end.x,maze.end.y]],full=[];let st=[maze.start.x,maze.start.y];for(const t of targets){const part=bfs(maze,st,t,blocked);if(!part.length)return[];full.push(...(full.length?part.slice(1):part));st=t}return full}
 function safeTopology(source,seed,wallOpenings,deadEndPct){const maze=clone(source),protectedSet=new Set((maze.assetZones||[]).flatMap(z=>rectCells(z).map(([x,y])=>key(x,y)))),r=rng(seed^0x71a5b3c9),candidates=[];for(let y=0;y<maze.rows;y++)for(let x=0;x<maze.cols;x++)if(!protectedSet.has(key(x,y)))for(const p of neighbors(maze,x,y)){if(protectedSet.has(key(p.nx,p.ny))||p.ny<y||(p.ny===y&&p.nx<x)||!maze.cells[y][x].w[p.w])continue;candidates.push({x,y,p})}const maxExtra=Math.max(0,Math.round(maze.cols*maze.rows*(.008+.03*clamp(wallOpenings,0,100,15)/100)));let opened=0;for(const e of shuffle(candidates,r)){if(opened>=maxExtra)break;if(degree(maze,e.x,e.y)>=3||degree(maze,e.p.nx,e.p.ny)>=3)continue;openWall(maze,e.x,e.y,e.p);opened++}return{maze,opened}}
 function chooseMissionAnchors(provisional,path,seed,s,zones,assetImages){const result=[...zones],r=rng(seed^0xc0ffee),cc=Math.max(0,Math.min(5,Number(s.checkpointCount)||0)),hc=Math.max(0,Math.min(8,Number(s.hazardCount)||0)),cpDims=footprint(assetImages?.[s.checkpointAssetRef],s.checkpointScale,.78),hzDims=footprint(assetImages?.[s.hazardAssetRef],s.hazardScale,.78),inner=path.length>8?path.slice(3,-3):path.slice(1,-1);for(let i=0;i<cc&&inner.length;i++){const idx=Math.min(inner.length-1,Math.round((i+1)*(inner.length-1)/(cc+1))),z=roomAround(inner[idx],cpDims,provisional.cols,provisional.rows,"checkpoint",result);if(z)result.push(z)}const route=new Set(path.map(p=>key(...p))),outside=[];for(let y=1;y<provisional.rows-1;y++)for(let x=1;x<provisional.cols-1;x++)if(!route.has(key(x,y)))outside.push([x,y]);for(const a of shuffle(outside,r)){if(result.filter(z=>z.role==="hazard").length>=hc)break;const z=roomAround(a,hzDims,provisional.cols,provisional.rows,"hazard",result);if(z)result.push(z)}return result}
 function pick(page,opts){const s=settingsOf(page),cols=Math.max(6,Number(s.cols)||18),rows=Math.max(8,Number(s.rows)||24),baseSeed=Number(page?.recipe?.seed??page?.seed??1)||1,target=clamp(s.pathTarget,10,100,50),twist=clamp(s.twistiness,0,100,50),saved=s.endpoints||page?.recipe?.meta?.renderState?.endpoints,assetImages=opts?.assetImages||{},c=[];for(let i=0;i<24;i++){const seed=baseSeed+i*104729,ep=saved?.start&&saved?.end?saved:base.endpointsForMode(s.endpointMode||"random",cols,rows,seed),startDims=footprint(assetImages?.[s.startAssetRef],s.startAssetScale,.82),goalDims=footprint(assetImages?.[s.goalAssetRef],s.goalAssetScale,.82),baseZones=[endpointRoom(ep.start,startDims,cols,rows,"start"),endpointRoom(ep.end,goalDims,cols,rows,"goal")];if(overlaps(baseZones[0],baseZones[1],1))continue;const provisional=constrainedBuild(cols,rows,seed,ep,clone(baseZones)),pp=base.solve(provisional);if(pp.length<2)continue;const zones=chooseMissionAnchors(provisional,pp,seed,s,baseZones,assetImages),raw=constrainedBuild(cols,rows,seed,ep,zones),t=safeTopology(raw,seed,s.wallOpenings,s.deadEnds),maze=t.maze,path=solveVia(maze,maze.assetZones||zones);if(path.length<2)continue;const turn=turns(path);c.push({seed,maze,path,zones:maze.assetZones||zones,len:path.length,turn,opened:t.opened})}if(!c.length){const ep=base.endpointsForMode(s.endpointMode||"random",cols,rows,baseSeed),zones=[endpointRoom(ep.start,{w:1,h:1},cols,rows,"start"),endpointRoom(ep.end,{w:1,h:1},cols,rows,"goal")],maze=constrainedBuild(cols,rows,baseSeed,ep,zones);return{seed:baseSeed,maze,path:base.solve(maze),zones,opened:0}}
  const min=Math.min(...c.map(x=>x.len)),max=Math.max(...c.map(x=>x.len));for(const x of c){x.lenPct=max===min?50:10+90*(x.len-min)/(max-min);x.turnPct=x.path.length<3?0:100*x.turn/(x.path.length-2);x.score=Math.abs(x.lenPct-target)+.55*Math.abs(x.turnPct-twist)}c.sort((a,b)=>a.score-b.score);const best=c[0];best.checkpoints=best.zones.filter(z=>z.role==="checkpoint").map(roomCenterCell);best.hazards=best.zones.filter(z=>z.role==="hazard").map(roomCenterCell);best.stats={pathCells:best.path.length,pathPct:Math.round(best.lenPct||50),turns:best.turn||0,turnPct:Math.round(best.turnPct||0),extraOpenings:best.opened,reservedRooms:best.zones.length};return best}
 const advanced={...base,engineVersion:VERSION,render(page,opts={}){const choice=pick(page,opts),p=clone(page||{}),s=settingsOf(page);p.seed=choice.seed;p.recipe=p.recipe||{};p.recipe.seed=choice.seed;p.settings={...(p.settings||{}),...s};p.recipe.settings={...(p.recipe.settings||{}),...s};const result=base.render(p,{...opts,solution:false});return{...result,maze:choice.maze,checkpoints:choice.checkpoints||[],hazards:choice.hazards||[],assetZones:choice.zones||[],solutionPath:choice.path||[],difficultyStats:choice.stats||{},effectiveSeed:choice.seed,engineVersion:VERSION}}};
 window.FenixMaze=Object.freeze(advanced);
})();