"use strict";
(()=>{
 const $=id=>document.getElementById(id),canvas=$("page"),status=$("status"),select=$("pageSelect"),difficultyInfo=$("difficultyInfo"),assetInfo=$("assetInfo"),decoChoices=$("decoAssetChoices"),saveButton=$("saveCart");
 const ids=["title","subtitle","instruction","titleSize","titleY","ageProfile","difficulty","cols","rows","lineWidth","endpointMode","wallStyle","startAsset","goalAsset","startAssetScale","goalAssetScale","decoCount","decoScale","sideMargin","topMargin","bottomMargin","mazeScale","seed","solution"],fields=Object.fromEntries(ids.map(id=>[id,$(id)]));
 const DIFFICULTY_PRESETS=Object.freeze({
  "4-6":Object.freeze({easy:{cols:12,rows:16,lineWidth:7,mazeScale:92},medium:{cols:16,rows:20,lineWidth:6,mazeScale:96},hard:{cols:20,rows:26,lineWidth:5,mazeScale:100}}),
  "5-7":Object.freeze({easy:{cols:14,rows:18,lineWidth:7,mazeScale:94},medium:{cols:18,rows:24,lineWidth:6,mazeScale:98},hard:{cols:24,rows:30,lineWidth:5,mazeScale:100}}),
  "6-8":Object.freeze({easy:{cols:16,rows:22,lineWidth:6,mazeScale:95},medium:{cols:22,rows:28,lineWidth:5,mazeScale:99},hard:{cols:28,rows:36,lineWidth:4,mazeScale:100}})
 });
 const LABELS={easy:"Łatwy",medium:"Średni",hard:"Trudny",custom:"Własny"};
 let currentId=null,loadedEndpoints=null,legacyDecorations=null,legacyTheme="classic",renderTimer=null,applyingPreset=false,renderSeq=0;
 const clone=value=>value==null?value:typeof structuredClone==="function"?structuredClone(value):JSON.parse(JSON.stringify(value));
 const num=(id,fallback)=>{const value=Number(fields[id]?.value);return Number.isFinite(value)?value:fallback};
 const esc=value=>String(value??"").replace(/[&<>'\"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'\"':"&quot;"}[char]));
 function selectedDecoRefs(){return [...decoChoices.querySelectorAll('input[type="checkbox"]:checked')].map(input=>input.value)}
 function settings(){return{ageProfile:fields.ageProfile?.value||"4-6",difficulty:fields.difficulty?.value||"custom",cols:Math.max(6,Math.min(45,num("cols",18))),rows:Math.max(8,Math.min(58,num("rows",24))),lineWidth:Math.max(2,Math.min(12,num("lineWidth",5))),titleSize:Math.max(24,Math.min(72,num("titleSize",42))),titleY:Math.max(45,Math.min(150,num("titleY",82))),subtitle:fields.subtitle.value||"",instruction:fields.instruction.value||"",sideMargin:Math.max(35,Math.min(150,num("sideMargin",80))),topMargin:Math.max(120,Math.min(300,num("topMargin",170))),bottomMargin:Math.max(55,Math.min(180,num("bottomMargin",90))),mazeScale:Math.max(55,Math.min(100,num("mazeScale",100))),endpointMode:fields.endpointMode.value||"random",wallStyle:fields.wallStyle.value||"clean",showSolution:fields.solution.value==="yes",startAssetRef:fields.startAsset?.value||null,goalAssetRef:fields.goalAsset?.value||null,startAssetScale:Math.max(40,Math.min(180,num("startAssetScale",100))),goalAssetScale:Math.max(40,Math.min(180,num("goalAssetScale",100))),decoAssetRefs:selectedDecoRefs(),decoCount:Math.max(0,Math.min(10,num("decoCount",0))),decoScale:Math.max(30,Math.min(160,num("decoScale",80))),endpoints:clone(loadedEndpoints),showPageNumber:false,pageNumber:1,...(!fields.startAsset?.value&&!fields.goalAsset?.value&&!selectedDecoRefs().length&&legacyDecorations?{theme:legacyTheme,decorations:clone(legacyDecorations),assetCount:legacyDecorations.length}:{})}}
 function draft(){const s=settings(),seed=Number(fields.seed.value)||1,title=fields.title.value.trim()||"Find the Way!";return{module:"maze-studio",title,seed,settings:s,recipe:{module:"maze-studio",seed,title,settings:s,meta:{createdWith:"FENIX PC",desktopEditedAt:new Date().toISOString(),renderState:{showSolution:s.showSolution,endpoints:s.endpoints}}},solution:{available:true,imageData:null},source:{app:"fenix-desktop",version:"0.18.9",format:"native"}}}
 function updateDifficultyInfo(){if(!difficultyInfo)return;const age=fields.ageProfile?.value||"4-6",difficulty=fields.difficulty?.value||"custom";if(difficulty==="custom"){difficultyInfo.textContent=`Profil ${age} lat · Własny: ręczne parametry siatki są aktywne.`;return}const preset=DIFFICULTY_PRESETS[age]?.[difficulty];difficultyInfo.textContent=preset?`Profil ${age} lat · ${LABELS[difficulty]} · siatka ${preset.cols}×${preset.rows} · ściany ${preset.lineWidth}px · skala ${preset.mazeScale}%. Możesz potem skorygować parametry ręcznie.`:`Profil ${age} lat · ${LABELS[difficulty]||difficulty}.`}
 function assetLabel(asset){const mark=asset.validation?.status==="ok"?"✓":asset.validation?.status==="error"?"×":"!";return `${mark} ${asset.name}`}
 function setSelectOptions(element,assets,selected){const exists=assets.some(asset=>asset.id===selected);element.innerHTML=`<option value="">Bez assetu — znacznik ${element===fields.startAsset?"S":"M"}</option>`+assets.map(asset=>`<option value="${esc(asset.id)}">${esc(assetLabel(asset))}</option>`).join("");element.value=exists?selected:""}
 function refreshAssetControls(saved={}){const startSelected=saved.startAssetRef??fields.startAsset?.value??"",goalSelected=saved.goalAssetRef??fields.goalAsset?.value??"",decoSelected=new Set(saved.decoAssetRefs??selectedDecoRefs());const gameplay=FenixCore.findAssets({tag:"gameplay"}),deco=FenixCore.findAssets({tag:"deco"});setSelectOptions(fields.startAsset,gameplay,startSelected);setSelectOptions(fields.goalAsset,gameplay,goalSelected);decoChoices.innerHTML=deco.length?deco.map(asset=>`<label class="deco-choice"><input type="checkbox" value="${esc(asset.id)}" ${decoSelected.has(asset.id)?"checked":""}><span><strong>${esc(asset.name)}</strong><small>${asset.validation?.status==="ok"?"✓ B&W OK":"! sprawdź B&W"}</small></span></label>`).join(""):'<div class="asset-empty">Brak assetów oznaczonych jako Deco w aktywnym projekcie.</div>';decoChoices.querySelectorAll('input[type="checkbox"]').forEach(input=>input.addEventListener("change",()=>{legacyDecorations=null;scheduleDraw()}));if(assetInfo){const warnings=[...gameplay,...deco].filter(asset=>asset.validation?.status!=="ok").length;assetInfo.textContent=`Biblioteka projektu: Gameplay ${gameplay.length} · Deco ${deco.length}${warnings?` · ${warnings} assetów z uwagami walidacji`:" · wszystkie widoczne assety mają status OK"}. Ramka pozostaje poza aktywną logiką Maze i wróci później jako opcjonalna warstwa Deco.`}}
 async function draw(){const seq=++renderSeq;if(!window.FenixMaze){status.textContent="Błąd: wspólny renderer Maze nie został załadowany.";return}const page=draft(),s=settings();status.textContent="Odświeżam podgląd…";const assetImages=await FenixMaze.prepareAssets(page);if(seq!==renderSeq)return;const result=FenixMaze.render(page,{solution:s.showSolution,width:2550,height:3300,canvas,assetImages});if(seq!==renderSeq)return;loadedEndpoints=clone(result.endpoints);status.textContent=`Gotowy · ${s.ageProfile} lat · ${LABELS[s.difficulty]||s.difficulty} · ${s.cols}×${s.rows} · seed ${page.recipe.seed} · rozwiązanie ${s.showSolution?"tak":"nie"} · deco ${result.decorations?.length||0}`;updateDifficultyInfo()}
 function invalidate(kind){if(kind==="geometry"||kind==="seed")loadedEndpoints=null;if(kind!=="legacy")legacyDecorations=null;draw()}
 function scheduleDraw(kind="visual"){clearTimeout(renderTimer);renderTimer=setTimeout(()=>invalidate(kind),140)}
 function applyDifficultyPreset(){const age=fields.ageProfile?.value||"4-6",difficulty=fields.difficulty?.value||"easy";if(difficulty==="custom"){updateDifficultyInfo();draw();return}const preset=DIFFICULTY_PRESETS[age]?.[difficulty];if(!preset)return;applyingPreset=true;fields.cols.value=preset.cols;fields.rows.value=preset.rows;fields.lineWidth.value=preset.lineWidth;fields.mazeScale.value=preset.mazeScale;applyingPreset=false;updateDifficultyInfo();invalidate("geometry")}
 function markDifficultyCustom(){if(applyingPreset||!fields.difficulty)return;if(fields.difficulty.value!=="custom")fields.difficulty.value="custom";updateDifficultyInfo()}
 function mazePages(){return FenixCore.getCart().map(page=>FenixPageSchema.normalize(page)).filter(page=>page.module==="maze-studio")}
 function updateSaveLabel(){saveButton.textContent=currentId?"Zapisz zmiany w Stronach projektu":"Dodaj do Stron projektu"}
 function refill(preferredId=currentId){const pages=mazePages();select.innerHTML=pages.length?`<option value="">Nowa strona</option>`+pages.map(page=>`<option value="${page.id}">${esc(page.title||"Labirynt")}</option>`).join(""):"<option value=''>Nowa strona</option>";const requested=new URLSearchParams(location.search).get("id"),id=preferredId&&pages.some(page=>page.id===preferredId)?preferredId:requested&&pages.some(page=>page.id===requested)?requested:null;load(id)}
 function load(id){currentId=id||null;const page=currentId?FenixCore.getCart().find(item=>item.id===currentId):null;if(!page){loadedEndpoints=null;legacyDecorations=null;legacyTheme="classic";fields.ageProfile.value="4-6";fields.difficulty.value="easy";fields.startAssetScale.value="100";fields.goalAssetScale.value="100";fields.decoCount.value="0";fields.decoScale.value="80";refreshAssetControls({startAssetRef:null,goalAssetRef:null,decoAssetRefs:[]});select.value="";updateSaveLabel();applyDifficultyPreset();return}const normalized=FenixPageSchema.normalize(page),recipe=normalized.recipe,stored=recipe.settings||{},renderState=recipe.renderState||recipe.meta?.renderState||{};select.value=currentId;fields.title.value=normalized.title||"Find the Way!";const defaults={subtitle:"",instruction:"",titleSize:42,titleY:82,ageProfile:"4-6",difficulty:"custom",cols:18,rows:24,lineWidth:5,endpointMode:"random",wallStyle:"clean",sideMargin:80,topMargin:170,bottomMargin:90,mazeScale:100,startAssetScale:100,goalAssetScale:100,decoCount:0,decoScale:80};for(const key of Object.keys(defaults))if(fields[key])fields[key].value=stored[key]??defaults[key];fields.seed.value=recipe.seed??1;fields.solution.value=(stored.showSolution??renderState.showSolution)?"yes":"no";loadedEndpoints=clone(stored.endpoints||renderState.endpoints||null);legacyDecorations=Array.isArray(stored.decorations)?clone(stored.decorations):null;legacyTheme=stored.theme||"classic";refreshAssetControls(stored);updateDifficultyInfo();updateSaveLabel();draw()}
 function payload(){const page=draft();page.recipe.settings.endpoints=clone(loadedEndpoints);page.recipe.meta.renderState={showSolution:page.recipe.settings.showSolution,endpoints:clone(loadedEndpoints)};return FenixPageSchema.normalize(page)}
 function save(copy=false){const data=payload();if(!copy&&currentId){FenixCore.updatePage(currentId,data);status.textContent="Zmiany zapisane w Stronach projektu.";refill(currentId)}else{FenixCore.addPage(data);const newest=FenixCore.getCart().at(-1);currentId=newest?.id||null;status.textContent="Strona dodana do Stron projektu.";refill(currentId)}}
 ["title","subtitle","instruction","titleSize","titleY","wallStyle","solution","startAssetScale","goalAssetScale","decoCount","decoScale"].forEach(id=>fields[id]?.addEventListener("input",()=>scheduleDraw()));
 ["cols","rows","lineWidth","mazeScale"].forEach(id=>fields[id]?.addEventListener("input",()=>{markDifficultyCustom();scheduleDraw("geometry")}));
 ["endpointMode","sideMargin","topMargin","bottomMargin"].forEach(id=>fields[id]?.addEventListener("change",()=>invalidate("geometry")));
 ["startAsset","goalAsset"].forEach(id=>fields[id]?.addEventListener("change",()=>{legacyDecorations=null;draw()}));
 fields.ageProfile?.addEventListener("change",()=>{if(fields.difficulty.value!=="custom")applyDifficultyPreset();else{updateDifficultyInfo();draw()}});
 fields.difficulty?.addEventListener("change",applyDifficultyPreset);
 fields.seed?.addEventListener("change",()=>invalidate("seed"));
 select.onchange=()=>load(select.value||null);
 $("newVariant").onclick=()=>{fields.seed.value=String((Number(fields.seed.value)||1)+1);currentId=null;select.value="";updateSaveLabel();invalidate("seed")};
 saveButton.onclick=()=>save(false);$("saveCopy").onclick=()=>save(true);$("downloadPng").onclick=async()=>{await draw();FenixCore.downloadCanvas(canvas,`maze-${Number(fields.seed.value)||1}.png`)};
 window.addEventListener("fenix-state-change",event=>{if(event.detail?.cart||event.detail?.activeProject)refill(currentId);else if(event.detail?.assets){refreshAssetControls();draw()}});
 refill();
})();
