"use strict";

(()=>{
  const $=selector=>document.querySelector(selector),canvas=$("#page"),ctx=canvas.getContext("2d");
  const requestedId=new URLSearchParams(location.search).get("id");
  const state={assets:[],selected:new Set(),pages:[],index:0,editingId:requestedId||null};let refreshTimer=null;
  const val=(id,fallback="")=>$("#"+id)?.value??fallback;
  const checked=id=>Boolean($("#"+id)?.checked);
  const number=(id,fallback)=>Number(val(id,fallback))||fallback;
  const escapeHtml=value=>String(value??"").replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[ch]));

  function setStatus(text,error=false){const el=$("#status");el.textContent=text;el.dataset.type=error?"error":"ok"}
  function currentOptions(){return{title:val("title",FenixColoring.DEFAULTS.title),instructions:val("instructions",FenixColoring.DEFAULTS.instructions),showTitle:checked("showTitle"),showInstructions:checked("showInstructions"),titleSize:number("titleSize",112),instructionSize:number("instructionSize",46),titleY:number("titleY",230),assetScale:number("assetScale",82),assetY:number("assetY",56)}}
  function eligibleAssets(){const all=FenixCore.listAssets();return all.sort((a,b)=>{const ac=(a.tags||[]).includes("content")?0:1,bc=(b.tags||[]).includes("content")?0:1;return ac-bc||String(a.name).localeCompare(String(b.name),"pl")})}
  function renderAssets(){state.assets=eligibleAssets();const grid=$("#assetGrid"),empty=$("#assetEmpty");grid.innerHTML="";empty.hidden=state.assets.length>0;state.assets.forEach(asset=>{const selected=state.selected.has(asset.id),card=document.createElement("button");card.type="button";card.className=`asset-card${selected?" selected":""}`;card.setAttribute("aria-pressed",String(selected));card.innerHTML=`<span class="asset-check">${selected?"✓":""}</span><img src="${asset.dataUrl}" alt="${escapeHtml(asset.name)}"><strong>${escapeHtml(asset.name)}</strong><small>${(asset.tags||[]).includes("content")?"Treść":"Asset projektu"}</small>`;card.onclick=()=>{if(state.editingId){state.selected.clear();state.selected.add(asset.id)}else selected?state.selected.delete(asset.id):state.selected.add(asset.id);renderAssets();build()};grid.appendChild(card)});$("#selectionCount").textContent=state.editingId?`Edycja strony · wybrano: ${state.selected.size}`:`Wybrano: ${state.selected.size}`;$("#selectAll").disabled=!state.assets.length||Boolean(state.editingId);$("#selectAll").textContent=state.editingId?"Tryb edycji strony":state.assets.length&&state.assets.every(asset=>state.selected.has(asset.id))?"Odznacz wszystkie":"Zaznacz wszystkie"}
  async function makePage(asset,index,original=null){const o=currentOptions(),page=FenixPageSchema.normalize({id:original?.id,createdAt:original?.createdAt,module:"coloring-studio",title:o.title,recipe:{module:"coloring-studio",seed:null,title:o.title,settings:{...o,pageIndex:index},content:{assetRef:asset.id},meta:{...(original?.recipe?.meta||{}),createdWith:"FENIX PC",moduleVersion:2}},preview:{imageData:null},solution:{available:false,imageData:null},validation:{kdp:asset.validation||{status:"unknown",messages:[]}},source:{app:"fenix-desktop",version:"0.28.1",format:"native"}}),image=await FenixColoring.loadImage(asset.dataUrl);return{page,asset,image,canvas:FenixColoring.render(page,{width:850,height:1100,assetImage:image})}}
  async function build(){clearTimeout(refreshTimer);const token=Date.now();build.token=token;try{const selected=state.assets.filter(asset=>state.selected.has(asset.id));if(!selected.length){state.pages=[];show();return setStatus(state.editingId?"Ta zapisana strona nie ma dostępnego assetu w projekcie.":"Wybierz co najmniej jeden asset projektu.",true)}setStatus(`Przygotowuję ${selected.length} ${selected.length===1?"stronę":"stron"}…`);const pages=[],original=state.editingId?FenixCore.getCart().find(page=>page.id===state.editingId):null;for(let index=0;index<selected.length;index++)pages.push(await makePage(selected[index],index,original&&index===0?FenixPageSchema.normalize(original):null));if(build.token!==token)return;state.pages=pages;state.index=Math.min(state.index,Math.max(0,pages.length-1));show();setStatus(state.editingId?"Podgląd zapisanej strony został odtworzony z jej ustawień.":`Gotowe: ${pages.length} ${pages.length===1?"strona kolorowanki":"stron kolorowanek"}.`)}catch(error){console.error(error);setStatus(`Błąd: ${error.message}`,true)}}
  function scheduleBuild(){clearTimeout(refreshTimer);refreshTimer=setTimeout(build,140)}
  function show(){const current=state.pages[state.index];canvas.width=850;canvas.height=1100;ctx.fillStyle="#fff";ctx.fillRect(0,0,850,1100);if(current)ctx.drawImage(current.canvas,0,0);$("#pageCounter").textContent=state.pages.length?`${state.index+1} / ${state.pages.length}`:"0 / 0";$("#prev").disabled=state.index<=0;$("#next").disabled=state.index>=state.pages.length-1}
  function saveToProject(){if(!state.pages.length)return setStatus("Najpierw wybierz assety i wygeneruj strony.",true);if(state.editingId){const item=state.pages[0];FenixCore.updatePage(state.editingId,item.page);setStatus(`Zapisano zmiany strony Coloring Studio w projekcie „${FenixCore.getActiveProject().name}”.`);return}state.pages.forEach(item=>FenixCore.addPage(item.page));setStatus(`Dodano ${state.pages.length} stron Coloring Studio do projektu „${FenixCore.getActiveProject().name}”.`)}
  async function exportPng(){const current=state.pages[state.index];if(!current)return;const high=FenixColoring.render(current.page,{width:2550,height:3300,assetImage:current.image}),project=FenixCore.getActiveProject(),fitted=FenixProduction.fitCanvas(high,project.format,project.bleed);FenixCore.downloadCanvas(fitted.canvas,`coloring-${String(current.asset.name).replace(/[^a-z0-9_-]+/gi,"-")}.png`)}
  function projectInfo(){const project=FenixCore.getActiveProject(),profile=FenixProduction.profile(project.format,project.bleed);$("#projectInfo").textContent=`Aktywny projekt: ${project.name} · ${project.format==="a4"?"A4":project.format} · ${profile.width}×${profile.height}px${state.editingId?" · TRYB EDYCJI":""}`}
  function loadSavedPage(){if(!state.editingId)return false;const raw=FenixCore.getCart().find(page=>page.id===state.editingId);if(!raw||FenixPageSchema.moduleOf(raw)!=="coloring-studio"){state.editingId=null;return false}const page=FenixPageSchema.normalize(raw),o=FenixColoring.optionsFromPage(page);$("#title").value=o.title;$("#instructions").value=o.instructions;$("#showTitle").checked=o.showTitle;$("#showInstructions").checked=o.showInstructions;$("#titleSize").value=o.titleSize;$("#instructionSize").value=o.instructionSize;$("#titleY").value=o.titleY;$("#assetScale").value=o.assetScale;$("#assetY").value=o.assetY;state.selected.clear();if(o.assetRef&&FenixCore.getAsset(o.assetRef))state.selected.add(o.assetRef);$("#cart").textContent="Zapisz zmiany w projekcie";return true}

  $("#generate").onclick=build;$("#cart").onclick=saveToProject;$("#png").onclick=exportPng;$("#prev").onclick=()=>{if(state.index>0){state.index--;show()}};$("#next").onclick=()=>{if(state.index<state.pages.length-1){state.index++;show()}};
  $("#selectAll").onclick=()=>{if(state.editingId)return;const allSelected=state.assets.length&&state.assets.every(asset=>state.selected.has(asset.id));state.assets.forEach(asset=>allSelected?state.selected.delete(asset.id):state.selected.add(asset.id));renderAssets();build()};
  ["title","instructions","titleSize","instructionSize","titleY","assetScale","assetY"].forEach(id=>$("#"+id)?.addEventListener("input",scheduleBuild));["showTitle","showInstructions"].forEach(id=>$("#"+id)?.addEventListener("change",scheduleBuild));
  window.addEventListener("fenix-state-change",event=>{if(event.detail?.assets||event.detail?.activeProject){if(!state.editingId)state.selected.clear();projectInfo();renderAssets();show()}});
  projectInfo();renderAssets();loadSavedPage();renderAssets();show();if(state.editingId)build();
})();
