"use strict";

(()=>{
  const $=selector=>document.querySelector(selector),canvas=$("#page"),ctx=canvas.getContext("2d");
  const state={assets:[],selected:new Set(),pages:[],index:0,editingId:null};let refreshTimer=null;
  const val=(id,fallback="")=>$("#"+id)?.value??fallback;
  const checked=id=>Boolean($("#"+id)?.checked);
  const number=(id,fallback)=>Number(val(id,fallback))||fallback;
  const escapeHtml=value=>String(value??"").replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[ch]));

  function setStatus(text,error=false){const el=$("#status");el.textContent=text;el.dataset.type=error?"error":"ok"}
  function currentOptions(){return{title:val("title",FenixColoring.DEFAULTS.title),instructions:val("instructions",FenixColoring.DEFAULTS.instructions),showTitle:checked("showTitle"),showInstructions:checked("showInstructions"),titleSize:number("titleSize",112),instructionSize:number("instructionSize",46),titleY:number("titleY",230),assetScale:number("assetScale",82),assetY:number("assetY",56)}}
  function eligibleAssets(){const all=FenixCore.listAssets();return all.sort((a,b)=>{const ac=(a.tags||[]).includes("content")?0:1,bc=(b.tags||[]).includes("content")?0:1;return ac-bc||String(a.name).localeCompare(String(b.name),"pl")})}
  function renderAssets(){state.assets=eligibleAssets();const grid=$("#assetGrid"),empty=$("#assetEmpty");grid.innerHTML="";empty.hidden=state.assets.length>0;state.assets.forEach(asset=>{const selected=state.selected.has(asset.id),card=document.createElement("button");card.type="button";card.className=`asset-card${selected?" selected":""}`;card.setAttribute("aria-pressed",String(selected));card.innerHTML=`<span class="asset-check">${selected?"✓":""}</span><img src="${asset.dataUrl}" alt="${escapeHtml(asset.name)}"><strong>${escapeHtml(asset.name)}</strong><small>${(asset.tags||[]).includes("content")?"Treść":"Asset projektu"}</small>`;card.onclick=()=>{if(state.editingId){state.selected.clear();state.selected.add(asset.id)}else if(selected)state.selected.delete(asset.id);else state.selected.add(asset.id);renderAssets();build()};grid.appendChild(card)});$("#selectionCount").textContent=state.editingId?`Edytowana strona · asset: ${state.selected.size?"1":"0"}`:`Wybrano: ${state.selected.size}`;$("#selectAll").disabled=!state.assets.length||Boolean(state.editingId);$("#selectAll").textContent=state.editingId?"Tryb edycji jednej strony":state.assets.length&&state.assets.every(asset=>state.selected.has(asset.id))?"Odznacz wszystkie":"Zaznacz wszystkie"}
  async function makePage(asset,index){const o=currentOptions(),page=FenixPageSchema.normalize({module:"coloring-studio",title:o.title,recipe:{module:"coloring-studio",seed:null,title:o.title,settings:{...o,pageIndex:index},content:{assetRef:asset.id},meta:{createdWith:"FENIX PC",moduleVersion:1}},preview:{imageData:null},solution:{available:false,imageData:null},validation:{kdp:asset.validation||{status:"unknown",messages:[]}},source:{app:"fenix-desktop",version:"0.28.0",format:"native"}}),image=await FenixColoring.loadImage(asset.dataUrl);return{page,asset,image,canvas:FenixColoring.render(page,{width:850,height:1100,assetImage:image})}}
  async function build(){clearTimeout(refreshTimer);const token=Date.now();build.token=token;try{const selected=state.assets.filter(asset=>state.selected.has(asset.id));if(!selected.length){state.pages=[];show();return setStatus("Wybierz co najmniej jeden asset projektu.",true)}setStatus(`Przygotowuję ${selected.length} stron…`);const pages=[];for(let index=0;index<selected.length;index++)pages.push(await makePage(selected[index],index));if(build.token!==token)return;state.pages=pages;state.index=Math.min(state.index,Math.max(0,pages.length-1));show();setStatus(state.editingId?"Podgląd zapisanej strony został odtworzony z jej ustawień.":`Gotowe: ${pages.length} ${pages.length===1?"strona kolorowanki":"stron kolorowanek"}.`)}catch(error){console.error(error);setStatus(`Błąd: ${error.message}`,true)}}
  function scheduleBuild(){clearTimeout(refreshTimer);refreshTimer=setTimeout(build,140)}
  function show(){const current=state.pages[state.index];canvas.width=850;canvas.height=1100;ctx.fillStyle="#fff";ctx.fillRect(0,0,850,1100);if(current)ctx.drawImage(current.canvas,0,0);$("#pageCounter").textContent=state.pages.length?`${state.index+1} / ${state.pages.length}`:"0 / 0";$("#prev").disabled=state.index<=0;$("#next").disabled=state.index>=state.pages.length-1}
  function editingPage(){return state.editingId?FenixCore.getCart().find(page=>page.id===state.editingId&&FenixPageSchema.moduleOf(page)==="coloring-studio"):null}
  function hydrateEditingPage(){const requested=new URLSearchParams(location.search).get("id"),page=requested?FenixCore.getCart().find(item=>item.id===requested&&FenixPageSchema.moduleOf(item)==="coloring-studio"):null;if(!page)return false;const normalized=FenixPageSchema.normalize(page),settings=normalized.recipe?.settings||{},assetRef=normalized.recipe?.content?.assetRef||normalized.content?.assetRef||null;state.editingId=normalized.id;state.selected.clear();if(assetRef&&state.assets.some(asset=>asset.id===assetRef))state.selected.add(assetRef);const values={title:normalized.title||settings.title||FenixColoring.DEFAULTS.title,instructions:settings.instructions??FenixColoring.DEFAULTS.instructions,titleSize:settings.titleSize??112,instructionSize:settings.instructionSize??46,titleY:settings.titleY??230,assetScale:settings.assetScale??82,assetY:settings.assetY??56};Object.entries(values).forEach(([id,value])=>{const input=$("#"+id);if(input)input.value=value});const showTitle=$("#showTitle"),showInstructions=$("#showInstructions");if(showTitle)showTitle.checked=settings.showTitle!==false;if(showInstructions)showInstructions.checked=settings.showInstructions!==false;$("#cart").textContent="Zapisz zmiany w Stronach projektu";renderAssets();build();return true}
  function addToProject(){if(!state.pages.length)return setStatus("Najpierw wybierz assety i wygeneruj strony.",true);if(state.editingId){const original=editingPage();if(!original)return setStatus("Nie znaleziono edytowanej strony w aktywnym projekcie.",true);if(state.pages.length!==1)return setStatus("W trybie edycji wybierz dokładnie jeden asset.",true);const replacement={...state.pages[0].page,id:original.id,createdAt:original.createdAt,updatedAt:new Date().toISOString()};FenixCore.updatePage(original.id,replacement);setStatus("Zmiany zapisane w istniejącej stronie Coloring Studio.");return}state.pages.forEach(item=>FenixCore.addPage(item.page));setStatus(`Dodano ${state.pages.length} stron Coloring Studio do projektu „${FenixCore.getActiveProject().name}”.`)}
  async function exportPng(){const current=state.pages[state.index];if(!current)return;const high=FenixColoring.render(current.page,{width:2550,height:3300,assetImage:current.image}),project=FenixCore.getActiveProject(),fitted=FenixProduction.fitCanvas(high,project.format,project.bleed);FenixCore.downloadCanvas(fitted.canvas,`coloring-${String(current.asset.name).replace(/[^a-z0-9_-]+/gi,"-")}.png`)}
  function projectInfo(){const project=FenixCore.getActiveProject(),profile=FenixProduction.profile(project.format,project.bleed);$("#projectInfo").textContent=`Aktywny projekt: ${project.name} · ${project.format==="a4"?"A4":project.format} · ${profile.width}×${profile.height}px`}

  $("#generate").onclick=build;$("#cart").onclick=addToProject;$("#png").onclick=exportPng;$("#prev").onclick=()=>{if(state.index>0){state.index--;show()}};$("#next").onclick=()=>{if(state.index<state.pages.length-1){state.index++;show()}};
  $("#selectAll").onclick=()=>{if(state.editingId)return;const allSelected=state.assets.length&&state.assets.every(asset=>state.selected.has(asset.id));state.assets.forEach(asset=>allSelected?state.selected.delete(asset.id):state.selected.add(asset.id));renderAssets();build()};
  ["title","instructions","titleSize","instructionSize","titleY","assetScale","assetY"].forEach(id=>$("#"+id)?.addEventListener("input",scheduleBuild));["showTitle","showInstructions"].forEach(id=>$("#"+id)?.addEventListener("change",scheduleBuild));
  window.addEventListener("fenix-state-change",event=>{if(event.detail?.assets||event.detail?.activeProject){state.selected.clear();state.editingId=null;$("#cart").textContent="Dodaj wybrane strony do projektu";projectInfo();renderAssets();show()}});
  projectInfo();renderAssets();if(!hydrateEditingPage())show();
})();
