"use strict";
(()=>{
 const $=s=>document.querySelector(s),list=$("#pageList"),empty=$("#emptyState"),printBook=$("#printBook"),validationSummary=$("#validationSummary");
 let pages=[],dragIndex=null,renderToken=0;
 const normalize=page=>FenixPageSchema.normalize(page),moduleOf=page=>FenixPageSchema.moduleOf(page),isMaze=page=>moduleOf(page)==="maze-studio",isComplete=page=>moduleOf(page)==="complete-picture",isStandard=page=>FenixStandardRenderers.modules.includes(moduleOf(page)),hasSolution=page=>FenixPageSchema.hasSolution(page);
 const loadImage=src=>new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(new Error("Nie udało się odczytać obrazu strony/assetu."));img.src=src});
 function currentProject(){return FenixCore.getActiveProject()}
 function targetFormat(){return $("#format")?.value||currentProject().format}
 function targetProfile(){const project=currentProject();return FenixProduction.profile(targetFormat(),project.bleed)}
 function standardOptions(page){const p=normalize(page),s=p.recipe.settings||{};return{type:s.type||"",title:p.title||p.recipe.title,instructions:s.instructions||"Complete the activity.",difficulty:s.difficulty||"medium",age:s.age||"5-7",language:s.language||"en",range:Number(s.range)||20,extra:s.extra||"A"}}
 async function storedImageCanvas(data,quality){if(!data)return null;const img=await loadImage(data);if(quality==="preview"){const c=document.createElement("canvas");c.width=850;c.height=1100;const ctx=c.getContext("2d");ctx.fillStyle="#fff";ctx.fillRect(0,0,850,1100);const scale=Math.min(850/img.naturalWidth,1100/img.naturalHeight),w=img.naturalWidth*scale,h=img.naturalHeight*scale;ctx.drawImage(img,(850-w)/2,(1100-h)/2,w,h);return c}const p=targetProfile(),c=document.createElement("canvas");c.width=p.width;c.height=p.height;const ctx=c.getContext("2d");ctx.fillStyle="#fff";ctx.fillRect(0,0,c.width,c.height);const scale=Math.min(c.width/img.naturalWidth,c.height/img.naturalHeight),w=img.naturalWidth*scale,h=img.naturalHeight*scale;ctx.drawImage(img,(c.width-w)/2,(c.height-h)/2,w,h);return c}
 async function completeCanvas(page,solution,quality){const p=normalize(page),options=FenixCompletePicture.optionsFromPage(p),assetRef=p.recipe.content?.assetRef;let customImage=null;if(options.assetSource==="upload"){const asset=assetRef?FenixCore.getAsset(assetRef):null;if(!asset?.dataUrl)throw new Error(`Brak assetu „${p.title}” w bibliotece projektu.`);customImage=await loadImage(asset.dataUrl)}const raw=FenixCompletePicture.render(options,p.recipe.seed,Number(p.recipe.settings?.pageIndex)||0,{solution,scale:quality==="print"?3:1,customImage});if(quality==="preview")return raw;const project=currentProject();return FenixProduction.fitCanvas(raw,targetFormat(),project.bleed).canvas}
 async function renderCanvas(page,solution=false,quality="preview"){
   const p=normalize(page),module=p.module;
   if(page?._blank||module==="blank-page"){const profile=quality==="print"?targetProfile():{width:850,height:1100},c=document.createElement("canvas");c.width=profile.width;c.height=profile.height;const ctx=c.getContext("2d");ctx.fillStyle="#fff";ctx.fillRect(0,0,c.width,c.height);return c}
   if(isMaze(p)){const assetImages=await FenixMaze.prepareAssets(p);if(quality==="preview")return FenixMaze.render(p,{solution,width:850,height:1100,assetImages}).canvas;const raw=FenixMaze.render(p,{solution,width:2550,height:3300,assetImages}).canvas,project=currentProject();return FenixProduction.fitCanvas(raw,targetFormat(),project.bleed).canvas}
   if(isStandard(p)){const rendered=FenixStandardRenderers.render(module,standardOptions(p),p.recipe.seed,Number(p.recipe.settings?.pageIndex)||0,quality==="print"?3:1),raw=solution?rendered.solutionCanvas:rendered.pageCanvas;if(!raw)return null;if(quality==="preview")return raw;const project=currentProject();return FenixProduction.fitCanvas(raw,targetFormat(),project.bleed).canvas}
   if(isComplete(p))return completeCanvas(p,solution,quality);
   return storedImageCanvas(solution?p.solution?.imageData:p.preview?.imageData,quality)
 }
 async function imageUrl(page,solution=false,quality="preview"){const canvas=await renderCanvas(page,solution,quality);return canvas?canvas.toDataURL("image/png"):null}
 function validateProject(){if(!validationSummary)return;const project=currentProject(),result=FenixProjectValidator.validate({...project,format:targetFormat(),pages});const icon=status=>status==="ok"?"✓":status==="warning"?"!":"×";validationSummary.innerHTML=`<strong>Gotowość: ${result.score}%</strong><br>${result.checks.map(check=>`${icon(check.status)} ${check.label}: ${check.message}`).join("<br>")}`;validationSummary.dataset.status=result.status}
 function loadCart(){pages=FenixCore.getCart().map((page,index)=>({...normalize(page),_builderId:page.id||`page-${index}`}));const project=currentProject();$("#bookTitle").value=project.name;$("#format").value=String(project.format).toLowerCase()==="a4"?"a4":project.format;render()}
 function render(){const token=++renderToken;list.innerHTML="";empty.hidden=pages.length>0;const solutions=pages.filter(hasSolution).length;$("#pageCount").textContent=`${pages.length} stron`;$("#cartSummary").textContent=`W składzie: ${pages.length} stron · rozwiązania: ${solutions}.`;pages.forEach((page,index)=>{const card=document.createElement("article");card.className="page-card";card.draggable=true;const module=page.module||"strona";card.innerHTML=`<span class="page-index">${index+1}</span><div class="page-thumb"><div class="blank-thumb">…</div></div><div class="page-meta"><strong>${page.title||module||"Strona"}</strong><small>${page._blank?"Pusta strona":hasSolution(page)?`${module} · rozwiązanie dostępne`:module}</small><div class="card-actions"><button data-up="${index}">↑</button><button data-down="${index}">↓</button><button class="danger" data-remove="${index}">Usuń</button></div></div>`;card.ondragstart=()=>{dragIndex=index;card.classList.add("dragging")};card.ondragend=()=>card.classList.remove("dragging");card.ondragover=event=>event.preventDefault();card.ondrop=event=>{event.preventDefault();if(dragIndex===null||dragIndex===index)return;const[moved]=pages.splice(dragIndex,1);pages.splice(index,0,moved);dragIndex=null;render()};list.appendChild(card);imageUrl(page,false,"preview").then(src=>{if(token!==renderToken||!card.isConnected)return;card.querySelector(".page-thumb").innerHTML=src?`<img src="${src}" alt="Podgląd strony">`:`<div class="blank-thumb">${page._blank?"□":"?"}</div>`}).catch(error=>{console.error(error);if(card.isConnected)card.querySelector(".page-thumb").innerHTML=`<div class="blank-thumb" title="${String(error.message).replace(/"/g,'&quot;')}">!</div>`})});document.querySelectorAll("[data-remove]").forEach(button=>button.onclick=()=>{pages.splice(Number(button.dataset.remove),1);render()});document.querySelectorAll("[data-up]").forEach(button=>button.onclick=()=>move(Number(button.dataset.up),-1));document.querySelectorAll("[data-down]").forEach(button=>button.onclick=()=>move(Number(button.dataset.down),1));validateProject()}
 function move(index,direction){const target=index+direction;if(target<0||target>=pages.length)return;[pages[index],pages[target]]=[pages[target],pages[index]];render()}
 function addPrintPage(imageData,index){const element=document.createElement("article");element.className="print-page";if(imageData){const image=document.createElement("img");image.src=imageData;element.appendChild(image)}if($("#pageNumbers").value==="yes"){const number=document.createElement("div");number.className="page-number-print";number.textContent=index;element.appendChild(number)}printBook.appendChild(element)}
 async function buildPrintBook(){const project=currentProject();printBook.innerHTML="";printBook.dataset.format=targetFormat();printBook.dataset.bleed=project.bleed==="bleed"?"bleed":"no-bleed";let number=1;for(const page of pages)addPrintPage(await imageUrl(page,false,"print"),number++);if($("#includeSolutions").checked){const solved=pages.filter(hasSolution),per=Number($("#solutionLayout").value)||1;for(let index=0;index<solved.length;index+=per){const sheet=document.createElement("article");sheet.className="print-page";const title=document.createElement("div");title.className="solutions-title";title.textContent="Solutions";sheet.appendChild(title);const grid=document.createElement("div");grid.className=`solutions-grid layout-${per} with-title`;for(let offset=0;offset<solved.slice(index,index+per).length;offset++){const item=solved[index+offset],image=await imageUrl(item,true,"print");if(!image)continue;const box=document.createElement("div");box.className="solution-box";box.innerHTML=`<h3>Solution ${index+offset+1}</h3><img src="${image}" alt="Rozwiązanie">`;grid.appendChild(box)}sheet.appendChild(grid);if($("#pageNumbers").value==="yes"){const n=document.createElement("div");n.className="page-number-print";n.textContent=number++;sheet.appendChild(n)}printBook.appendChild(sheet)}}return printBook.children.length}
 function setBusy(busy,text="Przygotowuję skład…"){[$("#previewBook"),$("#exportPdf")].forEach(button=>button.disabled=busy);if(busy)$("#cartSummary").textContent=text;else $("#cartSummary").textContent=`W składzie: ${pages.length} stron · rozwiązania: ${pages.filter(hasSolution).length}.`}
 $("#reloadCart").onclick=loadCart;$("#addBlank").onclick=()=>{const stamp=Date.now();pages.push({_builderId:`blank-${stamp}`,_blank:true,id:`blank-${stamp}`,schemaVersion:3,title:"Pusta strona",module:"blank-page",recipe:{module:"blank-page",seed:null,title:"Pusta strona",settings:{},content:{},meta:{},renderState:{}},preview:{imageData:null},solution:{available:false,imageData:null},validation:{kdp:{status:"ok",messages:[]}},production:targetProfile(),source:{app:"book-builder",version:"0.17.0",format:"native"}});render()};
 $("#previewBook").onclick=async()=>{if(!pages.length)return alert("Projekt nie zawiera jeszcze stron.");setBusy(true);try{const count=await buildPrintBook();alert(`Podgląd przygotowany: ${count} stron.`)}catch(error){console.error(error);alert(`Nie udało się przygotować podglądu: ${error.message}`)}finally{setBusy(false)}};
 $("#exportPdf").onclick=async()=>{if(!pages.length)return alert("Projekt nie zawiera jeszcze stron.");setBusy(true,"Renderuję strony 300 DPI…");try{await buildPrintBook();setTimeout(()=>window.print(),250)}catch(error){console.error(error);alert(`Nie udało się przygotować PDF: ${error.message}`)}finally{setBusy(false)}};
 ["format","pageNumbers","includeSolutions","solutionLayout"].forEach(id=>$("#"+id)?.addEventListener("change",()=>{if(id==="format")render();else validateProject()}));loadCart();
})();
