"use strict";
(()=>{
 const $=s=>document.querySelector(s),list=$("#pageList"),empty=$("#emptyState"),printBook=$("#printBook"),validationSummary=$("#validationSummary");
 let pages=[],dragIndex=null,renderToken=0;
 const normalize=page=>FenixPageSchema.normalize(page),moduleOf=page=>FenixPageSchema.moduleOf(page),hasSolution=page=>FenixPageSchema.hasSolution(page);
 const MODULE_NAMES={"intro-studio":"Intro","maze-studio":"Maze","word-search-studio":"Word Search","coloring-studio":"Coloring","tracing-studio":"Tracing","matching-studio":"Matching","alphabet-studio":"Alphabet","math-studio":"Math","dot-to-dot-studio":"Dot to Dot","hidden-objects-studio":"Hidden Objects","logic-studio":"Logic","complete-picture":"Complete the Picture","congratulations-studio":"Congratulations","qr-studio":"QR","certificate-studio":"Certificate","blank-page":"Puste strony"};
 const EXACT_MODULES=new Set(Object.keys(MODULE_NAMES).filter(x=>x!=="blank-page"));
 const loadImage=src=>new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(new Error("Nie udało się odczytać obrazu strony/assetu."));img.src=src});
 function currentProject(){return FenixCore.getActiveProject()}
 function targetFormat(){return $("#format")?.value||currentProject().format}
 function targetProfile(){const project=currentProject();return FenixProduction.profile(targetFormat(),project.bleed)}
 async function storedImageCanvas(data,quality){if(!data)return null;const img=await loadImage(data);if(quality==="preview"){const c=document.createElement("canvas");c.width=850;c.height=1100;const ctx=c.getContext("2d");ctx.fillStyle="#fff";ctx.fillRect(0,0,850,1100);const scale=Math.min(850/img.naturalWidth,1100/img.naturalHeight),w=img.naturalWidth*scale,h=img.naturalHeight*scale;ctx.drawImage(img,(850-w)/2,(1100-h)/2,w,h);return c}const p=targetProfile(),c=document.createElement("canvas");c.width=p.width;c.height=p.height;const ctx=c.getContext("2d");ctx.fillStyle="#fff";ctx.fillRect(0,0,c.width,c.height);const scale=Math.min(c.width/img.naturalWidth,c.height/img.naturalHeight),w=img.naturalWidth*scale,h=img.naturalHeight*scale;ctx.drawImage(img,(c.width-w)/2,(c.height-h)/2,w,h);return c}
 async function completeCanvas(page,solution,quality){if(!window.FenixCompletePicture)throw new Error("Brak silnika Complete Picture.");const p=normalize(page),options=FenixCompletePicture.optionsFromPage(p),assetRef=p.recipe.content?.assetRef;let customImage=null;if(options.assetSource==="upload"){const asset=assetRef?FenixCore.getAsset(assetRef):null;if(!asset?.dataUrl)throw new Error(`Brak assetu „${p.title}” w bibliotece projektu.`);customImage=await loadImage(asset.dataUrl)}const raw=FenixCompletePicture.render(options,p.recipe.seed,Number(p.recipe.settings?.pageIndex)||0,{solution,scale:quality==="print"?3:1,customImage});if(!raw)throw new Error("Complete Picture zwrócił pusty canvas.");if(quality==="preview")return raw;const project=currentProject();return FenixProduction.fitCanvas(raw,targetFormat(),project.bleed).canvas}
 async function tracingCanvas(page,quality){if(!window.FenixTracingCore)throw new Error("Brak silnika Tracing.");const p=normalize(page),assetRef=p.recipe.content?.assetRef||p.recipe.settings?.assetRef,asset=assetRef?FenixCore.getAsset(assetRef):null;if(!asset?.dataUrl)throw new Error(`Brak assetu Tracing dla strony „${p.title}”.`);const raw=await FenixTracingCore.render(asset,p.recipe.settings||{});if(!raw)throw new Error("Tracing zwrócił pusty canvas.");if(quality==="preview")return raw;const project=currentProject();return FenixProduction.fitCanvas(raw,targetFormat(),project.bleed).canvas}
 async function logicCanvas(page,solution,quality){if(!window.FenixLogicFrozenRenderer)throw new Error("Brak silnika Logic v5.");const raw=await FenixLogicFrozenRenderer.render(page,solution);if(!raw)throw new Error("Logic zwrócił pusty canvas.");if(quality==="preview")return raw;const project=currentProject();return FenixProduction.fitCanvas(raw,targetFormat(),project.bleed).canvas}
 async function mazeCanvas(p,solution,quality,renderOptions){if(!window.FenixMaze)throw new Error("Brak silnika Maze.");const assetImages=await FenixMaze.prepareAssets(p);if(quality==="preview"){const result=FenixMaze.render(p,{solution,...renderOptions,width:850,height:1100,assetImages});if(!result?.canvas)throw new Error("Maze zwrócił pusty canvas.");return result.canvas}const result=FenixMaze.render(p,{solution,...renderOptions,width:2550,height:3300,assetImages});if(!result?.canvas)throw new Error("Maze zwrócił pusty canvas.");const project=currentProject();return FenixProduction.fitCanvas(result.canvas,targetFormat(),project.bleed).canvas}
 async function wordSearchCanvas(p,solution,quality,renderOptions){if(!window.FenixWordSearch)throw new Error("Brak silnika Word Search.");const assetImages=await FenixWordSearch.prepareAssets(p),result=FenixWordSearch.render(p,{solution,...renderOptions,width:quality==="print"?2550:850,height:quality==="print"?3300:1100,assetImages}),raw=result?.canvas;if(!raw)throw new Error("Word Search zwrócił pusty canvas.");if(quality==="preview")return raw;const project=currentProject();return FenixProduction.fitCanvas(raw,targetFormat(),project.bleed).canvas}
 async function coloringCanvas(p,quality){if(!window.FenixColoring)throw new Error("Brak silnika Coloring.");const prepared=await FenixColoring.prepareAsset(p);if(!prepared?.image)throw new Error(`Nie znaleziono przypisanego assetu Coloring dla „${p.title}”.`);const raw=FenixColoring.render(p,{width:quality==="print"?2550:850,height:quality==="print"?3300:1100,assetImage:prepared.image});if(!raw)throw new Error("Coloring zwrócił pusty canvas.");if(quality==="preview")return raw;const project=currentProject();return FenixProduction.fitCanvas(raw,targetFormat(),project.bleed).canvas}
 async function introCanvas(p,quality){if(!window.FenixIntroRenderer)throw new Error("Brak silnika Intro.");const project=currentProject(),prepared=FenixIntroRenderer.prepare(p,{...project,pages}),raw=FenixIntroRenderer.render(prepared,{width:quality==="print"?2550:850,height:quality==="print"?3300:1100});if(!raw)throw new Error("Intro zwrócił pusty canvas.");if(quality==="preview")return raw;return FenixProduction.fitCanvas(raw,targetFormat(),project.bleed).canvas}
 async function endingCanvas(p,quality){if(!window.FenixEndingRenderers?.modules.includes(p.module))throw new Error(`Brak renderera końcowego: ${p.module}.`);let qrAssetImage=null,creatorMarkImage=null;if(p.module==="qr-studio"){const assetRef=p.recipe.content?.assetRef||p.recipe.settings?.qrAssetRef,asset=assetRef?FenixCore.getAsset(assetRef):null;if(!asset?.dataUrl)throw new Error("Strona QR nie ma przypisanego assetu kodu QR.");qrAssetImage=await loadImage(asset.dataUrl)}if(p.module==="certificate-studio"){const assetRef=p.recipe.content?.creatorMarkAssetRef||p.recipe.settings?.creatorMarkAssetRef||p.recipe.content?.signatureAssetRef||p.recipe.settings?.signatureAssetRef,asset=assetRef?FenixCore.getAsset(assetRef):null;if(asset?.dataUrl)creatorMarkImage=await loadImage(asset.dataUrl)}const raw=FenixEndingRenderers.render(p,{width:quality==="print"?2550:850,height:quality==="print"?3300:1100,qrAssetImage,creatorMarkImage});if(!raw)throw new Error(`${MODULE_NAMES[p.module]||p.module} zwrócił pusty canvas.`);if(quality==="preview")return raw;const project=currentProject();return FenixProduction.fitCanvas(raw,targetFormat(),project.bleed).canvas}
 async function productionCanvas(p,solution,quality){if(!window.FenixBookProductionRenderers?.supports(p.module))throw new Error(`Brak dokładnego renderera produkcyjnego dla ${p.module}.`);const raw=await FenixBookProductionRenderers.render(p,{solution,quality});if(!raw){if(solution&&!p.solution?.available)return null;throw new Error(`Renderer ${p.module} zwrócił pustą stronę.`)}if(quality==="preview")return raw;const project=currentProject();return FenixProduction.fitCanvas(raw,targetFormat(),project.bleed).canvas}
 async function renderCanvas(page,solution=false,quality="preview",renderOptions={}){
   const p=normalize(page),module=p.module;
   if(page?._blank||module==="blank-page"){const profile=quality==="print"?targetProfile():{width:850,height:1100},c=document.createElement("canvas");c.width=profile.width;c.height=profile.height;const ctx=c.getContext("2d");ctx.fillStyle="#fff";ctx.fillRect(0,0,c.width,c.height);return c}
   const savedSnapshot=solution?p.solution?.imageData:p.preview?.imageData;
   if(savedSnapshot)return storedImageCanvas(savedSnapshot,quality);
   if(module==="logic-studio")return logicCanvas(p,solution,quality);
   if(module==="tracing-studio")return tracingCanvas(p,quality);
   if(module==="complete-picture")return completeCanvas(p,solution,quality);
   if(module==="maze-studio")return mazeCanvas(p,solution,quality,renderOptions);
   if(module==="word-search-studio")return wordSearchCanvas(p,solution,quality,renderOptions);
   if(module==="coloring-studio")return coloringCanvas(p,quality);
   if(["matching-studio","alphabet-studio","math-studio","dot-to-dot-studio","hidden-objects-studio"].includes(module))return productionCanvas(p,solution,quality);
   if(module==="intro-studio")return introCanvas(p,quality);
   if(["congratulations-studio","qr-studio","certificate-studio"].includes(module))return endingCanvas(p,quality);
   if(EXACT_MODULES.has(module))throw new Error(`Moduł ${module} nie ma aktywnej dokładnej ścieżki renderowania.`);
   throw new Error(`Nieobsługiwany moduł strony: ${module}.`)
 }
 async function imageUrl(page,solution=false,quality="preview",renderOptions={}){const canvas=await renderCanvas(page,solution,quality,renderOptions);return canvas?canvas.toDataURL("image/png"):null}
 function drawPageNumber(canvas,number){if($("#pageNumbers").value!=="yes")return canvas;const ctx=canvas.getContext("2d"),fontSize=Math.max(28,Math.round(canvas.width/61));ctx.save();ctx.fillStyle="#444";ctx.font=`${fontSize}px Arial, sans-serif`;ctx.textAlign="center";ctx.textBaseline="alphabetic";ctx.fillText(String(number),canvas.width/2,canvas.height-Math.round(canvas.height*.018));ctx.restore();return canvas}
 async function canvasToJpegBytes(canvas,quality=.94,label="strony"){if(!canvas||typeof canvas.toBlob!=="function")throw new Error(`Nie udało się wyrenderować ${label}. Sprawdź tę stronę w jej Studio.`);const blob=await new Promise(resolve=>canvas.toBlob(resolve,"image/jpeg",quality));if(!blob)throw new Error(`Przeglądarka nie utworzyła obrazu ${label}.`);return new Uint8Array(await blob.arrayBuffer())}
 function fitInto(ctx,source,x,y,width,height,monochrome=false){const scale=Math.min(width/source.width,height/source.height),drawWidth=source.width*scale,drawHeight=source.height*scale;ctx.save();if(monochrome)ctx.filter="grayscale(1)";ctx.drawImage(source,x+(width-drawWidth)/2,y+(height-drawHeight)/2,drawWidth,drawHeight);ctx.restore()}
 function solutionEntries(source=pages){const counters={};return source.map((page,index)=>({page,pageNumber:index+1})).filter(item=>hasSolution(item.page)).map(item=>{const module=moduleOf(item.page),activityNumber=(counters[module]||0)+1;counters[module]=activityNumber;return{...item,module,activityNumber,label:`${MODULE_NAMES[module]||"Activity"} ${activityNumber} — Activity Page ${item.pageNumber}`}})}
 async function solutionSheet(items,per,{showSectionTitle=true}={}){const profile=targetProfile(),canvas=document.createElement("canvas");canvas.width=profile.width;canvas.height=profile.height;const ctx=canvas.getContext("2d"),pad=Math.round(profile.width*.045),titleHeight=Math.round(profile.height*(showSectionTitle ? .075 : .035)),gap=Math.round(profile.width*.025),cols=per===4?2:1,rows=per===1?1:per===2?2:2,cellWidth=(profile.width-pad*2-gap*(cols-1))/cols,cellHeight=(profile.height-pad*2-titleHeight-gap*(rows-1))/rows;ctx.fillStyle="#fff";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle="#111";ctx.textAlign="center";ctx.textBaseline="middle";if(showSectionTitle){ctx.font=`700 ${Math.max(44,Math.round(profile.width*.026))}px Arial, sans-serif`;ctx.fillText("Solutions",canvas.width/2,pad+titleHeight*.34)}for(let offset=0;offset<items.length;offset++){const item=items[offset],source=await renderCanvas(item.page,true,"print",{solutionKey:true});if(!source)continue;const col=offset%cols,row=Math.floor(offset/cols),x=pad+col*(cellWidth+gap),y=pad+titleHeight+row*(cellHeight+gap),heading=Math.max(38,Math.round(cellHeight*.075));ctx.fillStyle="#222";ctx.font=`700 ${Math.max(28,Math.round(profile.width*.016))}px Arial, sans-serif`;ctx.fillText(item.label,x+cellWidth/2,y+heading*.45);fitInto(ctx,source,x,y+heading,cellWidth,cellHeight-heading,true)}return canvas}
 async function buildPdfFile(){if(!window.FenixPdf)throw new Error("Nie załadowano lokalnego silnika PDF.");const project=currentProject(),profile=targetProfile(),pdfPages=[],sequence=productionSequence(pages),total=sequence.body.length+sequence.solutionPageCount+sequence.closing.length;let number=1,done=0;const append=async(canvas,label)=>{if(!canvas)throw new Error(`Nie udało się wyrenderować ${label}. Sprawdź tę stronę w jej Studio.`);drawPageNumber(canvas,number++);pdfPages.push({jpegBytes:await canvasToJpegBytes(canvas,.94,label),pixelWidth:canvas.width,pixelHeight:canvas.height,widthPt:profile.width/profile.dpi*72,heightPt:profile.height/profile.dpi*72});done++;$("#cartSummary").textContent=`Generuję finalny PDF: ${done} / ${total} stron…`;await new Promise(resolve=>requestAnimationFrame(resolve))};for(let index=0;index<sequence.body.length;index++){const page=sequence.body[index];await append(await renderCanvas(page,false,"print"),`strony ${index+1} „${page.title||MODULE_NAMES[moduleOf(page)]||"bez tytułu"}”`)}for(let index=0;index<sequence.solved.length;index+=sequence.per)await append(await solutionSheet(sequence.solved.slice(index,index+sequence.per),sequence.per,{showSectionTitle:true}),`arkusza rozwiązań ${Math.floor(index/sequence.per)+1}`);for(let index=0;index<sequence.closing.length;index++){const page=sequence.closing[index];await append(await renderCanvas(page,false,"print"),`strony końcowej „${page.title||MODULE_NAMES[moduleOf(page)]||"bez tytułu"}”`)}const bytes=FenixPdf.build({pages:pdfPages,title:$("#bookTitle").value||project.name}),result=FenixPdf.download(bytes,$("#bookTitle").value||project.name);return{...result,pageCount:pdfPages.length}}
 function validateProject(){if(!validationSummary)return;const project=currentProject(),result=FenixProjectValidator.validate({...project,format:targetFormat(),pages});const icon=status=>status==="ok"?"✓":status==="warning"?"!":"×";validationSummary.innerHTML=`<strong>Gotowość: ${result.score}%</strong><br>${result.checks.map(check=>`${icon(check.status)} ${check.label}: ${check.message}`).join("<br>")}`;validationSummary.dataset.status=result.status}
 function orderedPages(source,solutionPageCount=0){return window.FenixBookOrder?.compose?FenixBookOrder.compose(source,{solutionPageCount}):window.FenixBookOrder?FenixBookOrder.sort(source):source}
 function productionSequence(source=pages){const include=$("#includeSolutions").checked,per=Number($("#solutionLayout").value)||1,clean=source.filter(page=>!page?._autoParity),sorted=window.FenixBookOrder?.sort?FenixBookOrder.sort(clean):clean,previewSolutions=include?solutionEntries(sorted):[],solutionPageCount=Math.ceil(previewSolutions.length/per),ordered=orderedPages(source,solutionPageCount),closingTest=page=>window.FenixBookOrder?.isClosing?FenixBookOrder.isClosing(page):["congratulations-studio","qr-studio","certificate-studio"].includes(moduleOf(page)),firstClosing=ordered.findIndex(closingTest),body=firstClosing<0?ordered:ordered.slice(0,firstClosing),closing=firstClosing<0?[]:ordered.slice(firstClosing),solved=include?solutionEntries(body):[];return{body,closing,solved,per,solutionPageCount,hasSolutionsDivider:false}}
 function loadCart(){pages=orderedPages(FenixCore.getCart().map((page,index)=>({...normalize(page),_builderId:page.id||`page-${index}`})));const project=currentProject();$("#bookTitle").value=project.name;$("#format").value=String(project.format).toLowerCase()==="a4"?"a4":project.format;render()}
 function renderContentSummary(){const counts=pages.reduce((result,page)=>{const module=moduleOf(page);result[module]=(result[module]||0)+1;return result},{}),entries=Object.entries(counts);$("#contentSummary").innerHTML=entries.length?entries.map(([module,count])=>`<div><span>${MODULE_NAMES[module]||module}</span><strong>${count} str.</strong></div>`).join(""):'<div class="empty-content">Studia pojawią się tutaj automatycznie po dodaniu stron.</div>'}
 async function renderThumbnails(jobs,token){let done=0,errors=0;for(const job of jobs){if(token!==renderToken)return;const {page,card,module}=job;if(!card.isConnected)continue;const thumb=card.querySelector(".page-thumb");try{const src=await imageUrl(page,false,"preview");if(token!==renderToken)return;if(!src)throw new Error(`Renderer ${module} nie zwrócił podglądu.`);thumb.innerHTML=`<img src="${src}" alt="Podgląd strony">`;thumb.dataset.renderStatus="ok"}catch(error){errors++;console.error(`Book Builder / ${module}`,error);thumb.innerHTML=`<div class="blank-thumb render-error" title="${String(error.message).replace(/"/g,'&quot;')}">BŁĄD<br><small>${MODULE_NAMES[module]||module}</small></div>`;thumb.dataset.renderStatus="error";thumb.dataset.renderError=String(error.message||error)}done++;if(done%4===0){$("#cartSummary").textContent=`Renderuję podglądy: ${done} / ${jobs.length}${errors?` · błędy: ${errors}`:""}`;await new Promise(resolve=>requestAnimationFrame(resolve))}}if(token===renderToken)$("#cartSummary").textContent=`W składzie: ${pages.length} stron · rozwiązania: ${pages.filter(hasSolution).length}${errors?` · błędy renderowania: ${errors}`:" · podglądy: OK"}.`}
 function render(){const token=++renderToken;list.innerHTML="";empty.hidden=pages.length>0;const solutions=pages.filter(hasSolution).length;$("#pageCount").textContent=`${pages.length} stron`;$("#cartSummary").textContent=`W składzie: ${pages.length} stron · rozwiązania: ${solutions} · przygotowuję dokładne podglądy…`;renderContentSummary();let lastSection="";const jobs=[];pages.forEach((page,index)=>{const section=window.FenixBookOrder?FenixBookOrder.section(page):"Strony książki";if(section!==lastSection){const heading=document.createElement("h3");heading.className="page-section-heading";heading.textContent=section;list.appendChild(heading);lastSection=section}const card=document.createElement("article");card.className="page-card";card.draggable=true;const module=page.module||"strona";card.dataset.pageId=page.id||page._builderId||"";card.dataset.module=module;card.innerHTML=`<span class="page-index">${index+1}</span><div class="page-thumb"><div class="blank-thumb">…</div></div><div class="page-meta"><strong>${page.title||module||"Strona"}</strong><small>${page._blank||module==="blank-page"?"Pusta strona":hasSolution(page)?`${module} · rozwiązanie dostępne`:module}</small><div class="card-actions"><button data-up="${index}">↑</button><button data-down="${index}">↓</button><button class="danger" data-remove="${index}">Usuń</button></div></div>`;card.ondragstart=()=>{dragIndex=index;card.classList.add("dragging")};card.ondragend=()=>card.classList.remove("dragging");card.ondragover=event=>event.preventDefault();card.ondrop=event=>{event.preventDefault();if(dragIndex===null||dragIndex===index)return;const[moved]=pages.splice(dragIndex,1);pages.splice(index,0,moved);dragIndex=null;render()};list.appendChild(card);jobs.push({page,card,module})});document.querySelectorAll("[data-remove]").forEach(button=>button.onclick=()=>{pages.splice(Number(button.dataset.remove),1);render()});document.querySelectorAll("[data-up]").forEach(button=>button.onclick=()=>move(Number(button.dataset.up),-1));document.querySelectorAll("[data-down]").forEach(button=>button.onclick=()=>move(Number(button.dataset.down),1));validateProject();void renderThumbnails(jobs,token)}
 function move(index,direction){const target=index+direction;if(target<0||target>=pages.length)return;[pages[index],pages[target]]=[pages[target],pages[index]];render()}
 function addPrintPage(imageData,index){const element=document.createElement("article");element.className="print-page";if(imageData){const image=document.createElement("img");image.src=imageData;element.appendChild(image)}if($("#pageNumbers").value==="yes"){const number=document.createElement("div");number.className="page-number-print";number.textContent=index;element.appendChild(number)}printBook.appendChild(element)}
 async function buildPrintBook(){const project=currentProject(),sequence=productionSequence(pages);printBook.innerHTML="";printBook.dataset.format=targetFormat();printBook.dataset.bleed=project.bleed==="bleed"?"bleed":"no-bleed";let number=1;for(const page of sequence.body)addPrintPage(await imageUrl(page,false,"print"),number++);for(let index=0;index<sequence.solved.length;index+=sequence.per){const sheet=document.createElement("article");sheet.className="print-page";const title=document.createElement("div");title.className="solutions-title";title.textContent="Solutions";sheet.appendChild(title);const grid=document.createElement("div");grid.className=`solutions-grid layout-${sequence.per} with-title`;for(const item of sequence.solved.slice(index,index+sequence.per)){const image=await imageUrl(item.page,true,"print",{solutionKey:true});if(!image)continue;const box=document.createElement("div");box.className="solution-box";box.innerHTML=`<h3>${item.label}</h3><img src="${image}" alt="${item.label}">`;grid.appendChild(box)}sheet.appendChild(grid);if($("#pageNumbers").value==="yes"){const n=document.createElement("div");n.className="page-number-print";n.textContent=number;sheet.appendChild(n)}number++;printBook.appendChild(sheet)}for(const page of sequence.closing)addPrintPage(await imageUrl(page,false,"print"),number++);return printBook.children.length}
 function setBusy(busy,text="Przygotowuję skład…"){[$("#previewBook"),$("#exportPdf")].forEach(button=>button.disabled=busy);if(busy)$("#cartSummary").textContent=text;else $("#cartSummary").textContent=`W składzie: ${pages.length} stron · rozwiązania: ${pages.filter(hasSolution).length}.`}
 $("#reloadCart").onclick=loadCart;$("#autoOrder").onclick=()=>{const include=$("#includeSolutions").checked,per=Number($("#solutionLayout").value)||1,solutionPageCount=include?Math.ceil(solutionEntries(pages).length/per):0;pages=orderedPages(pages,solutionPageCount);render();$("#cartSummary").textContent=`Uporządkowano ${pages.length} stron: wprowadzenie → ćwiczenia → rozwiązania → zakończenie.`};$("#addBlank").onclick=()=>{const stamp=Date.now();pages.push({_builderId:`blank-${stamp}`,_blank:true,id:`blank-${stamp}`,schemaVersion:3,title:"Pusta strona",module:"blank-page",recipe:{module:"blank-page",seed:null,title:"Pusta strona",settings:{},content:{},meta:{},renderState:{}},preview:{imageData:null},solution:{available:false,imageData:null},validation:{kdp:{status:"ok",messages:[]}},production:targetProfile(),source:{app:"book-builder",version:"0.33.0",format:"native"}});render()};
 $("#previewBook").onclick=async()=>{if(!pages.length)return alert("Projekt nie zawiera jeszcze stron.");setBusy(true);try{const count=await buildPrintBook();alert(`Podgląd przygotowany: ${count} stron.`)}catch(error){console.error(error);alert(`Nie udało się przygotować podglądu: ${error.message}`)}finally{setBusy(false)}};
 $("#exportPdf").onclick=async()=>{if(!pages.length)return alert("Projekt nie zawiera jeszcze stron.");setBusy(true,"Renderuję finalny PDF 300 DPI…");try{const result=await buildPdfFile();alert(`Gotowy PDF: ${result.fileName}\nStrony: ${result.pageCount}\nRozmiar: ${(result.size/1024/1024).toFixed(1)} MB\n\nPlik został pobrany na komputer.`)}catch(error){console.error(error);alert(`Nie udało się wygenerować PDF: ${error.message}`)}finally{setBusy(false)}};
 ["format","pageNumbers","includeSolutions","solutionLayout"].forEach(id=>$("#"+id)?.addEventListener("change",()=>{if(id==="format")render();else validateProject()}));loadCart();
})();
