"use strict";
window.FenixAssetManager=(()=>{
  const VERSION=1,ROLES=Object.freeze(["content","gameplay","deco"]),clone=value=>value==null?value:typeof structuredClone==="function"?structuredClone(value):JSON.parse(JSON.stringify(value)),normalizeTags=value=>[...new Set((Array.isArray(value)?value:[]).map(tag=>String(tag||"").trim().toLowerCase()).filter(Boolean))];
  const readDataUrl=file=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=()=>reject(r.error||new Error("Nie udało się odczytać pliku."));r.readAsDataURL(file)}),readDimensions=dataUrl=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve({width:im.naturalWidth||im.width,height:im.naturalHeight||im.height});im.onerror=()=>reject(new Error("Nie udało się odczytać wymiarów obrazu."));im.src=dataUrl}),validator=()=>window.FenixAssetValidator||null;
  function assets(projectId){return FenixCore.listAssets(projectId)}function duplicateOf(file,projectId){return assets(projectId).find(a=>a.filename===file.name&&Number(a.sizeBytes)===Number(file.size)&&String(a.mime||"")===String(file.type||""))||null}
  async function importFiles(files,{projectId=FenixCore.getActiveProjectId(),source="imported",validate=true}={}){const list=[...(files||[])],summary={added:0,duplicates:0,failed:0,assets:[],errors:[]};for(const file of list){try{if(duplicateOf(file,projectId)){summary.duplicates++;continue}const v=validator();if(v&&Array.isArray(v.SUPPORTED)&&!v.SUPPORTED.includes(file.type))throw new Error("Nieobsługiwany format. Użyj PNG, JPG/JPEG, WEBP albo SVG.");const dataUrl=await readDataUrl(file),d=await readDimensions(dataUrl),base={name:file.name.replace(/\.[^.]+$/,"")||"Asset",filename:file.name,mime:file.type||"image/png",dataUrl,source,width:d.width,height:d.height,sizeBytes:file.size,aspectRatio:d.width&&d.height?Number((d.width/d.height).toFixed(4)):null,tags:[]},validation=validate&&v?await v.validate(base):{status:"warning",messages:["Asset nie był jeszcze walidowany."],metrics:{}};const saved=FenixCore.putAsset({...base,validation});summary.assets.push(saved);summary.added++}catch(error){summary.failed++;summary.errors.push({file:file?.name||"Asset",message:String(error?.message||error)})}}return summary}
  function setRole(id,role,enabled=true){if(!ROLES.includes(role))return false;const a=FenixCore.getAsset(id);if(!a)return false;const tags=new Set(normalizeTags(a.tags));enabled?tags.add(role):tags.delete(role);return FenixCore.updateAsset(id,{tags:[...tags]})}function toggleRole(id,role){const a=FenixCore.getAsset(id);return a?setRole(id,role,!normalizeTags(a.tags).includes(role)):false}function bulkRole(ids,role){const list=[...new Set(ids||[])].map(id=>FenixCore.getAsset(id)).filter(Boolean);if(!list.length||!ROLES.includes(role))return[];const remove=list.every(a=>normalizeTags(a.tags).includes(role));return list.map(a=>setRole(a.id,role,!remove)).filter(Boolean)}function clearRoles(ids){return[...new Set(ids||[])].map(id=>FenixCore.updateAsset(id,{tags:[]})).filter(Boolean)}function rename(id,name){const clean=String(name||"").trim();return clean?FenixCore.updateAsset(id,{name:clean}):false}
  function usage(id,projectId=FenixCore.getActiveProjectId()){return FenixCore.assetUsage?FenixCore.assetUsage(id,projectId):[]}function remove(id,{force=false}={}){return FenixCore.removeAsset?FenixCore.removeAsset(id,{force}):{removed:false,reason:"unsupported",usage:usage(id)}}async function revalidate(id){const a=FenixCore.getAsset(id),v=validator();if(!a||!v)return false;return FenixCore.updateAsset(id,{validation:await v.validate(a)})}async function revalidateAll(projectId=FenixCore.getActiveProjectId()){const out={total:0,ok:0,warning:0,error:0};for(const a of assets(projectId)){const u=await revalidate(a.id);if(!u)continue;out.total++;const s=u.validation?.status||"warning";out[s]=(out[s]||0)+1}return out}
  function filter({query="",role="",status="",sort="newest",projectId=FenixCore.getActiveProjectId()}={}){const q=String(query).trim().toLowerCase(),r=String(role).trim().toLowerCase(),st=String(status).trim().toLowerCase();let list=assets(projectId).filter(a=>(!q||`${a.name} ${a.filename} ${(a.tags||[]).join(" ")}`.toLowerCase().includes(q))&&(!r||(a.tags||[]).includes(r))&&(!st||String(a.validation?.status||"warning").toLowerCase()===st));return list.sort((a,b)=>sort==="name"?String(a.name).localeCompare(String(b.name),"pl",{sensitivity:"base"}):sort==="oldest"?String(a.createdAt).localeCompare(String(b.createdAt)):String(b.createdAt).localeCompare(String(a.createdAt)))}
  function library(projectId=FenixCore.getActiveProjectId()){const seen=new Set(),out=[];for(const p of FenixCore.getProjects())for(const a of Object.values(p.assets||{})){const key=a.dataUrl||`${a.filename}|${a.sizeBytes}`;if(seen.has(key))continue;seen.add(key);out.push({...clone(a),_projectId:p.id,_projectName:p.name,_active:p.id===projectId})}return out}
  return Object.freeze({VERSION,ROLES,assets,duplicateOf,importFiles,toggleRole,setRole,bulkRole,clearRoles,rename,usage,remove,revalidate,revalidateAll,filter,library});
})();