"use strict";
window.FenixSync=(()=>{
  const CONFIG_KEY="fenix-sync-config-v1",TOKEN_KEY="fenix-sync-token-v1",FORMAT="FENIX_SYNC_BUNDLE",VERSION=1,DEFAULTS=Object.freeze({provider:"github",owner:"opalkop",repo:"fenix",branch:"fenix-sync-data",path:"fenix-sync/projects.json",autoSync:true});
  const safeParse=(v,fallback)=>{try{return JSON.parse(v)||fallback}catch{return fallback}},readConfig=()=>safeParse(localStorage.getItem(CONFIG_KEY),{});
  function getConfig(){const c=readConfig();return{...DEFAULTS,...c,token:sessionStorage.getItem(TOKEN_KEY)||c.token||"",rememberToken:Boolean(c.token),autoSync:c.autoSync!==false}}
  function setConfig(next={}){const merged={...getConfig(),...next},persistent={provider:"github",owner:String(merged.owner||DEFAULTS.owner).trim(),repo:String(merged.repo||DEFAULTS.repo).trim(),branch:String(merged.branch||DEFAULTS.branch).trim(),path:String(merged.path||DEFAULTS.path).trim(),autoSync:merged.autoSync!==false};if(next.rememberToken&&merged.token)persistent.token=merged.token;localStorage.setItem(CONFIG_KEY,JSON.stringify(persistent));if(merged.token)sessionStorage.setItem(TOKEN_KEY,merged.token);else sessionStorage.removeItem(TOKEN_KEY);return getConfig()}
  function clearToken(){sessionStorage.removeItem(TOKEN_KEY);const c=readConfig();delete c.token;localStorage.setItem(CONFIG_KEY,JSON.stringify(c))}
  function snapshot(){const projects=FenixCore.getProjects();if(!Array.isArray(projects)||!projects.length)throw new Error("Fenix Sync: brak lokalnych projektów do wysłania.");return{type:FORMAT,version:VERSION,schemaVersion:window.FenixPageSchema?.VERSION||3,updatedAt:new Date().toISOString(),activeId:FenixCore.getActiveProjectId(),projects}}
  const newer=(a,b)=>String(a?.updatedAt||a?.createdAt||"").localeCompare(String(b?.updatedAt||b?.createdAt||""))>0;
  function mergeBundle(bundle,{prefer="newer"}={}){if(!bundle||bundle.type!==FORMAT||!Array.isArray(bundle.projects))throw new Error("Nieprawidłowy pakiet synchronizacji FENIX.");const byId=new Map(FenixCore.getProjects().map(p=>[p.id,p])),stats={created:0,updated:0,kept:0};for(const remote of bundle.projects){const here=byId.get(remote.id);if(!here){FenixCore.createProject(remote);stats.created++;byId.set(remote.id,remote);continue}const take=prefer==="remote"||prefer==="newer"&&newer(remote,here);if(take){FenixCore.updateProject(here.id,remote);stats.updated++}else stats.kept++}if(bundle.activeId&&FenixCore.getProjects().some(p=>p.id===bundle.activeId))FenixCore.setActiveProject(bundle.activeId);return stats}
  function b64utf8(text){const bytes=new TextEncoder().encode(text);let bin="";bytes.forEach(b=>bin+=String.fromCharCode(b));return btoa(bin)}
  function unb64utf8(text){const bin=atob(String(text||"").replace(/\n/g,"")),bytes=Uint8Array.from(bin,c=>c.charCodeAt(0));return new TextDecoder().decode(bytes)}
  function requireConfig(){const c=getConfig();if(!c.token)throw new Error("Fenix Sync wymaga jednorazowego tokenu GitHub na tym urządzeniu.");return c}
  async function githubRequest(url,options={}){const c=requireConfig(),headers={Accept:"application/vnd.github+json","X-GitHub-Api-Version":"2022-11-28",Authorization:`Bearer ${c.token}`,...options.headers},response=await fetch(url,{...options,headers});if(!response.ok&&response.status!==404){const body=await response.text().catch(()=>"");throw new Error(`GitHub Sync ${response.status}: ${body.slice(0,180)}`)}return response}
  const contentsUrl=c=>`https://api.github.com/repos/${encodeURIComponent(c.owner)}/${encodeURIComponent(c.repo)}/contents/${c.path.split('/').map(encodeURIComponent).join('/')}?ref=${encodeURIComponent(c.branch)}`;
  const writeUrl=c=>`https://api.github.com/repos/${encodeURIComponent(c.owner)}/${encodeURIComponent(c.repo)}/contents/${c.path.split('/').map(encodeURIComponent).join('/')}`;
  async function readRemoteMeta(){const c=requireConfig(),res=await githubRequest(contentsUrl(c));if(res.status===404)return null;return res.json()}
  async function readRemoteText(){const c=requireConfig(),res=await githubRequest(contentsUrl(c),{headers:{Accept:"application/vnd.github.raw+json"}});if(res.status===404)return null;const text=await res.text();if(!text.trim())throw new Error("Plik synchronizacji w GitHubie jest pusty lub niedostępny. Wyślij projekt ponownie z urządzenia, na którym masz poprawną kopię.");return text}
  async function pull({merge=true}={}){const meta=await readRemoteMeta();if(!meta)return{found:false,bundle:null,stats:null};let text="";if(meta.content){text=unb64utf8(meta.content)}else{text=await readRemoteText()}let bundle;try{bundle=JSON.parse(text)}catch{throw new Error("Nie można odczytać danych synchronizacji z GitHuba. Plik może być uszkodzony albo niekompletny.")}const stats=merge?mergeBundle(bundle):null;localStorage.setItem("fenix-sync-last-pull",new Date().toISOString());return{found:true,bundle,stats,sha:meta.sha}}
  async function push(){const c=requireConfig(),meta=await readRemoteMeta(),sha=meta?.sha||null,bundle=snapshot(),json=JSON.stringify(bundle);if(!json||json.length<20)throw new Error("Fenix Sync przerwał wysyłanie: lokalny pakiet projektu jest pusty.");const body={message:`Fenix Sync ${new Date().toISOString()}`,content:b64utf8(json),branch:c.branch};if(sha)body.sha=sha;const res=await githubRequest(writeUrl(c),{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),data=await res.json();localStorage.setItem("fenix-sync-last-push",new Date().toISOString());return{bundle,commit:data.commit?.sha||null,size:json.length}}
  async function sync(){let remote=null;try{remote=await pull({merge:true})}catch(error){if(!/pusty|uszkodzony|niekompletny/i.test(String(error.message||error)))throw error}const pushed=await push();window.dispatchEvent(new CustomEvent("fenix-sync-complete",{detail:{remote,pushed}}));return{remote,pushed}}
  async function auto(){const c=getConfig();if(!c.autoSync||!c.token)return{skipped:true};try{return await sync()}catch(error){console.warn("Fenix auto sync",error);return{error:String(error.message||error)}}}
  return Object.freeze({FORMAT,VERSION,DEFAULTS,getConfig,setConfig,clearToken,snapshot,mergeBundle,pull,push,sync,auto});
})();