"use strict";
window.FenixSync=(()=>{
  const CONFIG_KEY="fenix-sync-config-v1",TOKEN_KEY="fenix-sync-token-v1",FORMAT="FENIX_SYNC_BUNDLE",CHUNK_FORMAT="FENIX_SYNC_PAYLOAD_CHUNK",VERSION=6,MAX_CHUNK_BYTES=2800000,MAX_PART_CHARS=1800000,DEFAULTS=Object.freeze({provider:"github",owner:"opalkop",repo:"fenix",branch:"fenix-sync-data",path:"fenix-sync/projects.json",autoSync:true});
  let pushInFlight=null;
  const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
  const safeParse=(v,fallback)=>{try{return JSON.parse(v)||fallback}catch{return fallback}},readConfig=()=>safeParse(localStorage.getItem(CONFIG_KEY),{});
  function getConfig(){const c=readConfig();return{...DEFAULTS,...c,token:sessionStorage.getItem(TOKEN_KEY)||c.token||"",rememberToken:Boolean(c.token),autoSync:c.autoSync!==false}}
  function setConfig(next={}){const merged={...getConfig(),...next},persistent={provider:"github",owner:String(merged.owner||DEFAULTS.owner).trim(),repo:String(merged.repo||DEFAULTS.repo).trim(),branch:String(merged.branch||DEFAULTS.branch).trim(),path:String(merged.path||DEFAULTS.path).trim(),autoSync:merged.autoSync!==false};if(next.rememberToken&&merged.token)persistent.token=merged.token;localStorage.setItem(CONFIG_KEY,JSON.stringify(persistent));if(merged.token)sessionStorage.setItem(TOKEN_KEY,merged.token);else sessionStorage.removeItem(TOKEN_KEY);return getConfig()}
  function clearToken(){sessionStorage.removeItem(TOKEN_KEY);const c=readConfig();delete c.token;localStorage.setItem(CONFIG_KEY,JSON.stringify(c))}
  const libraryRefOf=asset=>String(asset?.libraryRef||asset?.meta?.libraryRef||"").trim();
  function compactProjects(projects){return projects.map(project=>({...project,assets:Object.fromEntries(Object.entries(project.assets||{}).map(([id,asset])=>[id,libraryRefOf(asset)?{...asset,dataUrl:""}:asset]))}))}
  function snapshot(){const projects=FenixCore.getProjects();if(!Array.isArray(projects)||!projects.length)throw new Error("Fenix Sync: brak lokalnych projektów do wysłania.");return{type:FORMAT,version:VERSION,schemaVersion:window.FenixPageSchema?.VERSION||3,updatedAt:new Date().toISOString(),activeId:FenixCore.getActiveProjectId(),assetLibrary:FenixCore.getAssetLibrary?.()||{},projects:compactProjects(projects)}}
  const copy=value=>typeof structuredClone==="function"?structuredClone(value):JSON.parse(JSON.stringify(value)),byteSize=value=>new TextEncoder().encode(String(value||"")).byteLength;
  const progress=(phase,current,total)=>window.dispatchEvent(new CustomEvent("fenix-sync-progress",{detail:{phase,current,total}}));
  function extractPayloads(value,path=[],out=[]){if(!value||typeof value!=="object")return out;for(const key of Object.keys(value)){const item=value[key],next=[...path,key];if(typeof item==="string"&&item.startsWith("data:")&&item.length){out.push({path:next,data:item});value[key]=""}else if(item&&typeof item==="object")extractPayloads(item,next,out)}return out}
  function chunkRoot(path){const clean=String(path||DEFAULTS.path).replace(/^\/+|\/+$/g,""),cut=clean.lastIndexOf("/");return`${cut>=0?`${clean.slice(0,cut)}/`:""}chunks`}
  function buildCloudPlan(source=snapshot(),manifestPath=getConfig().path){const manifest=copy(source),payloads=extractPayloads(manifest),pieces=[];for(const payload of payloads){const parts=Math.max(1,Math.ceil(payload.data.length/MAX_PART_CHARS));for(let part=0;part<parts;part++)pieces.push({path:payload.path,part,parts,data:payload.data.slice(part*MAX_PART_CHARS,(part+1)*MAX_PART_CHARS)})}const groups=[];let current=[];for(const piece of pieces){const candidate={type:CHUNK_FORMAT,version:1,pieces:[...current,piece]};if(current.length&&byteSize(JSON.stringify(candidate))>MAX_CHUNK_BYTES){groups.push(current);current=[piece]}else current.push(piece)}if(current.length)groups.push(current);const root=chunkRoot(manifestPath),chunks=groups.map((group,index)=>{const text=JSON.stringify({type:CHUNK_FORMAT,version:1,pieces:group}),path=`${root}/payload-${String(index+1).padStart(4,"0")}.json`;return{path,text,bytes:byteSize(text),pieceCount:group.length}});manifest.assetChunks=chunks.map(({path,bytes,pieceCount},index)=>({path,bytes,pieceCount,index:index+1}));manifest.payloadCount=payloads.length;return{manifest,chunks,payloadCount:payloads.length,size:byteSize(JSON.stringify(source)),manifestSize:byteSize(JSON.stringify(manifest))}}
  function setAtPath(target,path,value){if(!Array.isArray(path)||!path.length)throw new Error("Fenix Sync: nieprawidłowa ścieżka danych assetu.");let node=target;for(let index=0;index<path.length-1;index++){const key=path[index];if(!node||typeof node!=="object"||!(key in node))throw new Error("Fenix Sync: paczka assetów nie pasuje do manifestu.");node=node[key]}node[path.at(-1)]=value}
  function hydrateCloudBundle(source,chunkDocuments=[]){const bundle=copy(source),assembled=new Map;for(const chunk of chunkDocuments){if(chunk?.type!==CHUNK_FORMAT||!Array.isArray(chunk.pieces))throw new Error("Fenix Sync: nieprawidłowa część danych assetów.");for(const piece of chunk.pieces){const key=JSON.stringify(piece.path),entry=assembled.get(key)||{path:piece.path,parts:new Array(Number(piece.parts)||1)};entry.parts[Number(piece.part)||0]=String(piece.data||"");assembled.set(key,entry)}}for(const entry of assembled.values()){if(entry.parts.some(part=>typeof part!=="string"))throw new Error("Fenix Sync: brakuje fragmentu danych assetu.");setAtPath(bundle,entry.path,entry.parts.join(""))}if(Number(bundle.payloadCount||0)!==assembled.size)throw new Error(`Fenix Sync: pobrano ${assembled.size} z ${bundle.payloadCount||0} danych assetów.`);return bundle}
  const newer=(a,b)=>String(a?.updatedAt||a?.createdAt||"").localeCompare(String(b?.updatedAt||b?.createdAt||""))>0;
  function mergeAssetLibrarySafely(remoteLibrary,prefer){const incoming=remoteLibrary&&typeof remoteLibrary==="object"?remoteLibrary:{},local=FenixCore.getAssetLibrary?.()||{},normal={},forced={};for(const [id,remote] of Object.entries(incoming)){const here=local[id],remoteHasPayload=typeof remote?.dataUrl==="string"&&remote.dataUrl.startsWith("data:")&&remote.dataUrl.length>0,localHasPayload=typeof here?.dataUrl==="string"&&here.dataUrl.startsWith("data:")&&here.dataUrl.length>0;if(here&&!localHasPayload&&remoteHasPayload)forced[id]=remote;else normal[id]=remote}const base=FenixCore.mergeAssetLibrary?.(normal,{prefer})||{created:0,updated:0,kept:0},repair=Object.keys(forced).length?(FenixCore.mergeAssetLibrary?.(forced,{prefer:"remote"})||{created:0,updated:0,kept:0}):{created:0,updated:0,kept:0};return{created:(base.created||0)+(repair.created||0),updated:(base.updated||0)+(repair.updated||0),kept:(base.kept||0)+(repair.kept||0),repaired:Object.keys(forced).length}}
  function mergeBundle(bundle,{prefer="newer"}={}){if(!bundle||bundle.type!==FORMAT||!Array.isArray(bundle.projects))throw new Error("Nieprawidłowy pakiet synchronizacji FENIX.");const libraryStats=mergeAssetLibrarySafely(bundle.assetLibrary||{},prefer);const byId=new Map(FenixCore.getProjects().map(p=>[p.id,p])),stats={created:0,updated:0,kept:0,library:libraryStats};for(const remote of bundle.projects){const here=byId.get(remote.id);if(!here){FenixCore.createProject(remote);stats.created++;byId.set(remote.id,remote);continue}const take=prefer==="remote"||prefer==="newer"&&newer(remote,here);if(take){FenixCore.updateProject(here.id,remote);stats.updated++}else stats.kept++}if(bundle.activeId&&FenixCore.getProjects().some(p=>p.id===bundle.activeId))FenixCore.setActiveProject(bundle.activeId);return stats}
  async function mergeAndFlush(bundle,options){await FenixCore.ready;const stats=mergeBundle(bundle,options);await FenixCore.flushStorage();return stats}
  function unb64utf8(text){const clean=String(text||"").replace(/\s/g,"");if(!clean)return"";const bin=atob(clean),bytes=Uint8Array.from(bin,c=>c.charCodeAt(0));return new TextDecoder().decode(bytes)}
  function requireConfig(){const c=getConfig();if(!c.token)throw new Error("Fenix Sync wymaga jednorazowego tokenu GitHub na tym urządzeniu.");return c}
  async function githubRequest(url,options={}){const c=requireConfig(),headers={Accept:"application/vnd.github+json","X-GitHub-Api-Version":"2022-11-28",Authorization:`Bearer ${c.token}`,...options.headers},response=await fetch(url,{...options,headers});if(!response.ok&&response.status!==404){const body=await response.text().catch(()=>"");const error=new Error(`GitHub Sync ${response.status}: ${body.slice(0,220)}`);error.status=response.status;throw error}return response}
  const apiBase=c=>`https://api.github.com/repos/${encodeURIComponent(c.owner)}/${encodeURIComponent(c.repo)}`;
  const contentsUrl=(c,path=c.path)=>`${apiBase(c)}/contents/${String(path||"").split('/').map(encodeURIComponent).join('/')}?ref=${encodeURIComponent(c.branch)}`;
  async function readRemoteMeta(path=null){const c=requireConfig(),res=await githubRequest(contentsUrl(c,path||c.path));if(res.status===404)return null;return res.json()}
  async function readRemoteText(meta=null){const c=requireConfig();if(meta?.git_url){const res=await githubRequest(meta.git_url);const blob=await res.json();const text=unb64utf8(blob?.content);if(text)return text}const res=await githubRequest(contentsUrl(c),{headers:{Accept:"application/vnd.github.raw+json"}});if(res.status===404)return null;const text=await res.text();if(!text.trim())throw new Error("Plik synchronizacji w GitHubie jest pusty lub niedostępny.");return text}
  async function pull({merge=true,prefer="newer"}={}){const meta=await readRemoteMeta();if(!meta)return{found:false,bundle:null,stats:null};const text=meta.content?unb64utf8(meta.content):await readRemoteText(meta);let bundle;try{bundle=JSON.parse(text)}catch{throw new Error("Nie można odczytać danych synchronizacji z GitHuba. Plik może być uszkodzony albo niekompletny.")}const chunkRefs=Array.isArray(bundle.assetChunks)?bundle.assetChunks:[];if(chunkRefs.length){const documents=[];for(let index=0;index<chunkRefs.length;index++){progress("pull",index,chunkRefs.length);const chunkMeta=await readRemoteMeta(chunkRefs[index].path);if(!chunkMeta)throw new Error(`Fenix Sync: brakuje części ${index+1}/${chunkRefs.length}.`);const chunkText=chunkMeta.content?unb64utf8(chunkMeta.content):await readRemoteText(chunkMeta);try{documents.push(JSON.parse(chunkText))}catch{throw new Error(`Fenix Sync: część ${index+1}/${chunkRefs.length} jest uszkodzona.`)}}bundle=hydrateCloudBundle(bundle,documents);progress("pull",chunkRefs.length,chunkRefs.length)}const stats=merge?await mergeAndFlush(bundle,{prefer}):null;localStorage.setItem("fenix-sync-last-pull",new Date().toISOString());return{found:true,bundle,stats,sha:meta.sha||null,chunks:chunkRefs.length,size:byteSize(JSON.stringify(bundle))}}
  async function jsonRequest(url,method,body){const res=await githubRequest(url,{method,headers:{"Content-Type":"application/json"},body:body?JSON.stringify(body):undefined});return res.json()}
  async function writeViaGitData(bundle){const c=requireConfig(),plan=buildCloudPlan(bundle,c.path),base=apiBase(c),refUrl=`${base}/git/ref/heads/${encodeURIComponent(c.branch)}`,refUpdateUrl=`${base}/git/refs/heads/${encodeURIComponent(c.branch)}`;for(let attempt=0;attempt<5;attempt++){const ref=await(await githubRequest(refUrl)).json(),head=ref?.object?.sha;if(!head)throw new Error("Fenix Sync nie może odczytać aktualnego commita brancha synchronizacji.");const commit=await(await githubRequest(`${base}/git/commits/${head}`)).json(),baseTree=commit?.tree?.sha;if(!baseTree)throw new Error("Fenix Sync nie może odczytać drzewa brancha synchronizacji.");const treeEntries=[];for(let index=0;index<plan.chunks.length;index++){progress("push",index,plan.chunks.length+1);const chunk=plan.chunks[index],blob=await jsonRequest(`${base}/git/blobs`,"POST",{content:chunk.text,encoding:"utf-8"});treeEntries.push({path:chunk.path,mode:"100644",type:"blob",sha:blob.sha})}progress("push",plan.chunks.length,plan.chunks.length+1);const manifestText=JSON.stringify(plan.manifest),manifestBlob=await jsonRequest(`${base}/git/blobs`,"POST",{content:manifestText,encoding:"utf-8"});treeEntries.push({path:String(c.path||"").replace(/^\/+/,""),mode:"100644",type:"blob",sha:manifestBlob.sha});const tree=await jsonRequest(`${base}/git/trees`,"POST",{base_tree:baseTree,tree:treeEntries}),next=await jsonRequest(`${base}/git/commits`,"POST",{message:`Fenix Sync ${new Date().toISOString()}`,tree:tree.sha,parents:[head]});try{await jsonRequest(refUpdateUrl,"PATCH",{sha:next.sha,force:false});progress("push",plan.chunks.length+1,plan.chunks.length+1);return{commit:next.sha,chunks:plan.chunks.length,size:plan.size,manifestSize:plan.manifestSize,payloadCount:plan.payloadCount}}catch(error){if(error?.status!==409&&error?.status!==422)throw error;if(attempt===4)throw new Error("Fenix Sync wykrył równoległą zmianę w chmurze. Zamknij Fenix na innych urządzeniach i spróbuj ponownie.");await sleep(300*(attempt+1))}}}
  async function doPush(){await FenixCore.ready;await FenixCore.flushStorage();const bundle=snapshot(),cloud=await writeViaGitData(bundle);localStorage.setItem("fenix-sync-last-push",new Date().toISOString());return{bundle,...cloud}}
  async function push(){if(pushInFlight)return pushInFlight;pushInFlight=doPush();try{return await pushInFlight}finally{pushInFlight=null}}
  async function sync(){let remote=null;try{remote=await pull({merge:true,prefer:"newer"})}catch(error){if(!/pusty|uszkodzony|niekompletny/i.test(String(error.message||error)))throw error}const pushed=await push();window.dispatchEvent(new CustomEvent("fenix-sync-complete",{detail:{remote,pushed}}));return{remote,pushed}}
  async function auto(){const c=getConfig();if(!c.autoSync||!c.token)return{skipped:true};try{return await pull({merge:true,prefer:"newer"})}catch(error){console.warn("Fenix auto sync",error);return{error:String(error.message||error)}}}
  function bundleToText({pretty=true}={}){const bundle=snapshot(),text=JSON.stringify(bundle,null,pretty?2:0);return{bundle,text,size:new Blob([text]).size}}
  function exportLocalBundle(){const out=bundleToText({pretty:true}),date=new Date().toISOString().replace(/[:.]/g,"-");FenixCore.download(`fenix-sync-${date}.fenixsync`,out.text,"application/json");localStorage.setItem("fenix-sync-last-export",new Date().toISOString());return{bundle:out.bundle,size:out.size}}
  function parseLocalBundle(text){let bundle;try{bundle=JSON.parse(String(text||""))}catch{throw new Error("Nie można odczytać pliku Fenix Sync. Plik nie jest poprawnym JSON-em.")}if(!bundle||bundle.type!==FORMAT||!Array.isArray(bundle.projects))throw new Error("To nie jest prawidłowy plik Fenix Sync.");return bundle}
  async function importLocalBundle(file,{prefer="remote"}={}){if(!file)throw new Error("Nie wybrano pliku Fenix Sync.");await FenixCore.ready;const text=await file.text(),size=Number(file.size)||new Blob([text]).size,bundle=parseLocalBundle(text),stats=await mergeAndFlush(bundle,{prefer});localStorage.setItem("fenix-sync-last-import",new Date().toISOString());const storage=FenixCore.getStorageInfo();window.dispatchEvent(new CustomEvent("fenix-sync-local-import",{detail:{stats,size,storage}}));return{bundle,stats,size,storage}}
  return Object.freeze({FORMAT,VERSION,DEFAULTS,getConfig,setConfig,clearToken,snapshot,buildCloudPlan,hydrateCloudBundle,mergeBundle,pull,push,sync,auto,bundleToText,exportLocalBundle,parseLocalBundle,importLocalBundle});
})();
