"use strict";
(()=>{
  if(!window.FenixSync||document.getElementById("fenixSyncButton"))return;
  let busy=false,pushTimer=null,lastRemoteAt=0;
  const configured=()=>{const c=FenixSync.getConfig();return Boolean(c.autoSync&&c.owner&&c.repo&&c.token)};
  const style=document.createElement("style");style.textContent=`#fenixSyncButton{position:fixed;right:14px;bottom:14px;z-index:9998;border:0;border-radius:999px;padding:11px 15px;background:#111827;color:#fff;font:800 13px system-ui;box-shadow:0 8px 28px #0003}#fenixSyncButton[data-state="busy"]{opacity:.65}#fenixSyncPanel{position:fixed;inset:auto 12px 64px auto;z-index:9999;width:min(390px,calc(100vw - 24px));max-height:calc(100vh - 90px);overflow:auto;background:#fff;color:#111827;border:1px solid #d7dce3;border-radius:16px;padding:14px;box-shadow:0 18px 50px #0004;font:13px system-ui}#fenixSyncPanel[hidden]{display:none}#fenixSyncPanel h3{margin:0 0 5px}#fenixSyncPanel p{margin:0 0 10px;color:#5b6572}#fenixSyncPanel label{display:block;font-weight:750;margin:8px 0}#fenixSyncPanel input{display:block;box-sizing:border-box;width:100%;margin-top:4px;padding:9px;border:1px solid #ccd3dc;border-radius:9px}#fenixSyncPanel .row{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}#fenixSyncPanel button{padding:9px 11px;border:1px solid #ccd3dc;border-radius:9px;background:#f5f7f9;font-weight:800}#fenixSyncPanel button.primary{background:#111827;color:#fff;border-color:#111827}#fenixSyncStatus{padding:8px;margin-top:9px;border-radius:9px;background:#f4f6f8;white-space:pre-wrap}#fenixSyncPanel .check{display:flex;align-items:center;gap:7px}#fenixSyncPanel .check input{width:auto;margin:0}`;document.head.appendChild(style);
  const button=document.createElement("button");button.id="fenixSyncButton";button.type="button";button.textContent="↻ Fenix Sync";
  const panel=document.createElement("section");panel.id="fenixSyncPanel";panel.hidden=true;panel.innerHTML=`<h3>Fenix Sync</h3><p>Ten sam projekt na Windows, Linux i mobile.</p><label>GitHub owner<input id="fsOwner" autocomplete="username"></label><label>Repozytorium danych<input id="fsRepo" placeholder="np. fenix-sync-data"></label><label>Branch<input id="fsBranch" value="main"></label><label>Ścieżka pliku<input id="fsPath" value="fenix-sync/projects.json"></label><label>Token GitHub<input id="fsToken" type="password" autocomplete="off" placeholder="Fine-grained token z dostępem Contents"></label><label class="check"><input id="fsRemember" type="checkbox">Zapamiętaj token na tym urządzeniu</label><label class="check"><input id="fsAuto" type="checkbox" checked>Automatycznie utrzymuj projekt w synchronizacji</label><div class="row"><button id="fsSave" class="primary">Zapisz konfigurację</button><button id="fsSync" class="primary">Synchronizuj teraz</button><button id="fsPull">Pobierz</button><button id="fsPush">Wyślij</button></div><div id="fenixSyncStatus">Nie skonfigurowano.</div>`;
  document.body.append(button,panel);const $=id=>document.getElementById(id),status=t=>$("fenixSyncStatus").textContent=t,setBusy=v=>{busy=v;button.dataset.state=v?"busy":"ready";button.textContent=v?"↻ Synchronizacja…":"↻ Fenix Sync"};
  function fill(){const c=FenixSync.getConfig();$("fsOwner").value=c.owner;$("fsRepo").value=c.repo;$("fsBranch").value=c.branch;$("fsPath").value=c.path;$("fsAuto").checked=c.autoSync;$("fsRemember").checked=c.rememberToken;if(c.token)$("fsToken").placeholder="Token ustawiony na tym urządzeniu";status(c.owner&&c.repo?`Gotowy · ${c.owner}/${c.repo}`:"Nie skonfigurowano.")}
  function save(){const old=FenixSync.getConfig(),token=$("fsToken").value||old.token,c=FenixSync.setConfig({owner:$("fsOwner").value,repo:$("fsRepo").value,branch:$("fsBranch").value,path:$("fsPath").value,token,rememberToken:$("fsRemember").checked,autoSync:$("fsAuto").checked});status(`Zapisano · ${c.owner}/${c.repo}`);return c}
  async function execute(kind,{silent=false}={}){if(busy)return null;try{busy=true;setBusy(true);if(!silent)save();if(!silent)status(kind==="sync"?"Synchronizacja…":kind==="pull"?"Pobieranie…":"Wysyłanie…");const out=kind==="sync"?await FenixSync.sync():kind==="pull"?await FenixSync.pull({merge:true}):await FenixSync.push();if(kind!=="push")lastRemoteAt=Date.now();if(!silent)status(kind==="sync"?"✓ Zsynchronizowano projekt.":kind==="pull"?`✓ ${out.found===false?"Brak zdalnego projektu — pierwszy zapis utworzy go automatycznie.":"Pobrano i scalono dane."}`:"✓ Zapisano zmiany w chmurze.");return out}catch(e){status(`Błąd synchronizacji: ${e.message||e}`);return{error:String(e.message||e)}}finally{busy=false;setBusy(false)}}
  function queuePush(){if(!configured()||busy||Date.now()-lastRemoteAt<1800)return;clearTimeout(pushTimer);pushTimer=setTimeout(()=>execute("push",{silent:true}),2200)}
  async function refreshFromRemote(){if(!configured()||busy)return;await execute("sync",{silent:true})}
  button.onclick=()=>{panel.hidden=!panel.hidden;if(!panel.hidden)fill()};$("fsSave").onclick=save;$("fsSync").onclick=()=>execute("sync");$("fsPull").onclick=()=>execute("pull");$("fsPush").onclick=()=>execute("push");
  window.addEventListener("fenix-state-change",queuePush);window.addEventListener("online",refreshFromRemote);document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible")refreshFromRemote()});window.addEventListener("focus",()=>{if(Date.now()-lastRemoteAt>15000)refreshFromRemote()});
  fill();setTimeout(refreshFromRemote,450);
})();