"use strict";
(()=>{
  if(!window.FenixSync||window.__fenixSyncUiReady)return;window.__fenixSyncUiReady=true;
  let busy=false,pushTimer=null,lastRemoteAt=0;
  const configured=()=>{const c=FenixSync.getConfig();return Boolean(c.autoSync&&c.owner&&c.repo&&c.token)};
  const isDashboard=()=>Boolean(document.body.classList.contains("dashboard-v2")||document.getElementById("projects")||document.getElementById("home"));
  const style=document.createElement("style");style.textContent=`
  #fenixSyncCard{display:flex;align-items:center;justify-content:space-between;gap:18px;width:100%;box-sizing:border-box;margin:16px 0 22px;padding:18px 20px;border:1px solid #d8dee7;border-radius:18px;background:linear-gradient(135deg,#fff 0%,#f7fafc 100%);color:#111827;box-shadow:0 8px 24px #0f172a0d;cursor:pointer;text-align:left;font-family:system-ui;transition:.18s ease}
  #fenixSyncCard:hover{transform:translateY(-1px);box-shadow:0 12px 30px #0f172a14;border-color:#b9c4d2}
  #fenixSyncCard:focus-visible{outline:3px solid #f59e0b55;outline-offset:2px}
  .fenix-sync-card-main{display:flex;align-items:center;gap:15px;min-width:0}.fenix-sync-card-icon{display:grid;place-items:center;flex:0 0 48px;width:48px;height:48px;border-radius:14px;background:#111827;color:#fff;font-size:25px;font-weight:900}.fenix-sync-card-copy{min-width:0}.fenix-sync-card-kicker{font-size:11px;font-weight:900;letter-spacing:.12em;color:#7c8796}.fenix-sync-card-copy strong{display:block;margin:2px 0 4px;font-size:19px;line-height:1.15}.fenix-sync-card-copy p{margin:0;color:#596577;font-size:13px;line-height:1.45}.fenix-sync-card-side{display:flex;align-items:center;gap:12px;flex:0 0 auto}.fenix-sync-device{font-size:12px;color:#6b7280;font-weight:700;white-space:nowrap}.fenix-sync-badge{padding:7px 10px;border-radius:999px;background:#eef2f6;color:#374151;font-size:11px;font-weight:900;letter-spacing:.05em;white-space:nowrap}.fenix-sync-badge.ready{background:#e8f7ee;color:#166534}.fenix-sync-badge.busy{background:#fff4dc;color:#92400e}.fenix-sync-badge.error{background:#feecec;color:#991b1b}
  #fenixSyncPanel{box-sizing:border-box;width:100%;margin:-10px 0 24px;padding:18px;background:#fff;color:#111827;border:1px solid #d7dce3;border-radius:16px;box-shadow:0 10px 30px #00000012;font:13px system-ui}#fenixSyncPanel[hidden]{display:none}#fenixSyncPanel h3{margin:0 0 5px;font-size:18px}#fenixSyncPanel p{margin:0 0 12px;color:#5b6572}#fenixSyncPanel label{display:block;font-weight:750;margin:9px 0}#fenixSyncPanel input{display:block;box-sizing:border-box;width:100%;margin-top:4px;padding:10px;border:1px solid #ccd3dc;border-radius:9px;background:#fff;color:#111827}#fenixSyncPanel .row{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}#fenixSyncPanel button{padding:9px 11px;border:1px solid #ccd3dc;border-radius:9px;background:#f5f7f9;color:#111827;font-weight:800}#fenixSyncPanel button.primary{background:#111827;color:#fff;border-color:#111827}#fenixSyncStatus{padding:9px;margin-top:10px;border-radius:9px;background:#f4f6f8;white-space:pre-wrap}#fenixSyncPanel .check{display:flex;align-items:center;gap:7px}#fenixSyncPanel .check input{width:auto;margin:0}
  @media(max-width:760px){#fenixSyncCard{align-items:flex-start;padding:15px;gap:10px}.fenix-sync-card-icon{width:42px;height:42px;flex-basis:42px}.fenix-sync-card-copy strong{font-size:17px}.fenix-sync-card-copy p{font-size:12px}.fenix-sync-card-side{flex-direction:column;align-items:flex-end;gap:5px}.fenix-sync-device{display:none}#fenixSyncPanel{padding:14px}}
  `;document.head.appendChild(style);
  let card=null,panel=null,statusEl=null,badge=null;
  function buildDashboardUi(){if(!isDashboard()||document.getElementById("fenixSyncCard"))return;const anchor=document.querySelector("#projects")||document.querySelector(".project-strip")||document.querySelector("#home .hero")||document.querySelector("main");if(!anchor)return;
    card=document.createElement("button");card.id="fenixSyncCard";card.type="button";card.innerHTML=`<span class="fenix-sync-card-main"><span class="fenix-sync-card-icon">↻</span><span class="fenix-sync-card-copy"><span class="fenix-sync-card-kicker">FENIX CLOUD</span><strong>Fenix Sync</strong><p>Ten sam projekt, strony i assety na Windows, Linux i mobile.</p></span></span><span class="fenix-sync-card-side"><span class="fenix-sync-device">Windows · Linux · Mobile</span><span id="fenixSyncBadge" class="fenix-sync-badge">SPRAWDZAM…</span></span>`;
    panel=document.createElement("section");panel.id="fenixSyncPanel";panel.hidden=true;panel.innerHTML=`<h3>Fenix Sync</h3><p>Synchronizacja wspólnego projektu pomiędzy Twoimi urządzeniami.</p><label>GitHub owner<input id="fsOwner" autocomplete="username"></label><label>Repozytorium danych<input id="fsRepo"></label><label>Branch<input id="fsBranch"></label><label>Ścieżka pliku<input id="fsPath"></label><label>Token GitHub<input id="fsToken" type="password" autocomplete="off" placeholder="Fine-grained token z dostępem Contents"></label><label class="check"><input id="fsRemember" type="checkbox">Zapamiętaj token na tym urządzeniu</label><label class="check"><input id="fsAuto" type="checkbox" checked>Automatycznie utrzymuj projekt w synchronizacji</label><div class="row"><button id="fsSave" class="primary">Zapisz konfigurację</button><button id="fsSync" class="primary">Synchronizuj teraz</button><button id="fsPull">Pobierz</button><button id="fsPush">Wyślij</button></div><div id="fenixSyncStatus">Sprawdzam konfigurację…</div>`;
    anchor.insertAdjacentElement("afterend",panel);anchor.insertAdjacentElement("afterend",card);statusEl=panel.querySelector("#fenixSyncStatus");badge=card.querySelector("#fenixSyncBadge");
    card.onclick=()=>{panel.hidden=!panel.hidden;if(!panel.hidden)fill()};panel.querySelector("#fsSave").onclick=save;panel.querySelector("#fsSync").onclick=()=>execute("sync");panel.querySelector("#fsPull").onclick=()=>execute("pull");panel.querySelector("#fsPush").onclick=()=>execute("push");fill();
  }
  const $=id=>document.getElementById(id),setStatus=t=>{if(statusEl)statusEl.textContent=t};
  function setBadge(text,state=""){if(!badge)return;badge.textContent=text;badge.className=`fenix-sync-badge${state?` ${state}`:""}`}
  function setBusy(v){busy=v;if(v)setBadge("SYNCHRONIZACJA…","busy");else updateBadge()}
  function updateBadge(){const c=FenixSync.getConfig();if(!c.token)setBadge("KONFIGURACJA");else if(c.autoSync)setBadge("GOTOWY","ready");else setBadge("RĘCZNY")}
  function fill(){if(!panel)return;const c=FenixSync.getConfig();$("fsOwner").value=c.owner;$("fsRepo").value=c.repo;$("fsBranch").value=c.branch;$("fsPath").value=c.path;$("fsAuto").checked=c.autoSync;$("fsRemember").checked=c.rememberToken;if(c.token)$("fsToken").placeholder="Token ustawiony na tym urządzeniu";setStatus(c.token?`Gotowy · ${c.owner}/${c.repo}`:"Wymagana jednorazowa konfiguracja tokenu na tym urządzeniu.");updateBadge()}
  function save(){if(!panel)return FenixSync.getConfig();const old=FenixSync.getConfig(),token=$("fsToken").value||old.token,c=FenixSync.setConfig({owner:$("fsOwner").value,repo:$("fsRepo").value,branch:$("fsBranch").value,path:$("fsPath").value,token,rememberToken:$("fsRemember").checked,autoSync:$("fsAuto").checked});setStatus(`Zapisano · ${c.owner}/${c.repo}`);updateBadge();return c}
  async function execute(kind,{silent=false}={}){if(busy)return null;try{busy=true;setBusy(true);if(!silent&&panel)save();if(!silent)setStatus(kind==="sync"?"Synchronizacja…":kind==="pull"?"Pobieranie…":"Wysyłanie…");const out=kind==="sync"?await FenixSync.sync():kind==="pull"?await FenixSync.pull({merge:true}):await FenixSync.push();if(kind!=="push")lastRemoteAt=Date.now();if(!silent)setStatus(kind==="sync"?"✓ Zsynchronizowano projekt.":kind==="pull"?`✓ ${out.found===false?"Brak zdalnego projektu.":"Pobrano i scalono dane."}`:"✓ Zapisano zmiany w chmurze.");setBadge("ZSYNCHRONIZOWANO","ready");return out}catch(e){setStatus(`Błąd synchronizacji: ${e.message||e}`);setBadge("BŁĄD","error");return{error:String(e.message||e)}}finally{busy=false;setTimeout(updateBadge,1800)}}
  function queuePush(){if(!configured()||busy||Date.now()-lastRemoteAt<1800)return;clearTimeout(pushTimer);pushTimer=setTimeout(()=>execute("push",{silent:true}),2200)}
  async function refreshFromRemote(){if(!configured()||busy)return;await execute("sync",{silent:true})}
  buildDashboardUi();window.addEventListener("fenix-state-change",queuePush);window.addEventListener("online",refreshFromRemote);document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible")refreshFromRemote()});window.addEventListener("focus",()=>{if(Date.now()-lastRemoteAt>15000)refreshFromRemote()});setTimeout(refreshFromRemote,450);
})();