"use strict";
(()=>{
  const $=id=>document.getElementById(id),requestedId=new URLSearchParams(location.search).get("id");
  const safe=s=>String(s||"").replace(/[&<>"']/g,"");
  const moduleOf=p=>p?.module||p?.recipe?.module;
  const tracingPages=()=>FenixCore.getCart().filter(p=>moduleOf(p)==="tracing-studio");
  function selectedAsset(){const card=document.querySelector("#assetGrid .asset-card.selected"),img=card?.querySelector("img"),name=$("selectedAssetName")?.textContent||"Brak assetu";return{src:img?.src||"",name}}
  function updateSelectedPanel(){const asset=selectedAsset();if($("selectedAssetPanelName"))$("selectedAssetPanelName").textContent=asset.name;const thumb=$("selectedAssetThumb");if(thumb)thumb.innerHTML=asset.src?`<img src="${asset.src}" alt="">`:"";if($("summaryAsset"))$("summaryAsset").textContent=asset.name;const treatment=$("treatment");if($("summaryTreatment"))$("summaryTreatment").textContent=treatment?.selectedOptions?.[0]?.textContent||"—";const exercise=$("exerciseMode");if($("summaryExercise"))$("summaryExercise").textContent=exercise?.selectedOptions?.[0]?.textContent||"—";if($("summaryPages"))$("summaryPages").textContent=String(tracingPages().length)}
  function pageThumb(page){const ref=page.recipe?.content?.assetRef||page.recipe?.settings?.assetRef,asset=ref?FenixCore.getAsset(ref):null;if(asset?.dataUrl)return`<div class="studio-page-thumb"><img src="${asset.dataUrl}" alt=""></div>`;return'<div class="studio-page-thumb">✎</div>'}
  function renderPages(){const pages=tracingPages(),box=$("studioPagesList");if(!box)return;$("studioPagesCount").textContent=`${pages.length} ${pages.length===1?"strona":"stron"}`;if($("summaryPages"))$("summaryPages").textContent=String(pages.length);if(!pages.length){box.innerHTML='<div class="studio-pages-empty">Nie zapisano jeszcze żadnej strony Tracing.</div>';return}box.innerHTML=pages.map((p,i)=>{const ref=p.recipe?.content?.assetRef||p.recipe?.settings?.assetRef,asset=ref?FenixCore.getAsset(ref):null,mode=p.recipe?.settings?.treatment||"tracing";return`<article class="studio-page${p.id===requestedId?" current":""}">${pageThumb(p)}<div class="studio-page-copy"><strong>Tracing #${String(i+1).padStart(2,"0")} · ${safe(p.title||"Trace the Picture!")}</strong><small>${safe(asset?.name||"Brak assetu")} · ${safe(mode)}${p.id===requestedId?" · EDYCJA":""}</small></div><div class="studio-page-actions"><button type="button" data-edit="${p.id}">Edytuj</button><button type="button" class="delete" data-delete="${p.id}">Usuń</button></div></article>`}).join("");box.querySelectorAll("[data-edit]").forEach(btn=>btn.onclick=()=>{location.href=`${location.pathname}?id=${encodeURIComponent(btn.dataset.edit)}`});box.querySelectorAll("[data-delete]").forEach(btn=>btn.onclick=()=>{const page=FenixCore.getCart().find(p=>p.id===btn.dataset.delete);if(!page)return;if(!confirm(`Usunąć stronę „${page.title||"Tracing"}” z projektu?`))return;FenixCore.removePage(btn.dataset.delete);if(btn.dataset.delete===requestedId){location.href=location.pathname;return}renderPages();updateSelectedPanel()})}
  async function init(){await FenixCore.ready;const newBtn=$("newPage");if(newBtn)newBtn.onclick=()=>{location.href=location.pathname};const cart=$("cart");if(cart&&requestedId)cart.textContent="Zapisz zmiany w projekcie";renderPages();updateSelectedPanel();["treatment","exerciseMode"].forEach(id=>$(id)?.addEventListener("change",updateSelectedPanel));const observer=new MutationObserver(()=>updateSelectedPanel());if($("assetGrid"))observer.observe($("assetGrid"),{subtree:true,childList:true,attributes:true,attributeFilter:["class"]});window.addEventListener("fenix-state-change",()=>{renderPages();updateSelectedPanel()})}
  void init();
})();