"use strict";
(()=>{
  const $=id=>document.getElementById(id),canvas=$("page"),ctx=canvas.getContext("2d");const state={assets:[],selected:null,rendered:null};let timer=null;
  const val=(id,f="")=>$(id)?.value??f,checked=id=>Boolean($(id)?.checked),num=(id,f)=>Number(val(id,f))||f;
  const opts=()=>({scaleX:num("scaleX",80),scaleY:num("scaleY",80),assetX:num("assetX",50),assetY:num("assetY",58),rotation:num("rotation",0),workMargin:num("workMargin",8),flipX:checked("flipX"),flipY:checked("flipY"),showFrame:checked("showFrame"),treatment:val("treatment","trace"),threshold:num("threshold",180),edgeStrength:num("edgeStrength",35),brightness:num("brightness",105),contrast:num("contrast",125),opacity:num("opacity",42),invert:checked("invert"),smooth:checked("smooth"),title:val("title","Trace the Picture!"),instructions:val("instructions","Trace the picture carefully."),titleSize:num("titleSize",112),titleY:num("titleY",230),instructionSize:num("instructionSize",46)});
  function status(t,e=false){$("status").textContent=t;$("status").dataset.type=e?"error":"ok"}
  function assets(){state.assets=FenixCore.listAssets();$("assetCount").textContent=`${state.assets.length} assetów`;$("assetEmpty").hidden=state.assets.length>0;const g=$("assetGrid");g.innerHTML="";state.assets.forEach(a=>{const b=document.createElement("button");b.type="button";b.className=`asset-card${state.selected===a.id?" selected":""}`;b.innerHTML=`<img src="${a.dataUrl}" alt=""><strong>${String(a.name||"Asset").replace(/[&<>]/g,"")}</strong>`;b.onclick=()=>{state.selected=a.id;assets();render()};g.appendChild(b)});if(state.selected&&!state.assets.some(a=>a.id===state.selected))state.selected=null;$("selectedAssetName").textContent=state.assets.find(a=>a.id===state.selected)?.name||"Brak assetu"}
  async function render(){clearTimeout(timer);try{const a=state.assets.find(x=>x.id===state.selected)||null;state.rendered=await FenixTracingCore.render(a,opts());canvas.width=state.rendered.width;canvas.height=state.rendered.height;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(state.rendered,0,0);status(a?"Podgląd gotowy.":"Wybierz asset projektu.",!a)}catch(e){console.error(e);status(e.message||"Błąd renderowania",true)}}
  const schedule=()=>{clearTimeout(timer);timer=setTimeout(render,120)};
  async function importFiles(files){for(const file of files){const dataUrl=await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(new Error("Nie udało się odczytać pliku."));r.readAsDataURL(file)});const img=await FenixTracingCore.loadImage(dataUrl);const a=FenixCore.putAsset({name:file.name,filename:file.name,mime:file.type||"image/png",dataUrl,source:"tracing-studio",width:img.naturalWidth||img.width,height:img.naturalHeight||img.height,tags:["content"]});if(!state.selected)state.selected=a.id}assets();render()}
  function reset(){const d={scaleX:80,scaleY:80,assetX:50,assetY:58,rotation:0,workMargin:8,threshold:180,edgeStrength:35,brightness:105,contrast:125,opacity:42,titleSize:112,titleY:230,instructionSize:46};Object.entries(d).forEach(([k,v])=>{if($(k))$(k).value=v});$("flipX").checked=$("flipY").checked=$("showFrame").checked=$("invert").checked=false;$("smooth").checked=true;$("treatment").value="trace";render()}
  function save(){const a=state.assets.find(x=>x.id===state.selected);if(!a)return status("Najpierw wybierz asset.",true);const o=opts();FenixCore.addPage({module:"tracing-studio",title:o.title,recipe:{module:"tracing-studio",title:o.title,settings:o,content:{assetRef:a.id},meta:{createdWith:"FENIX PC",moduleVersion:2}},preview:{imageData:null},solution:{available:false,imageData:null},source:{app:"fenix-desktop",version:"0.31.0",format:"native"}});status(`Dodano stronę z assetem „${a.name}” do projektu.`)}
  $("importAsset").onclick=()=>$("assetFile").click();$("assetFile").onchange=async()=>{if($("assetFile").files?.length)await importFiles([...$("assetFile").files]);$("assetFile").value=""};$("generate").onclick=render;$("reset").onclick=reset;$("cart").onclick=save;$("png").onclick=()=>{if(state.rendered)FenixCore.downloadCanvas(state.rendered,`tracing-${Date.now()}.png`)};
  ["scaleX","scaleY","assetX","assetY","rotation","workMargin","threshold","edgeStrength","brightness","contrast","opacity","title","instructions","titleSize","titleY","instructionSize"].forEach(id=>$(id)?.addEventListener("input",schedule));["flipX","flipY","showFrame","treatment","invert","smooth"].forEach(id=>$(id)?.addEventListener("change",render));window.addEventListener("fenix-state-change",e=>{if(e.detail?.assets||e.detail?.activeProject){assets();render()}});const p=FenixCore.getActiveProject();$("projectInfo").textContent=`Aktywny projekt: ${p.name} · ${p.format} · ${p.bleed==="bleed"?"ze spadami":"bez spadów"}`;assets();render();
})();