"use strict";
(()=>{
  const $=id=>document.getElementById(id),canvas=$("page"),ctx=canvas.getContext("2d");
  const state={canvas:null,assets:[],selectedAssetId:null,assetImage:null,renderToken:0};
  const instructions={asset:"Trace the picture carefully.",waves:"Trace the waves from left to right.",zigzag:"Trace the zigzags from left to right.",loops:"Trace the loops carefully.",paths:"Follow each path from the dot to the star.",shapes:"Trace each shape carefully.",mixed:"Practice each kind of tracing line."};
  const val=(id,fallback="")=>$(id)?.value??fallback;
  const checked=id=>$(id)?.checked!==false;
  const num=(id,fallback)=>Number(val(id,fallback))||fallback;
  const escapeHtml=value=>String(value??"").replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[ch]));
  function options(){const sourceMode=val("sourceMode","asset"),type=val("type","waves");return{sourceMode,type,title:val("title",sourceMode==="asset"?"Trace the Picture!":"Tracing Practice"),instructions:val("instructions")||instructions[sourceMode==="asset"?"asset":type],seed:val("seed","fenix-tracing-001"),rows:num("rows",7),amplitude:num("amplitude",90),spacing:num("spacing",190),lineWidth:num("lineWidth",8),dashStyle:val("dashStyle","normal"),titleSize:num("titleSize",112),instructionSize:num("instructionSize",46),titleY:num("titleY",230),showTitle:checked("showTitle"),showInstructions:checked("showInstructions"),showGuides:checked("showGuides"),assetScale:num("assetScale",72),assetX:num("assetX",50),assetY:num("assetY",58),assetRotation:num("assetRotation",0),assetOpacity:num("assetOpacity",45),assetFit:val("assetFit","contain"),assetTreatment:val("assetTreatment","trace"),flipX:Boolean($("flipX")?.checked),showAssetFrame:Boolean($("showAssetFrame")?.checked),assetRef:state.selectedAssetId}};
  function setStatus(text,error=false){$("status").textContent=text;$("status").dataset.type=error?"error":"ok"}
  function eligibleAssets(){return FenixCore.listAssets().filter(asset=>asset.dataUrl).sort((a,b)=>String(a.name).localeCompare(String(b.name),"pl"))}
  function renderAssetGrid(){state.assets=eligibleAssets();const grid=$("assetGrid"),empty=$("assetEmpty");grid.innerHTML="";empty.hidden=state.assets.length>0;$("assetCount").textContent=`${state.assets.length} ${state.assets.length===1?"asset":"assetów"}`;if(state.selectedAssetId&&!state.assets.some(asset=>asset.id===state.selectedAssetId)){state.selectedAssetId=null;state.assetImage=null}if(!state.selectedAssetId&&state.assets.length)state.selectedAssetId=state.assets[0].id;state.assets.forEach(asset=>{const selected=asset.id===state.selectedAssetId,button=document.createElement("button");button.type="button";button.className=`asset-card${selected?" selected":""}`;button.innerHTML=`<span class="asset-check">${selected?"✓":""}</span><img src="${asset.dataUrl}" alt="${escapeHtml(asset.name)}"><strong>${escapeHtml(asset.name)}</strong><small>${String(asset.mime||"").includes("svg")?"SVG":"PNG / bitmap"}</small>`;button.onclick=async()=>{state.selectedAssetId=asset.id;state.assetImage=null;renderAssetGrid();await render()};grid.appendChild(button)});const selected=state.assets.find(asset=>asset.id===state.selectedAssetId);$("selectedAssetName").textContent=selected?selected.name:"Brak wybranego assetu"}
  async function currentAssetImage(){if(val("sourceMode","asset")!=="asset")return null;const asset=state.assets.find(item=>item.id===state.selectedAssetId);if(!asset)return null;if(state.assetImage&&state.assetImage.__fenixAssetId===asset.id)return state.assetImage;const image=await FenixTracingCore.loadImage(asset.dataUrl);image.__fenixAssetId=asset.id;state.assetImage=image;return image}
  async function render(){const token=++state.renderToken,o=options();try{const image=await currentAssetImage();if(token!==state.renderToken)return;if(o.sourceMode==="asset"&&!image){state.canvas=FenixTracingCore.render(o,null);setStatus("Wybierz lub dodaj asset projektu.",true)}else{state.canvas=FenixTracingCore.render(o,image);setStatus(o.sourceMode==="asset"?"Podgląd assetu gotowy.":"Podgląd ćwiczenia linii gotowy.")}canvas.width=state.canvas.width;canvas.height=state.canvas.height;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(state.canvas,0,0);syncModeUI()}catch(error){console.error(error);setStatus(error.message||"Nie udało się przygotować podglądu.",true)}}
  function syncModeUI(){const assetMode=val("sourceMode","asset")==="asset";$("assetSettings").hidden=!assetMode;$("lineSettings").hidden=assetMode;$("selectedAssetName").hidden=!assetMode}
  function save(){const o=options(),project=FenixCore.getActiveProject();if(o.sourceMode==="asset"&&!o.assetRef)return setStatus("Wybierz asset przed dodaniem strony do projektu.",true);FenixCore.addPage({module:"tracing-studio",title:o.title,seed:o.seed,recipe:{module:"tracing-studio",seed:o.seed,title:o.title,settings:o,content:o.assetRef?{assetRef:o.assetRef}:{}},preview:{imageData:null},solution:{available:false,imageData:null},source:{app:"fenix-desktop",version:"0.30.0",format:"native"}});setStatus(`Dodano stronę do projektu „${project.name}”.`)}
  function fileToDataUrl(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result||""));reader.onerror=()=>reject(new Error(`Nie udało się odczytać ${file.name}.`));reader.readAsDataURL(file)})}
  async function imageSize(dataUrl){try{const image=await FenixTracingCore.loadImage(dataUrl);return{width:image.naturalWidth||image.width||0,height:image.naturalHeight||image.height||0}}catch{return{width:0,height:0}}}
  async function importFiles(files){const list=[...files];if(!list.length)return;setStatus(`Dodaję ${list.length} assetów do projektu…`);for(const file of list){const dataUrl=await fileToDataUrl(file),size=await imageSize(dataUrl);FenixCore.putAsset({name:file.name.replace(/\.[^.]+$/,""),filename:file.name,mime:file.type||"image/png",dataUrl,source:"tracing-studio",width:size.width,height:size.height,sizeBytes:file.size,tags:["content"],validation:{status:"warning",messages:["Asset dodany w Tracing Studio; pełna walidacja B&W dostępna w Assetach projektu."],metrics:{}}})}state.assetImage=null;renderAssetGrid();await render();setStatus(`Dodano ${list.length} ${list.length===1?"asset":"assetów"} do aktywnego projektu.`)}
  $("generate").onclick=render;$("randomSeed").onclick=()=>{$("seed").value=`fenix-tracing-${Date.now().toString(36)}`;render()};$("png").onclick=()=>{if(!state.canvas)return;FenixCore.downloadCanvas(state.canvas,`tracing-${val("seed")}.png`)};$("cart").onclick=save;$("importAsset").onclick=()=>$("assetFile").click();$("assetFile").onchange=async()=>{try{await importFiles($("assetFile").files)}catch(error){console.error(error);setStatus(error.message,true)}finally{$("assetFile").value=""}};
  ["sourceMode","type","rows","amplitude","spacing","lineWidth","dashStyle","titleSize","instructionSize","titleY","assetScale","assetX","assetY","assetRotation","assetOpacity","assetFit","assetTreatment"].forEach(id=>$(id)?.addEventListener("change",render));["title","instructions","seed"].forEach(id=>$(id)?.addEventListener("input",render));["showTitle","showInstructions","showGuides","flipX","showAssetFrame"].forEach(id=>$(id)?.addEventListener("change",render));
  window.addEventListener("fenix-state-change",event=>{if(event.detail?.assets||event.detail?.activeProject){state.assetImage=null;renderAssetGrid();const p=FenixCore.getActiveProject();$("projectInfo").textContent=`Aktywny projekt: ${p.name} · ${p.format} · ${p.bleed==="bleed"?"ze spadami":"bez spadów"}`;render()}});
  const p=FenixCore.getActiveProject();$("projectInfo").textContent=`Aktywny projekt: ${p.name} · ${p.format} · ${p.bleed==="bleed"?"ze spadami":"bez spadów"}`;renderAssetGrid();syncModeUI();render();
})();