"use strict";
window.FenixTracingCore=(()=>{
  const W=2550,H=3300;
  const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
  const makeCanvas=(w=W,h=H)=>{const c=document.createElement("canvas");c.width=w;c.height=h;return c};
  const loadImage=dataUrl=>new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(new Error("Nie udało się wczytać assetu."));img.src=dataUrl});
  const isSvgAsset=asset=>String(asset?.mime||"").includes("svg")||String(asset?.dataUrl||"").startsWith("data:image/svg+xml");
  function renderBase(ctx,o){ctx.fillStyle="#fff";ctx.fillRect(0,0,W,H);ctx.fillStyle="#111";ctx.textAlign="center";ctx.font=`700 ${o.titleSize||112}px Arial`;ctx.fillText(o.title||"Trace the Picture!",W/2,o.titleY||230);ctx.font=`${o.instructionSize||46}px Arial`;ctx.fillText(o.instructions||"Trace the picture carefully.",W/2,(o.titleY||230)+110)}
  function preparedImage(img,o){const maxSide=1200,ratio=Math.min(1,maxSide/Math.max(img.naturalWidth||img.width,img.naturalHeight||img.height)),w=Math.max(1,Math.round((img.naturalWidth||img.width)*ratio)),h=Math.max(1,Math.round((img.naturalHeight||img.height)*ratio)),c=makeCanvas(w,h),x=c.getContext("2d");x.imageSmoothingEnabled=o.smooth!==false;x.drawImage(img,0,0,w,h);return c}
  function grayscaleData(canvas,o){const x=canvas.getContext("2d"),d=x.getImageData(0,0,canvas.width,canvas.height),p=d.data,bright=(Number(o.brightness)||100)/100,contrast=(Number(o.contrast)||100)/100;for(let i=0;i<p.length;i+=4){const a=p[i+3]/255;let g=.299*p[i]+.587*p[i+1]+.114*p[i+2];g=g*a+255*(1-a);g=(g-128)*contrast+128;g*=bright;g=clamp(g,0,255);if(o.invert)g=255-g;p[i]=p[i+1]=p[i+2]=g;p[i+3]=255}return d}
  function renderRasterDots(base,o){const w=base.width,h=base.height,d=grayscaleData(base,o),p=d.data,thr=Number(o.threshold)||180,strength=Number(o.edgeStrength)||35,spacing=clamp(Number(o.dotSpacing)||22,6,80),radius=clamp(Number(o.dotSize)||8,2,30)/2,alpha=clamp(Number(o.dotOpacity)||70,10,100)/100,out=makeCanvas(w,h),x=out.getContext("2d");
    const gray=(xx,yy)=>p[(yy*w+xx)*4],isEdge=(xx,yy)=>{if(xx<=0||yy<=0||xx>=w-1||yy>=h-1)return false;const g=gray(xx,yy),l=gray(xx-1,yy),r=gray(xx+1,yy),u=gray(xx,yy-1),b=gray(xx,yy+1),binary=g<thr,neighborChange=(l<thr)!==binary||(r<thr)!==binary||(u<thr)!==binary||(b<thr)!==binary,gradient=Math.abs(r-l)+Math.abs(b-u);return neighborChange||gradient>strength};
    x.fillStyle=`rgba(0,0,0,${alpha})`;const search=Math.max(2,Math.floor(spacing/2));for(let gy=search;gy<h-search;gy+=spacing){for(let gx=search;gx<w-search;gx+=spacing){let found=null,best=Infinity;for(let yy=gy-search;yy<=gy+search;yy+=2){for(let xx=gx-search;xx<=gx+search;xx+=2){if(!isEdge(xx,yy))continue;const dist=(xx-gx)*(xx-gx)+(yy-gy)*(yy-gy);if(dist<best){best=dist;found={x:xx,y:yy}}}}if(found){x.beginPath();x.arc(found.x,found.y,radius,0,Math.PI*2);x.fill()}}}return out}
  function decodeSvg(dataUrl){const comma=dataUrl.indexOf(",");if(comma<0)throw new Error("Nieprawidłowy SVG.");const meta=dataUrl.slice(0,comma),body=dataUrl.slice(comma+1);if(/;base64/i.test(meta)){const binary=atob(body),bytes=Uint8Array.from(binary,ch=>ch.charCodeAt(0));return new TextDecoder("utf-8").decode(bytes)}return decodeURIComponent(body.replace(/\+/g,"%20"))}
  async function renderVectorDots(asset,o){const svgText=decodeSvg(asset.dataUrl),doc=new DOMParser().parseFromString(svgText,"image/svg+xml");if(doc.querySelector("parsererror"))throw new Error("Nie udało się odczytać geometrii SVG.");const root=doc.documentElement;root.querySelectorAll("script,foreignObject").forEach(el=>el.remove());let vb=[0,0,Number(asset.width)||1024,Number(asset.height)||1024];const rawVb=(root.getAttribute("viewBox")||"").trim().split(/[\s,]+/).map(Number);if(rawVb.length===4&&rawVb.every(Number.isFinite)&&rawVb[2]>0&&rawVb[3]>0)vb=rawVb;else root.setAttribute("viewBox",vb.join(" "));const maxSide=1200,scale=Math.min(1,maxSide/Math.max(vb[2],vb[3])),outW=Math.max(1,Math.round(vb[2]*scale)),outH=Math.max(1,Math.round(vb[3]*scale)),unitPerPx=vb[2]/outW,dotSize=clamp(Number(o.dotSize)||8,2,30)*unitPerPx,dotSpacing=clamp(Number(o.dotSpacing)||22,6,80)*unitPerPx,alpha=clamp(Number(o.dotOpacity)||70,10,100)/100,dash=Math.max(dotSize*.02,unitPerPx*.05),gap=Math.max(dotSpacing-dotSize,dotSize*.35);root.setAttribute("width",String(outW));root.setAttribute("height",String(outH));root.setAttribute("preserveAspectRatio","xMidYMid meet");const geometry=[...root.querySelectorAll("path,rect,circle,ellipse,line,polyline,polygon")];if(!geometry.length)throw new Error("Ten SVG nie zawiera obsługiwanych ścieżek wektorowych.");for(const el of geometry){const previous=el.getAttribute("style")||"";el.setAttribute("style",`${previous};fill:none!important;stroke:rgba(0,0,0,${alpha})!important;stroke-width:${dotSize}!important;stroke-linecap:round!important;stroke-linejoin:round!important;stroke-dasharray:${dash} ${gap}!important;stroke-dashoffset:0!important;vector-effect:non-scaling-stroke;`)}root.querySelectorAll("image,text").forEach(el=>el.setAttribute("display","none"));const serialized=new XMLSerializer().serializeToString(root),url=`data:image/svg+xml;charset=utf-8,${encodeURIComponent(serialized)}`,img=await loadImage(url),out=makeCanvas(outW,outH),ctx=out.getContext("2d");ctx.clearRect(0,0,outW,outH);ctx.drawImage(img,0,0,outW,outH);return out}
  async function processImage(asset,img,o){const c=preparedImage(img,o);if(o.treatment==="original")return c;if(o.treatment==="dots")return isSvgAsset(asset)?renderVectorDots(asset,o):renderRasterDots(c,o);const x=c.getContext("2d"),d=grayscaleData(c,o),p=d.data,thr=Number(o.threshold)||180;if(o.treatment==="bw"||o.treatment==="outline")for(let i=0;i<p.length;i+=4){const g=p[i]<thr?0:255;p[i]=p[i+1]=p[i+2]=g}x.putImageData(d,0,0);if(o.treatment==="outline"){const src=x.getImageData(0,0,c.width,c.height),out=x.createImageData(c.width,c.height),s=src.data,t=out.data,strength=Number(o.edgeStrength)||35;for(let yy=1;yy<c.height-1;yy++)for(let xx=1;xx<c.width-1;xx++){const k=(yy*c.width+xx)*4,l=(yy*c.width+xx-1)*4,r=(yy*c.width+xx+1)*4,u=((yy-1)*c.width+xx)*4,b=((yy+1)*c.width+xx)*4;const edge=Math.abs(s[r]-s[l])+Math.abs(s[b]-s[u])>strength?0:255;t[k]=t[k+1]=t[k+2]=edge;t[k+3]=255}x.putImageData(out,0,0)}return c}
  async function render(asset,o={}){const out=makeCanvas(),ctx=out.getContext("2d");renderBase(ctx,o);if(!asset)return out;const img=await loadImage(asset.dataUrl),processed=await processImage(asset,img,o),margin=clamp(Number(o.workMargin)||8,0,30)/100,area={x:W*margin,y:520+H*margin*.25,w:W*(1-margin*2),h:H-650-H*margin*.5},sx=(Number(o.scaleX)||80)/100,sy=(Number(o.scaleY)||80)/100,fit=Math.min(area.w/processed.width,area.h/processed.height),dw=processed.width*fit*sx,dh=processed.height*fit*sy,cx=W*clamp(Number(o.assetX)||50,5,95)/100,cy=H*clamp(Number(o.assetY)||58,20,90)/100;ctx.save();ctx.translate(cx,cy);ctx.rotate((Number(o.rotation)||0)*Math.PI/180);ctx.scale(o.flipX?-1:1,o.flipY?-1:1);ctx.globalAlpha=o.treatment==="dots"?1:clamp(Number(o.opacity)||42,5,100)/100;ctx.imageSmoothingEnabled=o.smooth!==false;ctx.drawImage(processed,-dw/2,-dh/2,dw,dh);ctx.restore();if(o.showFrame){ctx.save();ctx.strokeStyle="#a8b3bf";ctx.setLineDash([20,15]);ctx.lineWidth=4;ctx.strokeRect(area.x,area.y,area.w,area.h);ctx.restore()}return out}
  return Object.freeze({WIDTH:W,HEIGHT:H,loadImage,render});
})();