"use strict";
window.FenixTracingCore=(()=>{
  const W=2550,H=3300;
  const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
  const makeCanvas=(w=W,h=H)=>{const c=document.createElement("canvas");c.width=w;c.height=h;return c};
  const loadImage=dataUrl=>new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(new Error("Nie udało się wczytać assetu."));img.src=dataUrl});
  function base(ctx,o){ctx.fillStyle="#fff";ctx.fillRect(0,0,W,H);ctx.fillStyle="#111";ctx.textAlign="center";ctx.font=`700 ${o.titleSize||112}px Arial`;ctx.fillText(o.title||"Trace the Picture!",W/2,o.titleY||230);ctx.font=`${o.instructionSize||46}px Arial`;ctx.fillText(o.instructions||"Trace the picture carefully.",W/2,(o.titleY||230)+110)}
  function processImage(img,o){const maxSide=1000,ratio=Math.min(1,maxSide/Math.max(img.naturalWidth||img.width,img.naturalHeight||img.height)),w=Math.max(1,Math.round((img.naturalWidth||img.width)*ratio)),h=Math.max(1,Math.round((img.naturalHeight||img.height)*ratio)),c=makeCanvas(w,h),x=c.getContext("2d");x.imageSmoothingEnabled=o.smooth!==false;x.drawImage(img,0,0,w,h);if(o.treatment==="original")return c;const d=x.getImageData(0,0,w,h),p=d.data,bright=(Number(o.brightness)||100)/100,contrast=(Number(o.contrast)||100)/100,thr=Number(o.threshold)||180;for(let i=0;i<p.length;i+=4){let g=(.299*p[i]+.587*p[i+1]+.114*p[i+2]);g=(g-128)*contrast+128;g*=bright;g=clamp(g,0,255);if(o.treatment==="bw"||o.treatment==="outline")g=g<thr?0:255;if(o.invert)g=255-g;p[i]=p[i+1]=p[i+2]=g}x.putImageData(d,0,0);if(o.treatment==="outline"){const src=x.getImageData(0,0,w,h),out=x.createImageData(w,h),s=src.data,t=out.data,strength=Number(o.edgeStrength)||35;for(let yy=1;yy<h-1;yy++)for(let xx=1;xx<w-1;xx++){const k=(yy*w+xx)*4,l=(yy*w+xx-1)*4,r=(yy*w+xx+1)*4,u=((yy-1)*w+xx)*4,b=((yy+1)*w+xx)*4;const gx=Math.abs(s[r]-s[l]),gy=Math.abs(s[b]-s[u]),edge=gx+gy>strength?0:255;t[k]=t[k+1]=t[k+2]=edge;t[k+3]=s[k+3]}x.putImageData(out,0,0)}return c}
  async function render(asset,o={}){const out=makeCanvas(),ctx=out.getContext("2d");base(ctx,o);if(!asset)return out;const img=await loadImage(asset.dataUrl),processed=processImage(img,o),margin=clamp(Number(o.workMargin)||8,0,30)/100,area={x:W*margin,y:520+H*margin*.35,w:W*(1-margin*2),h:H-650-H*margin*.7},sx=(Number(o.scaleX)||80)/100,sy=(Number(o.scaleY)||80)/100,fit=Math.min(area.w/processed.width,area.h/processed.height),dw=processed.width*fit*sx,dh=processed.height*fit*sy,cx=W*clamp(Number(o.assetX)||50,5,95)/100,cy=H*clamp(Number(o.assetY)||58,20,90)/100;ctx.save();ctx.translate(cx,cy);ctx.rotate((Number(o.rotation)||0)*Math.PI/180);ctx.scale(o.flipX?-1:1,o.flipY?-1:1);ctx.globalAlpha=clamp(Number(o.opacity)||42,5,100)/100;ctx.imageSmoothingEnabled=o.smooth!==false;ctx.drawImage(processed,-dw/2,-dh/2,dw,dh);ctx.restore();if(o.showFrame){ctx.save();ctx.strokeStyle="#a8b3bf";ctx.setLineDash([20,15]);ctx.lineWidth=4;ctx.strokeRect(area.x,area.y,area.w,area.h);ctx.restore()}return out}
  return Object.freeze({WIDTH:W,HEIGHT:H,loadImage,render});
})();