"use strict";
(()=>{
 const $=id=>document.getElementById(id),canvas=$("page"),status=$("status"),select=$("pageSelect"),save=$("saveCart"),deco=$("decoAssetChoices");
 const ids=["title","subtitle","instruction","titleSize","titleY","subtitleSize","instructionSize","ageProfile","difficulty","cols","rows","wordCount","maxWordLength","seed","words","gridFontSize","wordListTitleSize","wordListSize","decoCount","decoScale","sideMargin","topMargin","bottomMargin","wordListPosition","solution"],f=Object.fromEntries(ids.map(id=>[id,$(id)]));
 const presets={"4-6":{easy:[9,9,6,7,["right","down"]],medium:[10,10,7,8,["right","down","diagDown"]],hard:[12,12,8,9,["right","down","diagDown","diagUp"]]},"5-7":{easy:[10,10,7,8,["right","down","diagDown"]],medium:[12,12,9,10,["right","down","diagDown","diagUp"]],hard:[14,14,11,11,["right","down","diagDown","diagUp","left"]]},"6-8":{easy:[12,12,8,10,["right","down","diagDown","diagUp"]],medium:[14,14,11,12,["right","down","diagDown","diagUp","left"]],hard:[16,16,14,14,["right","down","diagDown","diagUp","left","up","diagBackDown","diagBackUp"]]}};
 let currentId=null,directions=["right","down"],timer=null;
 const checkedDeco=()=>deco?[...deco.querySelectorAll('input:checked')]:[];
 const n=(id,d)=>Number(f[id]?.value)||d;
 const words=()=>FenixWordSearch.normalizeWords(f.words.value);
 const libraryRefOf=asset=>String(asset?.libraryRef||asset?.meta?.libraryRef||"").trim();
 const selectedDeco=()=>checkedDeco().map(x=>x.value).filter(Boolean);
 const selectedDecoLibraries=()=>[...new Set(checkedDeco().map(x=>String(x.dataset.libraryId||libraryRefOf(FenixCore.getAsset?.(x.value))||"").trim()).filter(Boolean))];
 function settings(){return{ageProfile:f.ageProfile.value,difficulty:f.difficulty.value,cols:n("cols",9),rows:n("rows",9),wordCount:n("wordCount",6),maxWordLength:n("maxWordLength",7),directions:directions.slice(),typographyVersion:2,titleSize:n("titleSize",112),titleY:n("titleY",230),subtitle:f.subtitle.value,instruction:f.instruction.value,subtitleSize:n("subtitleSize",48),instructionSize:n("instructionSize",46),gridFontSize:n("gridFontSize",54),wordListTitleSize:n("wordListTitleSize",42),wordListSize:n("wordListSize",52),decoAssetRefs:selectedDeco(),decoLibraryRefs:selectedDecoLibraries(),decoCount:n("decoCount",0),decoScale:n("decoScale",80),sideMargin:n("sideMargin",110),topMargin:n("topMargin",330),bottomMargin:n("bottomMargin",190),wordListPosition:f.wordListPosition.value,showSolution:f.solution.value==="yes"}}
 function draft(){const s=settings(),list=words(),seed=n("seed",1),title=f.title.value.trim()||"Find the Words!";return{module:"word-search-studio",title,seed,recipe:{module:"word-search-studio",seed,title,settings:s,content:{words:list}},content:{words:list},solution:{available:true,imageData:null},source:{app:"fenix-mobile",version:"0.27.9",format:"native"}}}
 function announcePageState(pageId,settings){window.dispatchEvent(new CustomEvent("fenix-word-search-page-loaded",{detail:{pageId:pageId||"",settings:settings||{}}}))}
 function refreshDeco(saved={}){
  if(!deco)return;
  const selectedLocal=new Set(Array.isArray(saved.decoAssetRefs)?saved.decoAssetRefs:selectedDeco());
  const selectedLibrary=new Set(Array.isArray(saved.decoLibraryRefs)?saved.decoLibraryRefs:selectedDecoLibraries());
  const base=FenixCore.findAssets({tag:"deco"})||[];
  const byId=new Map(base.map(a=>[a.id,a]));
  selectedLocal.forEach(id=>{const a=FenixCore.getAsset?.(id);if(a)byId.set(a.id,a)});
  (FenixCore.listAssets?.()||[]).forEach(a=>{const ref=libraryRefOf(a);if(ref&&selectedLibrary.has(ref))byId.set(a.id,a)});
  const assets=[...byId.values()];
  deco.innerHTML=assets.length?assets.map(a=>{
   const libraryId=libraryRefOf(a);
   const checked=selectedLocal.has(a.id)||(libraryId&&selectedLibrary.has(libraryId));
   return`<label class="deco-choice"><input type="checkbox" value="${a.id}"${libraryId?` data-library-id="${libraryId}"`:""} ${checked?"checked":""}><span><strong>${a.name}</strong><small>${a.validation?.status==="ok"?"✓ B&W OK":"! sprawdź B&W"}</small></span></label>`;
  }).join(""):'<div class="asset-empty">Brak assetów Deco w projekcie.</div>';
  deco.querySelectorAll("input").forEach(x=>x.onchange=draw);
 }
 async function draw(){const page=draft(),assets=await FenixWordSearch.prepareAssets(page),result=FenixWordSearch.render(page,{solution:page.recipe.settings.showSolution,width:2550,height:3300,canvas,assetImages:assets});status.textContent=`Gotowy · ${result.cols}×${result.rows} · seed ${page.recipe.seed} · słowa ${result.placements.length}/${result.words.length}`;$("wordStats").textContent=`${words().length} słów · używane do ${f.wordCount.value}`;$("wordWarning").textContent=result.unplaced.length?`Nie umieszczono: ${result.unplaced.join(", ")}`:"Wszystkie słowa mieszczą się w ustawieniach."}
 function schedule(){clearTimeout(timer);timer=setTimeout(draw,120)}
 function applyPreset(){const p=presets[f.ageProfile.value]?.[f.difficulty.value];if(!p)return;[f.cols.value,f.rows.value,f.wordCount.value,f.maxWordLength.value,directions]=[p[0],p[1],p[2],p[3],p[4].slice()];$("difficultyInfo").textContent=`Profil ${f.ageProfile.value} lat · siatka ${p[0]}×${p[1]} · ${p[2]} słów · maks. ${p[3]} znaków.`;draw()}
 function pages(){return FenixCore.getCart().map(FenixPageSchema.normalize).filter(p=>p.module==="word-search-studio")}
 function refill(preferredId=currentId){const ps=pages();select.innerHTML='<option value="">Nowa strona</option>'+ps.map((p,i)=>`<option value="${p.id}">WS #${String(i+1).padStart(2,"0")} · ${p.title}</option>`).join("");const requested=new URLSearchParams(location.search).get("id"),id=preferredId&&ps.some(p=>p.id===preferredId)?preferredId:requested&&ps.some(p=>p.id===requested)?requested:null;load(id)}
 function load(id){currentId=id||null;const p=currentId?FenixCore.getCart().find(x=>x.id===currentId):null;if(!p){select.value="";f.seed.value="1";f.difficulty.value="easy";refreshDeco();announcePageState("",{});applyPreset();save.textContent="Dodaj do Stron projektu";return}const x=FenixPageSchema.normalize(p),s=x.recipe.settings||{};select.value=currentId;f.title.value=x.title||"Find the Words!";f.subtitle.value=s.subtitle||"";f.instruction.value=s.instruction||"Find and circle the hidden words.";["titleSize","titleY","subtitleSize","instructionSize","ageProfile","difficulty","cols","rows","wordCount","maxWordLength","gridFontSize","wordListTitleSize","wordListSize","decoCount","decoScale","sideMargin","topMargin","bottomMargin","wordListPosition"].forEach(k=>{if(f[k]&&s[k]!=null)f[k].value=s[k]});if(Number(s.typographyVersion)!==2){f.titleSize.value=Math.round(Math.max(72,Math.min(160,(Number(s.titleSize)||42)*8/3)));f.titleY.value=Math.round(Math.max(140,Math.min(420,(Number(s.titleY)||82)*8/3)))}f.seed.value=String(x.recipe.seed??x.seed??1);f.words.value=(x.recipe.content?.words||x.content?.words||[]).join("\n");f.solution.value=s.showSolution?"yes":"no";directions=Array.isArray(s.directions)&&s.directions.length?s.directions.slice():directions;refreshDeco(s);announcePageState(currentId,s);save.textContent="Zapisz zmiany w Stronach projektu";draw()}
 function savePage(copy=false){const data=FenixPageSchema.normalize(draft());if(currentId&&!copy)FenixCore.updatePage(currentId,data);else{FenixCore.addPage(data);currentId=FenixCore.getCart().at(-1)?.id||null}refill(currentId)}
 ids.forEach(id=>f[id]?.addEventListener("input",schedule));f.ageProfile.onchange=applyPreset;f.difficulty.onchange=()=>f.difficulty.value==="custom"?draw():applyPreset;select.onchange=()=>load(select.value||null);$("newVariant").onclick=()=>{f.seed.value=String(n("seed",1)+1);currentId=null;select.value="";announcePageState("",{});save.textContent="Dodaj do Stron projektu";draw()};save.onclick=()=>savePage(false);$("saveCopy").onclick=()=>savePage(true);window.addEventListener("fenix-state-change",e=>{if(e.detail?.cart||e.detail?.activeProject)refill(currentId)});refill();
})();