"use strict";
window.FenixDotCore=(()=>{
 const W=2550,H=3300,clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),makeCanvas=(w=W,h=H)=>{const c=document.createElement('canvas');c.width=w;c.height=h;return c};
 const loadImage=src=>new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=()=>rej(new Error('Nie udało się wczytać SVG.'));i.src=src});
 const isSvg=a=>String(a?.mime||'').includes('svg')||String(a?.dataUrl||'').startsWith('data:image/svg+xml');
 const profiles={detail:{dilate:1,smooth:1},balanced:{dilate:2,smooth:4},simple:{dilate:4,smooth:9}};
 async function rasterMask(asset,o){if(!isSvg(asset))throw new Error('Dot to Dot pracuje teraz na assetach SVG.');const img=await loadImage(asset.dataUrl),s=900,c=makeCanvas(s,s),x=c.getContext('2d');x.clearRect(0,0,s,s);const iw=img.naturalWidth||s,ih=img.naturalHeight||s,fit=Math.min(s/iw,s/ih)*.88,dw=iw*fit,dh=ih*fit;x.drawImage(img,(s-dw)/2,(s-dh)/2,dw,dh);const data=x.getImageData(0,0,s,s).data,ink=new Uint8Array(s*s);for(let i=0;i<ink.length;i++){const k=i*4,a=data[k+3],lum=(data[k]+data[k+1]+data[k+2])/3;if(a>16&&lum<248)ink[i]=1}const p=profiles[o.contourProfile]||profiles.balanced;let work=ink;for(let pass=0;pass<p.dilate;pass++){const next=work.slice();for(let y=1;y<s-1;y++)for(let xx=1;xx<s-1;xx++){const i=y*s+xx;if(work[i])continue;if(work[i-1]||work[i+1]||work[i-s]||work[i+s]||work[i-s-1]||work[i-s+1]||work[i+s-1]||work[i+s+1])next[i]=1}work=next}const outside=new Uint8Array(s*s),qx=new Int32Array(s*s),qy=new Int32Array(s*s);let head=0,tail=0;const push=(xx,yy)=>{if(xx<0||yy<0||xx>=s||yy>=s)return;const i=yy*s+xx;if(work[i]||outside[i])return;outside[i]=1;qx[tail]=xx;qy[tail]=yy;tail++};for(let xx=0;xx<s;xx++){push(xx,0);push(xx,s-1)}for(let yy=0;yy<s;yy++){push(0,yy);push(s-1,yy)}while(head<tail){const xx=qx[head],yy=qy[head++];push(xx-1,yy);push(xx+1,yy);push(xx,yy-1);push(xx,yy+1)}const solid=new Uint8Array(s*s);for(let i=0;i<solid.length;i++)if(work[i]||!outside[i])solid[i]=1;return{solid,s}}
 function largestComponent(m){const {solid,s}=m,seen=new Uint8Array(s*s),queue=new Int32Array(s*s);let best=[];for(let i=0;i<solid.length;i++){if(!solid[i]||seen[i])continue;let h=0,t=0;queue[t++]=i;seen[i]=1;const comp=[];while(h<t){const cur=queue[h++];comp.push(cur);const x=cur%s;const ns=[cur-1,cur+1,cur-s,cur+s];for(const n of ns){if(n<0||n>=solid.length||seen[n]||!solid[n])continue;const nx=n%s;if(Math.abs(nx-x)>1)continue;seen[n]=1;queue[t++]=n}}if(comp.length>best.length)best=comp}if(!best.length)throw new Error('Nie udało się znaleźć głównego kształtu SVG.');const mask=new Uint8Array(s*s);for(const i of best)mask[i]=1;return{mask,s}}
 const dirs=[[1,0],[1,1],[0,1],[-1,1],[-1,0],[-1,-1],[0,-1],[1,-1]];function dirIndex(dx,dy){return dirs.findIndex(d=>d[0]===dx&&d[1]===dy)}
 function traceOuter(m){const {mask,s}=m;let start=null;for(let y=1;y<s-1&&!start;y++)for(let x=1;x<s-1;x++){const i=y*s+x;if(mask[i]&&!mask[i-s]){start={x,y};break}}if(!start)throw new Error('Nie udało się znaleźć zewnętrznej krawędzi.');let cur=start,back={x:start.x-1,y:start.y},firstNext=null;const path=[{...start}],limit=s*s*3;for(let step=0;step<limit;step++){let bi=dirIndex(back.x-cur.x,back.y-cur.y);if(bi<0)bi=4;let found=null,newBack=null;for(let k=1;k<=8;k++){const di=(bi+k)%8,nx=cur.x+dirs[di][0],ny=cur.y+dirs[di][1];if(nx<0||ny<0||nx>=s||ny>=s)continue;if(mask[ny*s+nx]){found={x:nx,y:ny};const pi=(di+7)%8;newBack={x:cur.x+dirs[pi][0],y:cur.y+dirs[pi][1]};break}}if(!found)break;if(!firstNext)firstNext={...found};else if(cur.x===start.x&&cur.y===start.y&&found.x===firstNext.x&&found.y===firstNext.y)break;back=newBack;cur=found;path.push({...cur});if(path.length>12&&cur.x===start.x&&cur.y===start.y)break}if(path.length<20)throw new Error('Kontur SVG jest zbyt krótki lub nieciągły.');return path}
 function smooth(path,windowSize){if(windowSize<=1)return path;const n=path.length,out=[];for(let i=0;i<n;i++){let sx=0,sy=0,c=0;for(let k=-windowSize;k<=windowSize;k++){const p=path[(i+k+n)%n];sx+=p.x;sy+=p.y;c++}out.push({x:sx/c,y:sy/c})}return out}
 function arcSample(path,count){const n=path.length,dist=[0];let total=0;for(let i=1;i<=n;i++){const a=path[i-1],b=path[i%n];total+=Math.hypot(b.x-a.x,b.y-a.y);dist.push(total)}const out=[];for(let j=0;j<count;j++){const target=total*j/count;let i=1;while(i<dist.length&&dist[i]<target)i++;const a=path[(i-1)%n],b=path[i%n],span=Math.max(.0001,dist[i]-dist[i-1]),t=(target-dist[i-1])/span;out.push({x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t})}return out}
 function curvature(path,i,step){const n=path.length,a=path[(i-step+n)%n],b=path[i],c=path[(i+step)%n],v1x=b.x-a.x,v1y=b.y-a.y,v2x=c.x-b.x,v2y=c.y-b.y,l1=Math.hypot(v1x,v1y)||1,l2=Math.hypot(v2x,v2y)||1,dot=clamp((v1x*v2x+v1y*v2y)/(l1*l2),-1,1);return Math.acos(dot)/Math.PI}
 function adaptiveSample(path,count,sensitivity){const n=path.length,step=Math.max(3,Math.round(n/260)),weights=new Float64Array(n),cum=[0];let total=0;for(let i=0;i<n;i++){const a=path[i],b=path[(i+1)%n],len=Math.hypot(b.x-a.x,b.y-a.y),k=(curvature(path,i,step)+curvature(path,(i+1)%n,step))*.5,w=len*(1+sensitivity*Math.pow(k,1.35));weights[i]=w;total+=w;cum.push(total)}const out=[];for(let j=0;j<count;j++){const target=total*j/count;let lo=0,hi=n;while(lo<hi){const mid=(lo+hi)>>1;if(cum[mid+1]<target)lo=mid+1;else hi=mid}const i=Math.min(lo,n-1),a=path[i],b=path[(i+1)%n],span=Math.max(.0001,weights[i]),t=clamp((target-cum[i])/span,0,1);out.push({x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t})}return out}
 async function contour(asset,o){const raw=await rasterMask(asset,o),main=largestComponent(raw),profile=profiles[o.contourProfile]||profiles.balanced;return smooth(traceOuter(main),profile.smooth)}
 async function render(asset,o={}){const c=makeCanvas(),x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,W,H);x.fillStyle='#111';x.textAlign='center';x.font=`700 ${Number(o.titleSize)||112}px Arial`;x.fillText(o.title||'Connect the Dots!',W/2,230);x.font=`${Number(o.instructionSize)||46}px Arial`;x.fillText(o.instructions||'Connect the dots in number order.',W/2,340);const path=await contour(asset,o),count=clamp(Number(o.dotCount)||30,8,120),sensitivity=clamp(Number(o.curveSensitivity)||6,0,10),pts=o.dotDistribution==='uniform'?arcSample(path,count):adaptiveSample(path,count,sensitivity),scale=clamp(Number(o.assetSize)||100,30,180)/100,minX=Math.min(...path.map(p=>p.x)),maxX=Math.max(...path.map(p=>p.x)),minY=Math.min(...path.map(p=>p.y)),maxY=Math.max(...path.map(p=>p.y)),pw=maxX-minX||1,ph=maxY-minY||1,fit=Math.min(1650*scale/pw,2250*scale/ph),cx=W/2,cy=1770,tx=p=>({x:cx+(p.x-(minX+maxX)/2)*fit,y:cy+(p.y-(minY+maxY)/2)*fit}),draw=pts.map(tx),full=path.map(tx);if(o.guide==='faint'){x.save();x.strokeStyle='rgba(70,70,70,.12)';x.lineWidth=4;x.beginPath();full.forEach((p,i)=>i?x.lineTo(p.x,p.y):x.moveTo(p.x,p.y));x.closePath();x.stroke();x.restore()}const r=clamp(Number(o.dotSize)||13,5,28),fs=clamp(Number(o.numberSize)||34,18,64);x.fillStyle='#111';x.font=`700 ${fs}px Arial`;for(let i=0;i<draw.length;i++){const p=draw[i],prev=draw[(i-1+draw.length)%draw.length],next=draw[(i+1)%draw.length];let nx=-(next.y-prev.y),ny=next.x-prev.x;const len=Math.hypot(nx,ny)||1,toCenterX=cx-p.x,toCenterY=cy-p.y;if(nx*toCenterX+ny*toCenterY>0){nx*=-1;ny*=-1}x.beginPath();x.arc(p.x,p.y,r,0,Math.PI*2);x.fill();if(o.numbers!=='no'){const off=r+fs*.78;x.textAlign='center';x.textBaseline='middle';x.fillText(String(i+1),p.x+nx/len*off,p.y+ny/len*off)}}return c}
 return Object.freeze({render,isSvg});
})();