"use strict";
(async()=>{
  await FenixCore.ready;
  const TYPE="alphabet-studio",$=id=>document.getElementById(id),canvas=$("page"),ctx=canvas.getContext("2d"),editId=new URLSearchParams(location.search).get("id");
  canvas.width=850;canvas.height=1100;
  const val=id=>$(id)?.value||"",num=id=>Number(val(id)||0);
  let decoImage=null,decoKey="",solutionView=false;

  function seeded(seed){let x=0;for(const c of String(seed||"fenix"))x=(x*31+c.charCodeAt(0))>>>0;return()=>((x=(1664525*x+1013904223)>>>0)/4294967296)}
  function shuffle(a,r){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
  function lettersAround(L,count=6){const start=Math.max(0,Math.min(26-count,L.charCodeAt(0)-65-2));return Array.from({length:count},(_,i)=>String.fromCharCode(65+start+i))}
  function alphabetRange(from,to){let a=Math.max(65,Math.min(90,(from||"A").charCodeAt(0))),b=Math.max(65,Math.min(90,(to||"F").charCodeAt(0)));if(a>b)[a,b]=[b,a];return Array.from({length:b-a+1},(_,i)=>String.fromCharCode(a+i))}

  function installDeco(){const anchor=$("title")?.closest("label");if(!anchor)return;const box=document.createElement("div");box.style="margin:14px 0;padding:14px;border:1px solid #d7dce3;border-radius:12px;background:#f8fafc";box.innerHTML='<strong>Warstwa Deco</strong><label class="field"><span><input id="decoEnabled" type="checkbox"> Włącz dekorację tematyczną</span></label><label class="field"><span>Asset z projektu</span><select id="decoAsset"><option value="">— wybierz asset —</option></select></label><div class="row"><label class="field"><span>Pozycja</span><select id="decoPosition"><option value="top-left">Lewy górny</option><option value="top-right" selected>Prawy górny</option><option value="bottom-left">Lewy dolny</option><option value="bottom-right">Prawy dolny</option></select></label><label class="field"><span>Skala</span><input id="decoScale" type="range" min="0.4" max="1.6" step="0.1" value="0.8"></label></div><label class="field"><span>Widoczność</span><input id="decoOpacity" type="range" min="0.15" max="1" step="0.05" value="0.8"></label>';anchor.parentNode.insertBefore(box,anchor);refreshAssets();["decoEnabled","decoAsset","decoPosition","decoScale","decoOpacity"].forEach(id=>$(id)?.addEventListener("input",draw))}
  function installMatchControls(){const letterLabel=$("letter")?.closest("label");if(!letterLabel)return;const box=document.createElement("div");box.id="matchControls";box.style="margin:14px 0;padding:14px;border:1px solid #d7dce3;border-radius:12px;background:#f8fafc";box.innerHTML='<strong>Ustawienia dopasowania liter</strong><div class="row"><label class="field"><span>Zakres liter</span><select id="matchRange"><option value="A-F">A–F</option><option value="G-L">G–L</option><option value="M-R">M–R</option><option value="S-X">S–X</option><option value="U-Z">U–Z</option><option value="custom">Własny zakres</option></select></label><label class="field"><span>Liczba par</span><select id="matchCount"><option value="4">4</option><option value="5">5</option><option value="6" selected>6</option></select></label></div><div id="customMatchRange" class="row" style="display:none"><label class="field"><span>Od litery</span><input id="matchFrom" maxlength="1" value="A"></label><label class="field"><span>Do litery</span><input id="matchTo" maxlength="1" value="F"></label></div>';letterLabel.parentNode.insertBefore(box,letterLabel.nextSibling);["matchRange","matchCount","matchFrom","matchTo"].forEach(id=>$(id)?.addEventListener("input",()=>{solutionView=false;updateTypeControls();draw()}))}
  function installSolutionButton(){const png=$("png");if(!png)return;const b=document.createElement("button");b.id="solutionPreview";b.type="button";b.textContent="Pokaż rozwiązanie";b.style="background-color:#7c3aed!important;color:#fff!important;border:1px solid #6d28d9!important;-webkit-appearance:none!important;appearance:none!important;background-image:none!important;";b.onclick=()=>{solutionView=!solutionView;draw()};png.insertAdjacentElement("afterend",b)}

  function refreshAssets(){const s=$("decoAsset");if(!s)return;const keep=s.value,assets=Object.values(FenixCore.getActiveProject()?.assets||{});s.innerHTML='<option value="">— wybierz asset —</option>'+assets.map(a=>`<option value="${a.id}">${a.name||a.filename||'Asset'}</option>`).join('');if(assets.some(a=>a.id===keep))s.value=keep}
  function decoSettings(){return{enabled:$("decoEnabled")?.checked||false,assetId:val("decoAsset"),position:val("decoPosition")||"top-right",scale:Number(val("decoScale"))||.8,opacity:Number(val("decoOpacity"))||.8}}
  function matchSettings(){return{range:val("matchRange")||"A-F",count:Math.max(4,Math.min(6,Number(val("matchCount"))||6)),from:(val("matchFrom")||"A").slice(0,1).toUpperCase(),to:(val("matchTo")||"F").slice(0,1).toUpperCase()}}
  function settings(){return{type:val("type"),difficulty:val("difficulty"),age:val("age"),letter:(val("letter")||"A").slice(0,1).toUpperCase(),helperWidth:num("helperWidth")||1.5,helperOpacity:num("helperOpacity")||.35,title:val("title"),instructions:val("instructions"),seed:val("seed"),language:val("language"),match:matchSettings(),deco:decoSettings()}}

  function base(o){ctx.clearRect(0,0,850,1100);ctx.fillStyle="#fff";ctx.fillRect(0,0,850,1100);ctx.strokeStyle="#111827";ctx.lineWidth=3;ctx.strokeRect(40,40,770,1020);ctx.fillStyle="#111827";ctx.textAlign="center";ctx.font="700 40px Arial";ctx.fillText(solutionView&&o.type==="match-case"?"Solution":(o.title||"Alphabet Practice"),425,105);ctx.font="20px Arial";ctx.fillText(solutionView&&o.type==="match-case"?"Correct uppercase and lowercase pairs.":(o.instructions||"Practice the letter and complete the activity."),425,145)}
  function drawDeco(d){if(!d.enabled||!d.assetId)return;const a=FenixCore.getActiveProject()?.assets?.[d.assetId];if(!a?.dataUrl)return;if(decoKey!==a.dataUrl){decoKey=a.dataUrl;decoImage=new Image();decoImage.onload=draw;decoImage.src=a.dataUrl;return}if(!decoImage?.complete)return;const max=115*d.scale,ratio=(decoImage.naturalWidth||1)/(decoImage.naturalHeight||1);let w=max,h=max;if(ratio>1)h=w/ratio;else w=h*ratio;const pos={"top-left":[70,175],"top-right":[780-w,175],"bottom-left":[70,1015-h],"bottom-right":[780-w,1015-h]}[d.position]||[780-w,175];ctx.save();ctx.globalAlpha=Math.max(.15,Math.min(1,d.opacity));ctx.drawImage(decoImage,pos[0],pos[1],w,h);ctx.restore()}

  function matchLetters(o){const m=o.match||{},count=Math.max(4,Math.min(6,m.count||6));let pool;if(m.range==="custom")pool=alphabetRange(m.from,m.to);else{const [from,to]=String(m.range||"A-F").split("-");pool=alphabetRange(from,to)}if(pool.length<count){const start=pool[0]||"A";pool=lettersAround(start,count)}return pool.slice(0,count)}
  function matchLayout(o){const baseLetters=matchLetters(o),left=shuffle(baseLetters,seeded(`${o.seed}|left`));let right=shuffle(baseLetters.map(x=>x.toLowerCase()),seeded(`${o.seed}|right`));for(let tries=0;tries<12&&left.some((x,i)=>x.toLowerCase()===right[i]);tries++)right=shuffle(right,seeded(`${o.seed}|right|${tries}`));return{left,right}}

  function drawLetterPractice(o,L){ctx.fillStyle="#111827";ctx.textAlign="center";ctx.font="700 235px Arial";ctx.fillText(L,300,445);ctx.font="700 190px Arial";ctx.fillText(L.toLowerCase(),560,445);ctx.font="700 42px Arial";ctx.fillText(`${L}   ${L}   ${L}     ${L.toLowerCase()}   ${L.toLowerCase()}   ${L.toLowerCase()}`,425,620);ctx.font="28px Arial";ctx.fillText("Say the letter aloud, then write it below.",425,700);ctx.strokeStyle="#9ca3af";ctx.lineWidth=1.5;for(let y=790;y<=970;y+=90){ctx.beginPath();ctx.moveTo(110,y);ctx.lineTo(740,y);ctx.stroke()}}
  function drawTrace(o,L){ctx.fillStyle="#111827";ctx.textAlign="center";ctx.font="700 86px Arial";ctx.fillText(`${L}   ${L.toLowerCase()}`,425,265);ctx.save();ctx.globalAlpha=Math.max(.1,Math.min(1,o.helperOpacity));ctx.strokeStyle="#111827";ctx.lineWidth=Math.max(.5,Math.min(5,o.helperWidth));ctx.textAlign="center";ctx.font="700 92px Arial";for(let row=0;row<6;row++)for(let col=0;col<6;col++){const x=135+col*116,y=395+row*103;ctx.strokeText(col<3?L:L.toLowerCase(),x,y)}ctx.restore();ctx.fillStyle="#6b7280";ctx.font="18px Arial";ctx.fillText("Follow the light guide line with a pencil.",425,1020)}
  function drawMatch(o,showSolution=false){const {left,right}=matchLayout(o),n=left.length,step=n<=4?145:n===5?125:110,startY=n<=4?350:n===5?325:315,ys=[];ctx.textAlign="center";ctx.font="700 28px Arial";ctx.fillStyle="#111827";ctx.fillText(showSolution?"Correct pairs":"Match each uppercase letter with its lowercase partner.",425,220);ctx.font="700 48px Arial";for(let i=0;i<n;i++){const y=startY+i*step;ys.push(y);ctx.strokeStyle="#cbd5e1";ctx.lineWidth=2;ctx.strokeRect(120,y-48,150,72);ctx.strokeRect(580,y-48,150,72);ctx.fillStyle="#111827";ctx.fillText(left[i],195,y+5);ctx.fillText(right[i],655,y+5);ctx.fillStyle="#9ca3af";ctx.beginPath();ctx.arc(300,y-12,5,0,Math.PI*2);ctx.arc(550,y-12,5,0,Math.PI*2);ctx.fill()}if(showSolution){ctx.save();ctx.strokeStyle="#374151";ctx.lineWidth=4;ctx.globalAlpha=.85;for(let i=0;i<n;i++){const target=right.indexOf(left[i].toLowerCase());if(target<0)continue;ctx.beginPath();ctx.moveTo(305,ys[i]-12);ctx.lineTo(545,ys[target]-12);ctx.stroke()}ctx.restore()}}
  function drawFind(o,L){const r=seeded(o.seed),pool=[L,L.toLowerCase(),...lettersAround(L,10).filter(x=>x!==L),...lettersAround(L,10).filter(x=>x!==L).map(x=>x.toLowerCase())];ctx.textAlign="center";ctx.fillStyle="#111827";ctx.font="700 30px Arial";ctx.fillText(`Circle every ${L} and ${L.toLowerCase()}.`,425,225);ctx.font="700 46px Arial";for(let row=0;row<7;row++)for(let col=0;col<8;col++){let ch=pool[Math.floor(r()*pool.length)];if(r()<.22)ch=r()<.5?L:L.toLowerCase();ctx.fillText(ch,115+col*88,330+row*90)}}
  function drawMissing(o,L){const seq=lettersAround(L,10),r=seeded(o.seed),left=92,right=758,gap=12;ctx.textAlign="center";ctx.fillStyle="#111827";ctx.font="700 29px Arial";ctx.fillText("Write the missing letters.",425,220);for(let row=0;row<5;row++){const shown=seq.map((x,i)=>((i+row)%3===1||r()<.08)?"___":x),widths=shown.map(x=>Math.max(38,ctx.measureText(x).width+12)),total=widths.reduce((a,b)=>a+b,0)+gap*(shown.length-1),scale=Math.min(1,(right-left)/total);let x=425-total*scale/2;ctx.font=`700 ${Math.max(30,44*scale)}px Arial`;for(let i=0;i<shown.length;i++){const w=widths[i]*scale;ctx.fillText(shown[i],x+w/2,340+row*125);x+=w+gap*scale}}}
  function drawWords(o,L){const words={A:["apple","ant","anchor"],B:["ball","bee","boat"],C:["cat","car","crab"],D:["dog","duck","dolphin"],E:["egg","ear","eel"],F:["fish","frog","flag"],G:["goat","gift","grape"],H:["hat","hen","house"],I:["ice","ink","island"],J:["jam","jar","jellyfish"],K:["kite","key","king"],L:["lion","leaf","lamp"],M:["moon","mouse","map"],N:["nest","net","nose"],O:["octopus","owl","orange"],P:["pig","pen","pearl"],Q:["queen","quilt","quiz"],R:["rain","ring","ray"],S:["sun","star","shark"],T:["turtle","tree","train"],U:["umbrella","urchin","up"],V:["van","vase","vest"],W:["whale","wave","web"],X:["x-ray","xylophone","fox"],Y:["yak","yarn","yellow"],Z:["zebra","zero","zip"]};const list=words[L]||[L.toLowerCase()];ctx.textAlign="center";ctx.fillStyle="#111827";ctx.font="700 150px Arial";ctx.fillText(L,425,365);ctx.font="700 42px Arial";ctx.fillText(list.map(w=>w[0].toUpperCase()+w.slice(1)).join("   •   "),425,520);ctx.font="26px Arial";ctx.fillText("Say each word. Which sound do they share?",425,610);ctx.strokeStyle="#9ca3af";ctx.lineWidth=1.5;for(let y=735;y<=955;y+=74){ctx.beginPath();ctx.moveTo(120,y);ctx.lineTo(730,y);ctx.stroke()}}

  function updateTypeControls(){const type=val("type"),isMatch=type==="match-case",isTrace=type==="trace";if(!isMatch)solutionView=false;if($("matchControls"))$("matchControls").style.display=isMatch?"block":"none";if($("customMatchRange"))$("customMatchRange").style.display=isMatch&&val("matchRange")==="custom"?"grid":"none";const letterLabel=$("letter")?.closest("label");if(letterLabel)letterLabel.style.display=isMatch?"none":"";if($("traceControls"))$("traceControls").hidden=!isTrace;if($("solutionPreview")){$("solutionPreview").style.display=isMatch?"":"none";$("solutionPreview").textContent=solutionView?"Pokaż zadanie":"Pokaż rozwiązanie"}$("helperWidthValue").textContent=`${num("helperWidth").toFixed(1)} px`;$("helperOpacityValue").textContent=`${Math.round(num("helperOpacity")*100)}%`}
  function draw(){const o=settings(),L=o.letter||"A";updateTypeControls();base(o);({"letter-practice":()=>drawLetterPractice(o,L),trace:()=>drawTrace(o,L),"match-case":()=>drawMatch(o,solutionView),find:()=>drawFind(o,L),missing:()=>drawMissing(o,L),words:()=>drawWords(o,L)}[o.type]||(()=>drawLetterPractice(o,L)))();drawDeco(o.deco)}

  function payload(){const o=settings(),layout=o.type==="match-case"?matchLayout(o):null;return FenixPageSchema.normalize({module:TYPE,title:o.title||"Alphabet Practice",seed:o.seed,recipe:{module:TYPE,seed:o.seed,title:o.title,settings:o,content:{letter:o.letter,type:o.type,match:o.match,matchLayout:layout},meta:{moduleVersion:6,renderer:"alphabet-v6",lightweight:true}},preview:{imageData:null},solution:{available:o.type==="match-case",imageData:null},source:{app:"fenix-portable-preview",version:"6.0",format:"native"}})}
  function pages(){return FenixCore.getCart().filter(p=>(p.module||p.recipe?.module)===TYPE)}
  function renderList(){const list=pages();$("savedCount").textContent=`${list.length} ${list.length===1?"strona":"stron"}`;$("savedList").innerHTML=list.length?list.map((p,i)=>{const s=p.recipe?.settings||p.settings||{},L=s.letter||p.recipe?.content?.letter||"A",t=s.type||p.recipe?.content?.type||"letter-practice",match=s.match||p.recipe?.content?.match;const meta=t==="match-case"&&match?`${match.range||'A-F'} · ${match.count||6} par · Solution`:`litera ${L}`;return `<article class="saved-item${String(p.id)===String(editId)?' current':''}"><div class="thumb">${t==="match-case"?'Aa':L}</div><div><strong>Alphabet #${String(i+1).padStart(2,'0')} · ${p.title||'Alphabet Practice'}</strong><div class="hint">${t} · ${meta} · ${s.difficulty||'medium'} · ${s.age||'5-7'}</div></div><div class="item-actions"><button data-edit="${p.id}">Edytuj</button><button data-del="${p.id}">Usuń</button></div></article>`}).join(""):'<div class="hint">Nie zapisano jeszcze stron Alphabet Studio.</div>';document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>location.href=`${location.pathname}?id=${encodeURIComponent(b.dataset.edit)}`);document.querySelectorAll("[data-del]").forEach(b=>b.onclick=()=>{if(confirm("Usunąć tę stronę Alphabet?")){FenixCore.removePage(b.dataset.del);renderList()}})}
  function restore(){if(!editId)return;const p=pages().find(x=>String(x.id)===String(editId));if(!p)return;const s=p.recipe?.settings||p.settings||{};Object.entries(s).forEach(([k,v])=>{if(!["deco","match"].includes(k)&&$(k)&&v!=null)$(k).value=v});if(!s.letter&&p.recipe?.content?.letter)$("letter").value=p.recipe.content.letter;if(!s.type&&p.recipe?.content?.type)$("type").value=p.recipe.content.type;const m=s.match||p.recipe?.content?.match;if(m){$("matchRange").value=m.range||"A-F";$("matchCount").value=m.count||6;$("matchFrom").value=m.from||"A";$("matchTo").value=m.to||"F"}if(s.deco){$("decoEnabled").checked=!!s.deco.enabled;$("decoAsset").value=s.deco.assetId||"";$("decoPosition").value=s.deco.position||"top-right";$("decoScale").value=s.deco.scale||.8;$("decoOpacity").value=s.deco.opacity||.8}$("cart").textContent="Zapisz zmiany w projekcie";$("editBadge").textContent="TRYB EDYCJI · zapisujesz tę samą stronę";updateTypeControls();draw()}
  function save(){try{const data=payload();if(editId){FenixCore.updatePage(editId,data);$("status").textContent=data.solution?.available?"✓ Zapisano stronę Alphabet + Solution.":"✓ Zapisano zmiany strony Alphabet."}else{FenixCore.addPage(data);$("status").textContent=data.solution?.available?"✓ Dodano stronę Alphabet + Solution do projektu.":"✓ Dodano stronę Alphabet do projektu."}renderList()}catch(e){$("status").textContent=`Błąd zapisu: ${e?.message||e}`}}

  installDeco();installMatchControls();installSolutionButton();
  $("generate").onclick=draw;
  $("randomSeed").onclick=()=>{$("seed").value=`fenix-alphabet-${Date.now().toString(36)}`;solutionView=false;draw()};
  $("png").onclick=()=>FenixCore.downloadCanvas(canvas,`${solutionView?'alphabet-solution':'alphabet'}-${Date.now()}.png`);
  $("newPage").onclick=()=>location.href=location.pathname;
  $("cart").onclick=save;
  ["type","difficulty","age","letter","title","instructions","seed","language","helperWidth","helperOpacity"].forEach(id=>$(id)?.addEventListener("input",()=>{solutionView=false;updateTypeControls();draw()}));
  const p=FenixCore.getActiveProject();$("projectInfo").textContent=`Aktywny projekt: ${p.name} · ${p.format}`;
  restore();updateTypeControls();draw();renderList();window.addEventListener("fenix-state-change",()=>{refreshAssets();renderList()});
})();