"use strict";
(()=>{
const $=id=>document.getElementById(id),canvas=$("page"),requestedId=new URLSearchParams(location.search).get("id");
const state={assets:[],library:[],selected:new Set(),manual:[{left:"A",right:"a"},{left:"B",right:"b"},{left:"C",right:"c"},{left:"D",right:"d"},{left:"E",right:"e"}],task:null,solution:null,view:"task",assetSource:"project",editingId:requestedId||null};let timer=null,restoring=false;
const val=(id,f="")=>$(id)?.value??f,num=(id,f)=>Number(val(id,f))||f,safe=s=>String(s||"").replace(/[&<>"']/g,"");
const opts=()=>({mode:val("mode","alphabet"),pairCount:num("pairCount",5),seed:val("seed","fenix-match"),shuffle:val("shuffle","yes"),textSize:num("textSize",66),assetSize:num("assetSize",100),rowGap:num("rowGap",220),autoSpacing:val("autoSpacing","yes"),quantitySize:num("quantitySize",38),quantityGap:num("quantityGap",58),anchors:val("anchors","dots"),frames:val("frames","none"),solutionStyle:val("solutionStyle","lines"),shadowStyle:val("shadowStyle","solid"),shadowOpacity:num("shadowOpacity",55),shadowStroke:num("shadowStroke",5),shadowSide:val("shadowSide","left"),title:val("title","Match the Pairs!"),instructions:val("instructions","Draw a line to match each pair."),titleSize:num("titleSize",110),instructionSize:num("instructionSize",44)});
const modeLabels={alphabet:"Litery",identical:"Identyczne obrazki",shadow:"Obrazek → cień","word-image":"Słowo → obrazek","number-quantity":"Liczba → ilość",manual:"Pary ręczne"};
const isSvg=a=>String(a?.mime||"").includes("svg")||String(a?.dataUrl||"").startsWith("data:image/svg+xml");
function status(t,e=false){$("status").textContent=t;$("status").dataset.type=e?"error":"ok"}
function allLibrary(){const active=FenixCore.getActiveProjectId(),seen=new Set(),out=[];for(const p of FenixCore.getProjects())for(const a of Object.values(p.assets||{})){const key=a.dataUrl||`${a.filename}|${a.sizeBytes}`;if(seen.has(key))continue;seen.add(key);out.push({...a,_projectId:p.id,_projectName:p.name,_active:p.id===active})}return out}
function assetAllowed(a){return val("mode","alphabet")!=="shadow"||isSvg(a)}
function selectedAssets(){return state.assets.filter(a=>state.selected.has(a.id))}
function updateSummary(){const o=opts(),selected=selectedAssets();$("summaryMode").textContent=modeLabels[o.mode]||o.mode;$("summaryAssets").textContent=String(selected.length);$("summaryPairs").textContent=String(Math.min(o.pairCount,["alphabet","number-quantity","manual"].includes(o.mode)?o.pairCount:selected.length));$("previewInfo").textContent=state.editingId?`Edytujesz zapisaną stronę · ${o.title}`:`Nowa strona · ${o.title}`;const count=$("selectedAssetsCount"),strip=$("selectedAssetStrip");if(count)count.textContent=`${selected.length} ${selected.length===1?"wybrany":"wybranych"}`;if(strip)strip.innerHTML=selected.length?selected.map(a=>`<img src="${a.dataUrl}" alt="${safe(a.name)}" title="${safe(a.name)}">`).join(""):""}
function renderAssets(){state.assets=FenixCore.listAssets();for(const id of [...state.selected])if(!state.assets.some(a=>a.id===id))state.selected.delete(id);const g=$("assetGrid");g.innerHTML="";for(const a of state.assets){const allowed=assetAllowed(a),b=document.createElement("button");b.type="button";b.disabled=!allowed;b.className=`asset-card${state.selected.has(a.id)?" selected":""}${allowed?"":" disabled"}`;b.innerHTML=`<img src="${a.dataUrl}" alt=""><strong>${safe(a.name||a.filename||"Asset")}</strong>${!allowed?'<span class="check">SVG ONLY</span>':state.selected.has(a.id)?'<span class="check">WYBRANY</span>':""}`;b.onclick=()=>{if(!allowed)return;state.selected.has(a.id)?state.selected.delete(a.id):state.selected.add(a.id);renderAssets();schedule()};g.appendChild(b)}updateSummary()}
function renderLibrary(){state.library=allLibrary();const g=$("libraryGrid");g.innerHTML="";for(const a of state.library){const allowed=assetAllowed(a),b=document.createElement("button");b.type="button";b.disabled=!allowed;b.className=`asset-card${state.selected.has(a.id)&&a._active?" selected":""}${allowed?"":" disabled"}`;b.innerHTML=`<img src="${a.dataUrl}" alt=""><strong>${safe(a.name||a.filename||"Asset")}</strong><small>${safe(a._projectName||"")}</small>${!allowed?'<span class="check">SVG ONLY</span>':state.selected.has(a.id)&&a._active?'<span class="check">WYBRANY</span>':""}`;b.onclick=()=>{if(!allowed)return;if(a._active){state.selected.add(a.id);renderAssets();renderLibrary();schedule();return}const existing=state.assets.find(x=>x.dataUrl===a.dataUrl);if(existing){state.selected.add(existing.id);showSource("project");renderAssets();renderLibrary();schedule();return}const copy=FenixCore.putAsset({name:a.name,filename:a.filename,mime:a.mime,dataUrl:a.dataUrl,source:"fenix-library",width:a.width,height:a.height,sizeBytes:a.sizeBytes,tags:a.tags||["content"],meta:{...(a.meta||{}),librarySourceProject:a._projectName}});state.selected.add(copy.id);showSource("project");renderAssets();renderLibrary();schedule()};g.appendChild(b)}}
function showSource(which){state.assetSource=which;$("projectPane").hidden=which!=="project";$("libraryPane").hidden=which!=="library";$("tabProject").classList.toggle("active",which==="project");$("tabLibrary").classList.toggle("active",which==="library");if(which==="library")renderLibrary()}
function renderManual(){const box=$("manualPairs");box.innerHTML="";state.manual.forEach((p,i)=>{const row=document.createElement("div");row.className="pair-row";row.innerHTML=`<input data-i="${i}" data-k="left" value="${safe(p.left)}"><span>↔</span><input data-i="${i}" data-k="right" value="${safe(p.right)}"><button type="button" data-remove="${i}">×</button>`;box.appendChild(row)});box.querySelectorAll("input").forEach(inp=>inp.oninput=()=>{state.manual[Number(inp.dataset.i)][inp.dataset.k]=inp.value;schedule()});box.querySelectorAll("[data-remove]").forEach(btn=>btn.onclick=()=>{state.manual.splice(Number(btn.dataset.remove),1);renderManual();schedule()})}
function renumberSections(){let n=1;document.querySelectorAll("[data-section]").forEach(section=>{if(section.hidden)return;const summary=section.querySelector("summary[data-label]");if(summary)summary.textContent=`${n++}. ${summary.dataset.label}`});$("previewSectionNumber").textContent=`${n}.`}
function updateShadowUI(){const style=val("shadowStyle","solid");$("shadowOpacityWrap").hidden=style==="solid";$("shadowStrokeWrap").hidden=style!=="outline"}
function updateModeUI(resetText=true){const mode=val("mode","alphabet"),needsAssets=["identical","shadow","word-image"].includes(mode),manual=mode==="manual",quantity=mode==="number-quantity",shadow=mode==="shadow";$("assetSection").hidden=!needsAssets;$("shadowSection").hidden=!shadow;$("manualSection").hidden=!manual;$("assetSizeWrap").hidden=!needsAssets;$("autoSpacingWrap").hidden=!needsAssets;$("quantitySizeWrap").hidden=!quantity;$("quantityGapWrap").hidden=!quantity;if(shadow)for(const id of [...state.selected]){const a=state.assets.find(x=>x.id===id);if(a&&!isSvg(a))state.selected.delete(id)}if(resetText){const copy={alphabet:["Match Uppercase and Lowercase","Draw a line to match each uppercase letter with its lowercase letter."],shadow:["Match the Shadows!","Draw a line to match each picture with its silhouette."],identical:["Match the Pictures!","Draw a line to match the identical pictures."],"word-image":["Match Words and Pictures!","Draw a line to match each word with the correct picture."],"number-quantity":["Match Number and Quantity","Draw a line to match each number with the correct amount."],manual:["Match the Pairs!","Draw a line to match each pair."]}[mode];if(copy){$("title").value=copy[0];$("instructions").value=copy[1]}}updateShadowUI();renderAssets();renderLibrary();renumberSections();updateSummary();schedule()}
function seededSide(seed){let h=0;for(const c of String(seed||"fenix"))h=(h*31+c.charCodeAt(0))>>>0;return h%2?"left":"right"}
function pairsForMode(){const o=opts(),n=Math.max(1,Math.min(8,o.pairCount)),assets=selectedAssets().slice(0,n);if(o.mode==="alphabet")return [...Array(n)].map((_,i)=>({left:{kind:"text",text:String.fromCharCode(65+i)},right:{kind:"text",text:String.fromCharCode(97+i)}}));if(o.mode==="number-quantity")return [...Array(n)].map((_,i)=>({left:{kind:"text",text:String(i+1)},right:{kind:"quantity",value:i+1}}));if(o.mode==="manual")return state.manual.slice(0,n).map(p=>({left:{kind:"text",text:p.left},right:{kind:"text",text:p.right}}));if(!assets.length)return[];if(o.mode==="shadow"){const side=o.shadowSide==="random"?seededSide(o.seed):o.shadowSide;return assets.filter(isSvg).map(a=>{const original={kind:"image",dataUrl:a.dataUrl},silhouette={kind:"image",dataUrl:a.dataUrl,variant:"shadow"};return side==="right"?{left:silhouette,right:original}:{left:original,right:silhouette}})}return assets.map(a=>{const img={kind:"image",dataUrl:a.dataUrl};return o.mode==="word-image"?{left:{kind:"text",text:a.name||a.filename||"Asset"},right:img}:{left:img,right:{...img}}})}
async function render(){try{const pairs=pairsForMode();updateSummary();if(!pairs.length){canvas.width=850;canvas.height=1100;const c=canvas.getContext("2d");c.fillStyle="#fff";c.fillRect(0,0,850,1100);c.fillStyle="#66717d";c.textAlign="center";c.font="700 30px Arial";c.fillText(["alphabet","number-quantity","manual"].includes(val("mode"))?"Przygotuj ustawienia strony":"Wybierz assety do tego trybu",425,540);state.task=state.solution=null;return status("Przygotuj treść lub wybierz assety dla tej strony.",true)}const o=opts(),effectiveGap=await FenixMatchingCore.requiredGap(pairs,o);[state.task,state.solution]=await Promise.all([FenixMatchingCore.render(pairs,o,false),FenixMatchingCore.render(pairs,o,true)]);showCanvas();status(o.autoSpacing==="yes"&&effectiveGap>Number(o.rowGap)?`Podgląd gotowy · Fenix zwiększył odstęp do ${Math.round(effectiveGap)} px.`:`Podgląd gotowy · ${pairs.length} par.`)}catch(e){console.error(e);state.task=state.solution=null;status(e.message||"Błąd renderowania",true)}}
function showCanvas(){const src=state.view==="solution"?state.solution:state.task;if(!src)return;canvas.width=src.width;canvas.height=src.height;const c=canvas.getContext("2d");c.clearRect(0,0,canvas.width,canvas.height);c.drawImage(src,0,0)}
const schedule=()=>{clearTimeout(timer);timer=setTimeout(()=>void render(),120)};
function matchingPages(){return FenixCore.getCart().filter(p=>(p.module||p.recipe?.module)==="matching-studio")}
function pageThumb(page){const refs=page.recipe?.content?.assetRefs||[],first=refs.map(id=>FenixCore.getAsset(id)).find(Boolean);if(first?.dataUrl)return`<div class="studio-page-thumb"><img src="${first.dataUrl}" alt=""></div>`;const mode=page.recipe?.settings?.mode||"matching";return`<div class="studio-page-thumb"><span>${mode==="alphabet"?"Aa":mode==="number-quantity"?"123":"↔"}</span></div>`}
function renderPageList(){const pages=matchingPages(),box=$("studioPagesList");$("studioPagesCount").textContent=`${pages.length} ${pages.length===1?"strona":"stron"}`;if(!pages.length){box.innerHTML='<div class="studio-pages-empty">Nie zapisano jeszcze żadnej strony Matching.</div>';return}box.innerHTML=pages.map((p,i)=>`<article class="studio-page${p.id===state.editingId?" current":""}">${pageThumb(p)}<div class="studio-page-copy"><strong>Matching #${String(i+1).padStart(2,"0")} · ${safe(p.title||"Match the Pairs!")}</strong><small>${safe(modeLabels[p.recipe?.settings?.mode]||p.recipe?.settings?.mode||"")}${p.id===state.editingId?" · EDYCJA":""}</small></div><div class="studio-page-actions"><button data-edit="${p.id}" type="button">Edytuj</button><button data-delete="${p.id}" class="delete" type="button">Usuń</button></div></article>`).join("");box.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>void loadPage(b.dataset.edit));box.querySelectorAll("[data-delete]").forEach(b=>b.onclick=()=>deletePage(b.dataset.delete))}
function restoreAssets(page){state.selected.clear();const content=page.recipe?.content||{},refs=content.assetRefs||[];for(const id of refs)if(state.assets.some(a=>a.id===id))state.selected.add(id);if(!state.selected.size&&Array.isArray(content.assetIdentities))for(const ident of content.assetIdentities){let hit=state.assets.find(a=>a.id===ident.id);if(!hit&&ident.filename){const matches=state.assets.filter(a=>String(a.filename||"")===String(ident.filename));if(matches.length===1)hit=matches[0]}if(!hit&&ident.name){const matches=state.assets.filter(a=>String(a.name||"")===String(ident.name));if(matches.length===1)hit=matches[0]}if(hit)state.selected.add(hit.id)}if(!state.selected.size){const urls=[];for(const pair of content.pairs||[])for(const side of [pair.left,pair.right])if(side?.kind==="image"&&side.dataUrl)urls.push(side.dataUrl);for(const a of state.assets)if(urls.includes(a.dataUrl))state.selected.add(a.id)}}
function applySettings(s={}){for(const [k,v] of Object.entries(s)){const el=$(k);if(el&&v!=null)el.value=String(v)}}
async function loadPage(id){const p=FenixCore.getCart().find(x=>x.id===id);if(!p||(p.module||p.recipe?.module)!=="matching-studio")return status("Nie znaleziono strony Matching.",true);state.editingId=id;applySettings(p.recipe?.settings||{});state.manual=Array.isArray(p.recipe?.content?.manual)?p.recipe.content.manual.map(x=>({...x})):state.manual;renderManual();state.assets=FenixCore.listAssets();restoreAssets(p);updateModeUI(false);history.replaceState(null,"",`${location.pathname}?id=${encodeURIComponent(id)}`);$("cart").textContent="Zapisz zmiany + Solution";projectInfo();renderAssets();renderPageList();updateSummary();await render()}
function pageData(){const o=opts(),used=selectedAssets().slice(0,Math.max(1,Math.min(8,o.pairCount)));return{module:"matching-studio",title:o.title,recipe:{module:"matching-studio",title:o.title,settings:o,content:{assetRefs:used.map(a=>a.id),assetIdentities:used.map(a=>({id:a.id,name:a.name||null,filename:a.filename||null})),manual:state.manual.map(x=>({...x}))},meta:{createdWith:"FENIX PC",moduleVersion:10}},preview:{imageData:null},solution:{available:true,imageData:null},source:{app:"fenix-desktop",version:"0.10.0",format:"native"}}}
function save(){try{const pairs=pairsForMode();if(!state.task||!state.solution||!pairs.length)return status("Najpierw przygotuj poprawny podgląd.",true);const data=pageData();if(state.editingId){const updated=FenixCore.updatePage(state.editingId,data);if(!updated)throw new Error("Nie udało się odnaleźć strony do aktualizacji.");status("Zapisano zmiany strony Matching wraz z recepturą Solution.")}else{const before=new Set(FenixCore.getCart().map(p=>p.id));FenixCore.addPage(data);const added=matchingPages().find(p=>!before.has(p.id));if(!added)throw new Error("Strona nie pojawiła się w projekcie po zapisie.");state.editingId=added.id;history.replaceState(null,"",`${location.pathname}?id=${encodeURIComponent(state.editingId)}`);$("cart").textContent="Zapisz zmiany + Solution";status("Dodano stronę Matching do projektu.")}projectInfo();renderPageList();updateSummary()}catch(e){console.error(e);status(`Błąd zapisu: ${e.message}`,true)}}
function startNew(){state.editingId=null;state.selected.clear();state.task=state.solution=null;history.replaceState(null,"",location.pathname);$("cart").textContent="Dodaj stronę + Solution";projectInfo();renderAssets();renderPageList();updateSummary();void render()}
function deletePage(id){const p=FenixCore.getCart().find(x=>x.id===id);if(!p)return;if(!confirm(`Usunąć stronę „${p.title||"Matching"}” z projektu?`))return;FenixCore.removePage(id);if(state.editingId===id)startNew();else renderPageList();status("Usunięto stronę Matching z projektu.")}
function projectInfo(){const p=FenixCore.getActiveProject();$("projectInfo").textContent=`Aktywny projekt: ${p.name} · ${p.format}${state.editingId?" · TRYB EDYCJI":""}`}
$("tabProject").onclick=()=>showSource("project");$("tabLibrary").onclick=()=>showSource("library");$("clearAssets").onclick=()=>{state.selected.clear();renderAssets();schedule()};$("addPair").onclick=()=>{state.manual.push({left:"",right:""});renderManual()};$("autoAlphabet").onclick=()=>{state.manual=[...Array(26)].map((_,i)=>({left:String.fromCharCode(65+i),right:String.fromCharCode(97+i)}));$("pairCount").value=8;renderManual();schedule()};$("generate").onclick=()=>void render();$("cart").onclick=save;$("newPage").onclick=startNew;$("png").onclick=()=>{const src=state.view==="solution"?state.solution:state.task;if(src)FenixCore.downloadCanvas(src,`matching-${state.view}-${Date.now()}.png`)};$("taskTab").onclick=()=>{state.view="task";$("taskTab").classList.add("active");$("solutionTab").classList.remove("active");showCanvas()};$("solutionTab").onclick=()=>{state.view="solution";$("solutionTab").classList.add("active");$("taskTab").classList.remove("active");showCanvas()};["pairCount","seed","shuffle","textSize","assetSize","rowGap","autoSpacing","quantitySize","quantityGap","anchors","frames","solutionStyle","shadowOpacity","shadowStroke","shadowSide","title","instructions","titleSize","instructionSize"].forEach(id=>$(id)?.addEventListener($(id).tagName==="SELECT"?"change":"input",()=>{updateSummary();schedule()}));$("shadowStyle").addEventListener("change",()=>{updateShadowUI();schedule()});$("mode").addEventListener("change",()=>updateModeUI(true));window.addEventListener("fenix-state-change",()=>{if(restoring)return;renderAssets();renderLibrary();renderPageList();updateSummary()});
async function init(){projectInfo();status("Wczytuję projekt i assety…");await FenixCore.ready;renderManual();renderAssets();renderLibrary();showSource("project");renderPageList();if(state.editingId){restoring=true;await loadPage(state.editingId);restoring=false}else{updateModeUI(true);await render()}updateSummary()}
void init();
})();