"use strict";
(()=>{
  const $=id=>document.getElementById(id),canvas=$("page");
  const state={assets:[],library:[],selected:new Set(),manual:[{left:"A",right:"a"},{left:"B",right:"b"},{left:"C",right:"c"},{left:"D",right:"d"},{left:"E",right:"e"}],task:null,solution:null,view:"task",assetSource:"project"};
  const val=(id,f="")=>$(id)?.value??f,num=(id,f)=>Number(val(id,f))||f;
  const opts=()=>({mode:val("mode","alphabet"),pairCount:num("pairCount",5),seed:val("seed","fenix-match"),shuffle:val("shuffle","yes"),textSize:num("textSize",66),assetSize:num("assetSize",100),rowGap:num("rowGap",220),autoSpacing:val("autoSpacing","yes"),quantitySize:num("quantitySize",38),quantityGap:num("quantityGap",58),anchors:val("anchors","dots"),frames:val("frames","none"),solutionStyle:val("solutionStyle","lines"),shadowStyle:val("shadowStyle","solid"),shadowOpacity:num("shadowOpacity",55),shadowStroke:num("shadowStroke",5),shadowSide:val("shadowSide","left"),title:val("title","Match the Pairs!"),instructions:val("instructions","Draw a line to match each pair."),titleSize:num("titleSize",110),instructionSize:num("instructionSize",44)});
  const safe=s=>String(s||"").replace(/[&<>"']/g,"");
  const isSvg=a=>String(a?.mime||"").includes("svg")||String(a?.dataUrl||"").startsWith("data:image/svg+xml");
  function status(t,e=false){$("status").textContent=t;$("status").dataset.type=e?"error":"ok"}
  function allLibrary(){const active=FenixCore.getActiveProjectId(),seen=new Set(),out=[];for(const p of FenixCore.getProjects())for(const a of Object.values(p.assets||{})){const key=a.dataUrl||`${a.filename}|${a.sizeBytes}`;if(seen.has(key))continue;seen.add(key);out.push({...a,_projectId:p.id,_projectName:p.name,_active:p.id===active})}return out}
  function assetAllowed(a){return val("mode","alphabet")!=="shadow"||isSvg(a)}
  function renderAssets(){state.assets=FenixCore.listAssets();const g=$("assetGrid");g.innerHTML="";for(const a of state.assets){const allowed=assetAllowed(a),b=document.createElement("button");b.type="button";b.disabled=!allowed;b.className=`asset-card${state.selected.has(a.id)?" selected":""}${allowed?"":" disabled"}`;b.innerHTML=`<img src="${a.dataUrl}" alt=""><strong>${safe(a.name||a.filename||"Asset")}</strong>${!allowed?'<span class="check">SVG ONLY</span>':state.selected.has(a.id)?'<span class="check">WYBRANY</span>':""}`;b.onclick=()=>{if(!allowed)return;state.selected.has(a.id)?state.selected.delete(a.id):state.selected.add(a.id);renderAssets();schedule()};g.appendChild(b)}}
  function renderLibrary(){state.library=allLibrary();const g=$("libraryGrid");g.innerHTML="";for(const a of state.library){const allowed=assetAllowed(a),b=document.createElement("button");b.type="button";b.disabled=!allowed;b.className=`asset-card${state.selected.has(a.id)&&a._active?" selected":""}${allowed?"":" disabled"}`;b.innerHTML=`<img src="${a.dataUrl}" alt=""><strong>${safe(a.name||a.filename||"Asset")}</strong><small>${safe(a._projectName||"")}</small>${!allowed?'<span class="check">SVG ONLY</span>':state.selected.has(a.id)&&a._active?'<span class="check">WYBRANY</span>':""}`;b.onclick=()=>{if(!allowed)return;if(a._active){state.selected.add(a.id);renderAssets();renderLibrary();schedule();return}const existing=state.assets.find(x=>x.dataUrl===a.dataUrl);if(existing){state.selected.add(existing.id);showSource("project");renderAssets();renderLibrary();schedule();return}const copy=FenixCore.putAsset({name:a.name,filename:a.filename,mime:a.mime,dataUrl:a.dataUrl,source:"fenix-library",width:a.width,height:a.height,sizeBytes:a.sizeBytes,tags:a.tags||["content"],meta:{...(a.meta||{}),librarySourceProject:a._projectName}});state.selected.add(copy.id);showSource("project");renderAssets();renderLibrary();schedule()};g.appendChild(b)}}
  function showSource(which){state.assetSource=which;$("projectPane").hidden=which!=="project";$("libraryPane").hidden=which!=="library";$("tabProject").classList.toggle("active",which==="project");$("tabLibrary").classList.toggle("active",which==="library");if(which==="library")renderLibrary()}
  function renderManual(){const box=$("manualPairs");box.innerHTML="";state.manual.forEach((p,i)=>{const row=document.createElement("div");row.className="pair-row";row.innerHTML=`<input data-i="${i}" data-k="left" value="${safe(p.left)}"><span>↔</span><input data-i="${i}" data-k="right" value="${safe(p.right)}"><button type="button" data-remove="${i}">×</button>`;box.appendChild(row)});box.querySelectorAll("input").forEach(inp=>inp.oninput=()=>{state.manual[Number(inp.dataset.i)][inp.dataset.k]=inp.value;schedule()});box.querySelectorAll("[data-remove]").forEach(btn=>btn.onclick=()=>{state.manual.splice(Number(btn.dataset.remove),1);renderManual();schedule()})}
  function renumberSections(){let n=1;document.querySelectorAll("[data-section]").forEach(section=>{if(section.hidden)return;const summary=section.querySelector("summary[data-label]");if(summary)summary.textContent=`${n++}. ${summary.dataset.label}`});$("previewSectionNumber").textContent=`${n}.`}
  function updateShadowUI(){const style=val("shadowStyle","solid");$("shadowOpacityWrap").hidden=style==="solid";$("shadowStrokeWrap").hidden=style!=="outline"}
  function updateModeUI(){const mode=val("mode","alphabet"),needsAssets=["identical","shadow","word-image"].includes(mode),manual=mode==="manual",quantity=mode==="number-quantity",shadow=mode==="shadow";$("assetSection").hidden=!needsAssets;$("shadowSection").hidden=!shadow;$("manualSection").hidden=!manual;$("assetSizeWrap").hidden=!needsAssets;$("autoSpacingWrap").hidden=!needsAssets;$("quantitySizeWrap").hidden=!quantity;$("quantityGapWrap").hidden=!quantity;if(shadow){for(const id of [...state.selected]){const a=state.assets.find(x=>x.id===id);if(a&&!isSvg(a))state.selected.delete(id)}}if(mode==="alphabet"){$("title").value="Match Uppercase and Lowercase";$("instructions").value="Draw a line to match each uppercase letter with its lowercase letter."}else if(mode==="shadow"){$("title").value="Match the Shadows!";$("instructions").value="Draw a line to match each picture with its silhouette."}else if(mode==="identical"){$("title").value="Match the Pictures!";$("instructions").value="Draw a line to match the identical pictures."}else if(mode==="number-quantity"){$("title").value="Match Number and Quantity";$("instructions").value="Draw a line to match each number with the correct amount."}else if(mode==="manual"){$("title").value="Match the Pairs!";$("instructions").value="Draw a line to match each pair."}updateShadowUI();renderAssets();renderLibrary();renumberSections();schedule()}
  function selectedAssets(){return state.assets.filter(a=>state.selected.has(a.id))}
  function seededSide(seed){let h=0;for(const c of String(seed||"fenix"))h=(h*31+c.charCodeAt(0))>>>0;return h%2?"left":"right"}
  function pairsForMode(){const o=opts(),n=Math.max(1,Math.min(8,o.pairCount)),assets=selectedAssets().slice(0,n);if(o.mode==="alphabet")return [...Array(n)].map((_,i)=>({left:{kind:"text",text:String.fromCharCode(65+i)},right:{kind:"text",text:String.fromCharCode(97+i)}}));if(o.mode==="number-quantity")return [...Array(n)].map((_,i)=>({left:{kind:"text",text:String(i+1)},right:{kind:"quantity",value:i+1}}));if(o.mode==="manual")return state.manual.slice(0,n).map(p=>({left:{kind:"text",text:p.left},right:{kind:"text",text:p.right}}));if(!assets.length)return [];if(o.mode==="shadow"){const svgAssets=assets.filter(isSvg),side=o.shadowSide==="random"?seededSide(o.seed):o.shadowSide;return svgAssets.map(a=>{const original={kind:"image",dataUrl:a.dataUrl};const silhouette={kind:"image",dataUrl:a.dataUrl,variant:"shadow"};return side==="right"?{left:silhouette,right:original}:{left:original,right:silhouette}})}return assets.map(a=>{const img={kind:"image",dataUrl:a.dataUrl};if(o.mode==="word-image")return{left:{kind:"text",text:a.name||a.filename||"Asset"},right:img};return{left:img,right:{...img}}})}
  async function render(){try{const pairs=pairsForMode();if(!pairs.length){const c=canvas.getContext("2d");canvas.width=850;canvas.height=1100;c.fillStyle="#fff";c.fillRect(0,0,850,1100);c.fillStyle="#66717d";c.textAlign="center";c.font="700 30px Arial";c.fillText(val("mode")==="shadow"?"Wybierz assety SVG":"Wybierz assety do tego trybu",425,540);state.task=state.solution=null;return status(val("mode")==="shadow"?"Tryb Obrazek → cień obsługuje teraz wyłącznie SVG.":"Wybierz assety projektu lub Biblioteki Feniksa.",true)}const o=opts(),effectiveGap=await FenixMatchingCore.requiredGap(pairs,o);[state.task,state.solution]=await Promise.all([FenixMatchingCore.render(pairs,o,false),FenixMatchingCore.render(pairs,o,true)]);showCanvas();if(o.frames==="soft"&&o.autoSpacing==="no"&&effectiveGap>Number(o.rowGap)){status("Uwaga: przy tym rozmiarze assetu kapsułki mogą nachodzić na siebie. Włącz Auto-dopasuj odstęp albo zwiększ odstęp między parami.",true)}else if(o.autoSpacing==="yes"&&effectiveGap>Number(o.rowGap)){status(`Podgląd gotowy · Fenix zwiększył odstęp do ${Math.round(effectiveGap)} px.`)}else status(`Podgląd gotowy · ${pairs.length} par.`)}catch(e){console.error(e);status(e.message||"Błąd renderowania",true)}}
  function showCanvas(){const src=state.view==="solution"?state.solution:state.task;if(!src)return;canvas.width=src.width;canvas.height=src.height;const c=canvas.getContext("2d");c.clearRect(0,0,canvas.width,canvas.height);c.drawImage(src,0,0)}
  let timer;const schedule=()=>{clearTimeout(timer);timer=setTimeout(render,120)};
  function save(){const pairs=pairsForMode();if(!state.task||!pairs.length)return status("Najpierw przygotuj poprawny podgląd.",true);const o=opts();FenixCore.addPage({module:"matching-studio",title:o.title,recipe:{module:"matching-studio",title:o.title,settings:o,content:{pairs},meta:{createdWith:"FENIX PC",moduleVersion:8}},preview:{imageData:state.task.toDataURL("image/png")},solution:{available:true,imageData:state.solution.toDataURL("image/png")},source:{app:"fenix-desktop",version:"0.8.0",format:"native"}});status("Dodano stronę Matching wraz z Solution do projektu.")}
  $("tabProject").onclick=()=>showSource("project");$("tabLibrary").onclick=()=>showSource("library");$("addPair").onclick=()=>{state.manual.push({left:"",right:""});renderManual()};$("autoAlphabet").onclick=()=>{state.manual=[...Array(26)].map((_,i)=>({left:String.fromCharCode(65+i),right:String.fromCharCode(97+i)}));$("pairCount").value=8;renderManual();schedule()};$("generate").onclick=render;$("cart").onclick=save;$("png").onclick=()=>{const src=state.view==="solution"?state.solution:state.task;if(src)FenixCore.downloadCanvas(src,`matching-${state.view}-${Date.now()}.png`)};$("taskTab").onclick=()=>{state.view="task";$("taskTab").classList.add("active");$("solutionTab").classList.remove("active");showCanvas()};$("solutionTab").onclick=()=>{state.view="solution";$("solutionTab").classList.add("active");$("taskTab").classList.remove("active");showCanvas()};
  ["pairCount","seed","shuffle","textSize","assetSize","rowGap","autoSpacing","quantitySize","quantityGap","anchors","frames","solutionStyle","shadowOpacity","shadowStroke","shadowSide","title","instructions","titleSize","instructionSize"].forEach(id=>$(id)?.addEventListener($(id).tagName==="SELECT"?"change":"input",schedule));$("shadowStyle").addEventListener("change",()=>{updateShadowUI();schedule()});$("mode").addEventListener("change",updateModeUI);window.addEventListener("fenix-state-change",()=>{renderAssets();renderLibrary();schedule()});const p=FenixCore.getActiveProject();$("projectInfo").textContent=`Aktywny projekt: ${p.name} · ${p.format}`;renderManual();renderAssets();renderLibrary();showSource("project");updateModeUI();render();
})();