"use strict";
window.FenixMatchingCore=(()=>{
  const W=2550,H=3300,clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
  const makeCanvas=()=>{const c=document.createElement("canvas");c.width=W;c.height=H;return c};
  const loadImage=src=>new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=()=>rej(new Error("Nie udało się wczytać assetu."));i.src=src});
  function rng(seed){let x=2166136261;for(const ch of String(seed||"fenix")){x^=ch.charCodeAt(0);x=Math.imul(x,16777619)}return()=>((x=(Math.imul(x,1664525)+1013904223)>>>0)/4294967296)}
  function shuffled(n,seed){const a=[...Array(n).keys()],r=rng(seed);for(let i=a.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
  function shadowDataUrl(src){if(!String(src).startsWith("data:image/svg+xml"))return src;try{const comma=src.indexOf(","),meta=src.slice(0,comma),body=src.slice(comma+1),text=/;base64/i.test(meta)?new TextDecoder().decode(Uint8Array.from(atob(body),c=>c.charCodeAt(0))):decodeURIComponent(body.replace(/\+/g,"%20")),doc=new DOMParser().parseFromString(text,"image/svg+xml"),root=doc.documentElement;root.querySelectorAll("script,foreignObject,image,text").forEach(el=>el.remove());root.querySelectorAll("path,rect,circle,ellipse,line,polyline,polygon").forEach(el=>el.setAttribute("style",`${el.getAttribute("style")||""};fill:#111!important;stroke:#111!important;stroke-width:2!important;`));return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(new XMLSerializer().serializeToString(root))}`}catch{return src}}
  function itemBox(item,o){const isImage=item.kind==="image",scale=isImage?clamp(Number(o.assetSize)||70,30,200)/70:1;return{w:isImage?620*scale:620,h:isImage?240*scale:240,scale}}
  function requiredGap(pairs,o){if(o.frames!=="soft")return clamp(Number(o.rowGap)||220,120,700);let maxH=0;for(const pair of pairs){maxH=Math.max(maxH,itemBox(pair.left,o).h,itemBox(pair.right,o).h)}const requested=clamp(Number(o.rowGap)||220,120,700);return o.autoSpacing==="yes"?Math.max(requested,maxH+42):requested}
  async function drawItem(ctx,item,x,y,o,side){const box=itemBox(item,o),w=box.w,h=box.h,isImage=item.kind==="image";if(o.frames==="soft"){ctx.save();ctx.strokeStyle="#c8d1da";ctx.lineWidth=4;ctx.beginPath();ctx.roundRect(x-w/2,y-h/2,w,h,Math.max(20,Math.min(46,h*.16)));ctx.stroke();ctx.restore()}if(isImage){const src=item.variant==="shadow"?shadowDataUrl(item.dataUrl):item.dataUrl,img=await loadImage(src),fit=Math.min((w*.72)/img.width,(h*.72)/img.height),dw=img.width*fit,dh=img.height*fit;ctx.drawImage(img,x-dw/2,y-dh/2,dw,dh)}else if(item.kind==="quantity"){const count=clamp(Number(item.value)||1,1,12),cols=Math.min(4,count),rows=Math.ceil(count/cols),gap=clamp(Number(o.quantityGap)||58,30,100),r=clamp(Number(o.quantitySize)||38,18,70)/2,startX=x-(cols-1)*gap/2,startY=y-(rows-1)*gap/2;ctx.fillStyle="#111";ctx.strokeStyle="#111";ctx.lineWidth=Math.max(3,r*.16);for(let i=0;i<count;i++){const cx=startX+(i%cols)*gap,cy=startY+Math.floor(i/cols)*gap;ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(cx,cy,r+5,0,Math.PI*2);ctx.stroke()}}else{ctx.fillStyle="#111";ctx.textAlign="center";ctx.textBaseline="middle";ctx.font=`700 ${Number(o.textSize)||66}px Arial`;ctx.fillText(String(item.text??item.value??""),x,y)}if(o.anchors==="dots"){const anchorOffset=w/2+38;ctx.fillStyle="#111";ctx.beginPath();ctx.arc(side==="left"?x+anchorOffset:x-anchorOffset,y,13,0,Math.PI*2);ctx.fill()}return box}
  async function render(pairs,o={},solution=false){const c=makeCanvas(),ctx=c.getContext("2d");ctx.fillStyle="#fff";ctx.fillRect(0,0,W,H);ctx.fillStyle="#111";ctx.textAlign="center";ctx.font=`700 ${o.titleSize||110}px Arial`;ctx.fillText(o.title||"Match the Pairs!",W/2,220);ctx.font=`${o.instructionSize||44}px Arial`;ctx.fillText(solution?"Solution":(o.instructions||"Draw a line to match each pair."),W/2,325);const n=pairs.length,perm=o.shuffle==="no"?[...Array(n).keys()]:shuffled(n,o.seed),leftX=620,rightX=1930,gap=requiredGap(pairs,o),maxSpan=(n-1)*gap,startY=clamp(640+(2600-maxSpan)/2,560,900),leftPts=[],rightPts=[];for(let i=0;i<n;i++){const y=startY+i*gap,box=await drawItem(ctx,pairs[i].left,leftX,y,o,"left");leftPts.push([leftX+box.w/2+38,y])}for(let row=0;row<n;row++){const y=startY+row*gap,idx=perm[row],box=await drawItem(ctx,pairs[idx].right,rightX,y,o,"right");rightPts[idx]=[rightX-box.w/2-38,y]}if(solution){ctx.save();ctx.strokeStyle="#777";ctx.lineWidth=7;ctx.globalAlpha=.82;if(o.solutionStyle==="numbers"){ctx.font="700 44px Arial";ctx.fillStyle="#555";for(let i=0;i<n;i++){ctx.fillText(String(i+1),leftPts[i][0]+55,leftPts[i][1]);ctx.fillText(String(i+1),rightPts[i][0]-55,rightPts[i][1])}}else{for(let i=0;i<n;i++){ctx.beginPath();ctx.moveTo(...leftPts[i]);ctx.lineTo(...rightPts[i]);ctx.stroke()}}ctx.restore()}return c}
  return Object.freeze({render,requiredGap});
})();