"use strict";
window.FenixMatchingCore=(()=>{
  const W=2550,H=3300,clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
  const makeCanvas=(w=W,h=H)=>{const c=document.createElement("canvas");c.width=w;c.height=h;return c};
  const imageCache=new Map(),silhouetteCache=new Map();
  const loadImage=src=>{if(imageCache.has(src))return imageCache.get(src);const p=new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=()=>rej(new Error("Nie udało się wczytać assetu."));i.src=src});imageCache.set(src,p);return p};
  function rng(seed){let x=2166136261;for(const ch of String(seed||"fenix")){x^=ch.charCodeAt(0);x=Math.imul(x,16777619)}return()=>((x=(Math.imul(x,1664525)+1013904223)>>>0)/4294967296)}
  function shuffled(n,seed){const a=[...Array(n).keys()],r=rng(seed);for(let i=a.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
  function isSvg(src){return String(src||"").startsWith("data:image/svg+xml")}
  function dilate(mask,w,h,iterations=1){let src=mask;for(let it=0;it<iterations;it++){const out=new Uint8Array(src);for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){const i=y*w+x;if(src[i]||src[i-1]||src[i+1]||src[i-w]||src[i+w])out[i]=1}src=out}return src}
  function floodOutside(barrier,w,h){const n=w*h,outside=new Uint8Array(n),queue=new Int32Array(n);let head=0,tail=0;const push=i=>{if(i<0||i>=n||outside[i]||barrier[i])return;outside[i]=1;queue[tail++]=i};for(let x=0;x<w;x++){push(x);push((h-1)*w+x)}for(let y=1;y<h-1;y++){push(y*w);push(y*w+w-1)}while(head<tail){const i=queue[head++],x=i%w,y=(i/w)|0;if(x>0)push(i-1);if(x<w-1)push(i+1);if(y>0)push(i-w);if(y<h-1)push(i+w)}return outside}
  function erode(mask,w,h,iterations){let src=mask;for(let it=0;it<iterations;it++){const out=new Uint8Array(src);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=y*w+x;if(!src[i]){out[i]=0;continue}if(x===0||x===w-1||y===0||y===h-1||!src[i-1]||!src[i+1]||!src[i-w]||!src[i+w])out[i]=0}src=out}return src}
  async function silhouetteDataUrl(src,o){if(!isSvg(src))throw new Error("Tryb Obrazek → cień obsługuje wyłącznie SVG.");const style=o.shadowStyle||"solid",opacity=clamp(Number(o.shadowOpacity)||55,10,100),strokeW=clamp(Number(o.shadowStroke)||5,1,24),key=`${src}|${style}|${opacity}|${strokeW}`;if(silhouetteCache.has(key))return silhouetteCache.get(key);const promise=(async()=>{const img=await loadImage(src),iw=img.naturalWidth||img.width||1024,ih=img.naturalHeight||img.height||1024,maxSide=768,scale=maxSide/Math.max(iw,ih),w=Math.max(48,Math.round(iw*scale)),h=Math.max(48,Math.round(ih*scale)),work=makeCanvas(w,h),ctx=work.getContext("2d",{willReadFrequently:true});ctx.clearRect(0,0,w,h);ctx.drawImage(img,0,0,w,h);const data=ctx.getImageData(0,0,w,h).data,raw=new Uint8Array(w*h);let visible=0;for(let i=0,j=3;i<raw.length;i++,j+=4){if(data[j]>18){raw[i]=1;visible++}}if(!visible)throw new Error("Nie udało się wykryć widocznego kształtu SVG.");const barrier=dilate(raw,w,h,2),outside=floodOutside(barrier,w,h),silhouette=new Uint8Array(w*h);for(let i=0;i<silhouette.length;i++)silhouette[i]=outside[i]?0:1;let painted=silhouette;if(style==="outline"){const radius=clamp(Math.round(strokeW/2),1,12),inside=erode(silhouette,w,h,radius),edge=new Uint8Array(w*h);for(let i=0;i<edge.length;i++)edge[i]=silhouette[i]&&!inside[i]?1:0;painted=edge}const out=makeCanvas(w,h),ox=out.getContext("2d"),pixels=ox.createImageData(w,h),p=pixels.data,isGray=style==="gray"||style==="outline",shade=isGray?119:17,alpha=style==="solid"?255:Math.round(opacity*2.55);for(let i=0,j=0;i<painted.length;i++,j+=4){if(!painted[i])continue;p[j]=p[j+1]=p[j+2]=shade;p[j+3]=alpha}ox.putImageData(pixels,0,0);return out.toDataURL("image/png")})();silhouetteCache.set(key,promise);return promise}
  async function graphicMetrics(item,o){if(item.kind!=="image")return{graphicW:420,graphicH:180,frameW:620,frameH:240,img:null,src:null};const scale=clamp(Number(o.assetSize)||100,30,300)/100,src=item.variant==="shadow"?await silhouetteDataUrl(item.dataUrl,o):item.dataUrl,img=await loadImage(src),iw=img.naturalWidth||img.width||1,ih=img.naturalHeight||img.height||1,maxW=500*scale,maxH=300*scale,fit=Math.min(maxW/iw,maxH/ih),graphicW=iw*fit,graphicH=ih*fit,padX=clamp(34*scale,18,90),padY=clamp(28*scale,16,72);return{graphicW,graphicH,frameW:graphicW+padX*2,frameH:graphicH+padY*2,img,src}}
  async function requiredGap(pairs,o){const requested=clamp(Number(o.rowGap)||220,120,900);if(o.autoSpacing!=="yes")return requested;let maxH=0;for(const pair of pairs){const [l,r]=await Promise.all([graphicMetrics(pair.left,o),graphicMetrics(pair.right,o)]);maxH=Math.max(maxH,l.frameH,r.frameH)}return Math.max(requested,maxH+44)}
  async function drawItem(ctx,item,x,y,o,side){const m=await graphicMetrics(item,o),isImage=item.kind==="image";if(o.frames==="soft"){ctx.save();ctx.strokeStyle="#c8d1da";ctx.lineWidth=4;ctx.beginPath();ctx.roundRect(x-m.frameW/2,y-m.frameH/2,m.frameW,m.frameH,Math.max(18,Math.min(42,m.frameH*.14)));ctx.stroke();ctx.restore()}if(isImage){ctx.drawImage(m.img,x-m.graphicW/2,y-m.graphicH/2,m.graphicW,m.graphicH)}else if(item.kind==="quantity"){const count=clamp(Number(item.value)||1,1,12),cols=Math.min(4,count),rows=Math.ceil(count/cols),gap=clamp(Number(o.quantityGap)||58,30,100),r=clamp(Number(o.quantitySize)||38,18,70)/2,startX=x-(cols-1)*gap/2,startY=y-(rows-1)*gap/2;ctx.fillStyle="#111";ctx.strokeStyle="#111";ctx.lineWidth=Math.max(3,r*.16);for(let i=0;i<count;i++){const cx=startX+(i%cols)*gap,cy=startY+Math.floor(i/cols)*gap;ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(cx,cy,r+5,0,Math.PI*2);ctx.stroke()}}else{ctx.fillStyle="#111";ctx.textAlign="center";ctx.textBaseline="middle";ctx.font=`700 ${Number(o.textSize)||66}px Arial`;ctx.fillText(String(item.text??item.value??""),x,y)}if(o.anchors==="dots"){const edge=(o.frames==="soft"?m.frameW:m.graphicW)/2,anchorOffset=edge+36;ctx.fillStyle="#111";ctx.beginPath();ctx.arc(side==="left"?x+anchorOffset:x-anchorOffset,y,13,0,Math.PI*2);ctx.fill();return{...m,anchorOffset}}return{...m,anchorOffset:(o.frames==="soft"?m.frameW:m.graphicW)/2}}
  async function render(pairs,o={},solution=false){const c=makeCanvas(),ctx=c.getContext("2d");ctx.fillStyle="#fff";ctx.fillRect(0,0,W,H);ctx.fillStyle="#111";ctx.textAlign="center";ctx.font=`700 ${o.titleSize||110}px Arial`;ctx.fillText(o.title||"Match the Pairs!",W/2,220);ctx.font=`${o.instructionSize||44}px Arial`;ctx.fillText(solution?"Solution":(o.instructions||"Draw a line to match each pair."),W/2,325);const n=pairs.length,perm=o.shuffle==="no"?[...Array(n).keys()]:shuffled(n,o.seed),leftX=620,rightX=1930,gap=await requiredGap(pairs,o),maxSpan=(n-1)*gap,startY=clamp(640+(2600-maxSpan)/2,560,900),leftPts=[],rightPts=[];for(let i=0;i<n;i++){const y=startY+i*gap,m=await drawItem(ctx,pairs[i].left,leftX,y,o,"left");leftPts.push([leftX+m.anchorOffset,y])}for(let row=0;row<n;row++){const y=startY+row*gap,idx=perm[row],m=await drawItem(ctx,pairs[idx].right,rightX,y,o,"right");rightPts[idx]=[rightX-m.anchorOffset,y]}if(solution){ctx.save();ctx.strokeStyle="#777";ctx.lineWidth=7;ctx.globalAlpha=.82;if(o.solutionStyle==="numbers"){ctx.font="700 44px Arial";ctx.fillStyle="#555";for(let i=0;i<n;i++){ctx.fillText(String(i+1),leftPts[i][0]+55,leftPts[i][1]);ctx.fillText(String(i+1),rightPts[i][0]-55,rightPts[i][1])}}else{for(let i=0;i<n;i++){ctx.beginPath();ctx.moveTo(...leftPts[i]);ctx.lineTo(...rightPts[i]);ctx.stroke()}}ctx.restore()}return c}
  return Object.freeze({render,requiredGap});
})();