"use strict";
(()=>{
  const $=id=>document.getElementById(id),canvas=$("page"),ctx=canvas.getContext("2d");
  const state={selected:null,assets:[],library:[],image:null,view:"task",rendered:null};
  let timer=null;
  const safe=s=>String(s||"").replace(/[&<>"']/g,"");
  const val=(id,f="")=>$(id)?.value??f;
  const num=(id,f)=>Number(val(id,f))||f;
  const isImage=a=>/^image\/(png|jpeg|webp|svg\+xml)$/i.test(String(a?.mime||""))||String(a?.dataUrl||"").startsWith("data:image/");
  const allLibrary=()=>{const active=FenixCore.getActiveProjectId(),seen=new Set(),out=[];for(const p of FenixCore.getProjects())for(const a of Object.values(p.assets||{})){if(!isImage(a))continue;const key=a.dataUrl||`${a.filename}|${a.sizeBytes}`;if(seen.has(key))continue;seen.add(key);out.push({...a,_projectId:p.id,_projectName:p.name,_active:p.id===active})}return out};
  function status(t,e=false){$("status").textContent=t;$("status").dataset.type=e?"error":"ok"}
  function current(){return state.assets.find(a=>a.id===state.selected)||null}
  function opts(){const a=current();return{type:val("type","half-vertical"),assetSource:"upload",asset:"custom",difficulty:val("difficulty","medium"),age:val("age","5–7"),scale:num("scale",94)/100,lineWidth:num("lineWidth",4),shadow:num("shadowStrength",10)/100,shadowScale:num("shadowScale",140)/100,shadowAssetScale:num("shadowAssetScale",100)/100,guide:$("showGuide").checked,dots:$("showDots").checked,grid:$("showGrid").checked,missingGuide:val("missingGuide","faint"),missingGuideOpacity:num("missingGuideOpacity",20)/100,missingGuideLineWidth:num("missingGuideLineWidth",1.5),missingPartSize:num("missingPartSize",35)/100,missingPartPosition:val("missingPartPosition","random"),title:val("title","Complete the Picture"),instruction:val("instruction","Draw the missing half of the picture."),count:1,seed:val("seed","fenix-ctp"),seriesMode:"selected",assetRef:a?.id||null}}
  function loadAsset(a){return new Promise((res,rej)=>{if(!a)return rej(new Error("Brak assetu"));const im=new Image();im.onload=()=>res(im);im.onerror=()=>rej(new Error("Nie udało się wczytać assetu."));im.src=a.dataUrl})}
  function renderAssets(){state.assets=FenixCore.listAssets().filter(isImage);if(state.selected&&!state.assets.some(a=>a.id===state.selected))state.selected=null;if(!state.selected&&state.assets.length)state.selected=state.assets[0].id;const g=$("assetGrid");g.innerHTML="";state.assets.forEach(a=>{const b=document.createElement("button");b.type="button";b.className=`asset-card${a.id===state.selected?" selected":""}`;b.dataset.id=a.id;b.innerHTML=`<img src="${a.dataUrl}" alt=""><strong>${safe(a.name||a.filename||"Asset")}</strong><small>${safe(a.mime||"")}</small>`;b.onclick=()=>{state.selected=a.id;renderAssets();schedule()};g.appendChild(b)});$("assetEmpty").hidden=!!state.assets.length;$("selectedName").textContent=current()?.name||current()?.filename||"Brak assetu"}
  function renderLibrary(){state.library=allLibrary();const g=$("libraryGrid");g.innerHTML="";state.library.forEach(a=>{const b=document.createElement("button");b.type="button";b.className="asset-card";b.innerHTML=`<img src="${a.dataUrl}" alt=""><strong>${safe(a.name||a.filename||"Asset")}</strong><small>${safe(a._projectName||"")}</small>`;b.onclick=()=>{let hit=state.assets.find(x=>x.dataUrl===a.dataUrl);if(!hit)hit=FenixCore.putAsset({name:a.name,filename:a.filename,mime:a.mime,dataUrl:a.dataUrl,source:"fenix-library",width:a.width,height:a.height,sizeBytes:a.sizeBytes,tags:a.tags||["content"],meta:{...(a.meta||{}),librarySourceProject:a._projectName}});state.selected=hit.id;showSource("project");renderAssets();renderLibrary();schedule()};g.appendChild(b)});$("libraryEmpty").hidden=!!state.library.length}
  function showSource(which){$("projectPane").hidden=which!=="project";$("libraryPane").hidden=which!=="library";$("tabProject").classList.toggle("active",which==="project");$("tabLibrary").classList.toggle("active",which==="library");if(which==="library")renderLibrary()}
  async function importFiles(files){for(const file of files){const ok=["image/png","image/jpeg","image/webp","image/svg+xml"].includes(file.type)||/\.(png|jpe?g|webp|svg)$/i.test(file.name);if(!ok)continue;const dataUrl=await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(String(r.result));r.onerror=rej;r.readAsDataURL(file)});const a=FenixCore.putAsset({name:file.name.replace(/\.[^.]+$/,""),filename:file.name,mime:file.type||(/\.svg$/i.test(file.name)?"image/svg+xml":"image/png"),dataUrl,source:"complete-picture",sizeBytes:file.size,tags:["content"]});state.selected=a.id}renderAssets();renderLibrary();schedule()}
  const defaults={"half-vertical":"Draw the missing half of the picture.","half-horizontal":"Draw the missing bottom half of the picture.","shadow-trace":"Trace the picture by following the faint guide.","grid-copy":"Copy the picture into the empty grid.","missing-part":"Draw the missing part of the picture.","mirror-pair":"Draw the mirror image on the other side."};
  function updateType(){const t=val("type");$("instruction").value=defaults[t]||"Complete the picture.";const tracing=t==="shadow-trace",missing=t==="missing-part";$("shadowStrengthWrap").hidden=!tracing;$("shadowScaleWrap").hidden=!tracing;$("shadowAssetScaleWrap").hidden=!tracing;$("shadowTraceNote").hidden=!tracing;$("missingGuideWrap").hidden=!["half-vertical","half-horizontal","missing-part","mirror-pair"].includes(t);$("missingPartWrap").hidden=!missing;schedule()}
  function hash(value){let h=2166136261;for(const c of String(value||"fenix"))h=Math.imul(h^c.charCodeAt(0),16777619);return h>>>0}
  function seededRandom(seed){let h=hash(seed);return()=>((h=Math.imul(h^h>>>15,2246822507)^Math.imul(h^h>>>13,3266489909),((h^h>>>16)>>>0)/4294967296))}
  function missingGeometry(o){const random=seededRandom(o.seed),size=Math.max(.10,Math.min(.60,o.missingPartSize||.35)),r=45+size*180,offset=135;let angle=random()*Math.PI*2;if(o.missingPartPosition==="top")angle=-Math.PI/2;else if(o.missingPartPosition==="bottom")angle=Math.PI/2;else if(o.missingPartPosition==="left")angle=Math.PI;else if(o.missingPartPosition==="right")angle=0;return{mx:425+Math.cos(angle)*offset,my:550+Math.sin(angle)*offset,r}}
  function assetFrame(image,o){const iw=image.naturalWidth||1,ih=image.naturalHeight||1,maxW=430*o.scale,maxH=560*o.scale,ratio=Math.min(maxW/iw,maxH/ih),w=iw*ratio,h=ih*ratio;return{left:425-w/2,top:550-h/2,w,h,iw,ih}}
  function rasterMaskFromImage(image){const s=900,c=document.createElement("canvas");c.width=s;c.height=s;const x=c.getContext("2d"),iw=image.naturalWidth||s,ih=image.naturalHeight||s,fit=Math.min(s/iw,s/ih)*.88,dw=iw*fit,dh=ih*fit,ox=(s-dw)/2,oy=(s-dh)/2;x.drawImage(image,ox,oy,dw,dh);const data=x.getImageData(0,0,s,s).data,ink=new Uint8Array(s*s);for(let i=0;i<ink.length;i++){const k=i*4,a=data[k+3],lum=(data[k]+data[k+1]+data[k+2])/3;if(a>16&&lum<248)ink[i]=1}let work=ink;for(let pass=0;pass<2;pass++){const next=work.slice();for(let y=1;y<s-1;y++)for(let xx=1;xx<s-1;xx++){const i=y*s+xx;if(work[i])continue;if(work[i-1]||work[i+1]||work[i-s]||work[i+s]||work[i-s-1]||work[i-s+1]||work[i+s-1]||work[i+s+1])next[i]=1}work=next}const outside=new Uint8Array(s*s),qx=new Int32Array(s*s),qy=new Int32Array(s*s);let head=0,tail=0;const push=(xx,yy)=>{if(xx<0||yy<0||xx>=s||yy>=s)return;const i=yy*s+xx;if(work[i]||outside[i])return;outside[i]=1;qx[tail]=xx;qy[tail]=yy;tail++};for(let xx=0;xx<s;xx++){push(xx,0);push(xx,s-1)}for(let yy=0;yy<s;yy++){push(0,yy);push(s-1,yy)}while(head<tail){const xx=qx[head],yy=qy[head++];push(xx-1,yy);push(xx+1,yy);push(xx,yy-1);push(xx,yy+1)}const solid=new Uint8Array(s*s);for(let i=0;i<solid.length;i++)if(work[i]||!outside[i])solid[i]=1;return{solid,s,ox,oy,dw,dh}}
  function largestComponent(m){const {solid,s}=m,seen=new Uint8Array(s*s),queue=new Int32Array(s*s);let best=[];for(let i=0;i<solid.length;i++){if(!solid[i]||seen[i])continue;let h=0,t=0;queue[t++]=i;seen[i]=1;const comp=[];while(h<t){const cur=queue[h++];comp.push(cur);const x=cur%s;for(const n of [cur-1,cur+1,cur-s,cur+s]){if(n<0||n>=solid.length||seen[n]||!solid[n])continue;const nx=n%s;if(Math.abs(nx-x)>1)continue;seen[n]=1;queue[t++]=n}}if(comp.length>best.length)best=comp}if(!best.length)throw new Error("Nie udało się znaleźć głównego kształtu SVG.");const mask=new Uint8Array(s*s);for(const i of best)mask[i]=1;return{mask,s}}
  const dirs=[[1,0],[1,1],[0,1],[-1,1],[-1,0],[-1,-1],[0,-1],[1,-1]];
  function dirIndex(dx,dy){return dirs.findIndex(d=>d[0]===dx&&d[1]===dy)}
  function traceOuter(m){const {mask,s}=m;let start=null;for(let y=1;y<s-1&&!start;y++)for(let x=1;x<s-1;x++){const i=y*s+x;if(mask[i]&&!mask[i-s]){start={x,y};break}}if(!start)throw new Error("Nie udało się znaleźć zewnętrznej krawędzi.");let cur=start,back={x:start.x-1,y:start.y},firstNext=null;const path=[{...start}];for(let step=0;step<s*s*3;step++){let bi=dirIndex(back.x-cur.x,back.y-cur.y);if(bi<0)bi=4;let found=null,newBack=null;for(let k=1;k<=8;k++){const di=(bi+k)%8,nx=cur.x+dirs[di][0],ny=cur.y+dirs[di][1];if(nx<0||ny<0||nx>=s||ny>=s)continue;if(mask[ny*s+nx]){found={x:nx,y:ny};const pi=(di+7)%8;newBack={x:cur.x+dirs[pi][0],y:cur.y+dirs[pi][1]};break}}if(!found)break;if(!firstNext)firstNext={...found};else if(cur.x===start.x&&cur.y===start.y&&found.x===firstNext.x&&found.y===firstNext.y)break;back=newBack;cur=found;path.push({...cur});if(path.length>12&&cur.x===start.x&&cur.y===start.y)break}if(path.length<20)throw new Error("Kontur SVG jest zbyt krótki lub nieciągły.");return path}
  function smooth(path,windowSize=4){const n=path.length,out=[];for(let i=0;i<n;i++){let sx=0,sy=0,c=0;for(let k=-windowSize;k<=windowSize;k++){const p=path[(i+k+n)%n];sx+=p.x;sy+=p.y;c++}out.push({x:sx/c,y:sy/c})}return out}
  function buildFullGuideLayer(o,image){const layer=document.createElement("canvas");layer.width=850;layer.height=1100;const x=layer.getContext("2d"),raw=rasterMaskFromImage(image),path=smooth(traceOuter(largestComponent(raw))),frame=assetFrame(image,o),full=path.map(p=>({x:frame.left+((p.x-raw.ox)/raw.dw)*frame.w,y:frame.top+((p.y-raw.oy)/raw.dh)*frame.h})),alpha=Math.max(.05,Math.min(.45,o.missingGuideOpacity||.20)),guideWidth=Math.max(.75,Math.min(4,o.missingGuideLineWidth||1.5));x.save();x.strokeStyle=`rgba(70,70,70,${alpha})`;x.lineWidth=guideWidth;x.lineJoin="round";x.lineCap="round";x.beginPath();full.forEach((p,i)=>i?x.lineTo(p.x,p.y):x.moveTo(p.x,p.y));x.closePath();x.stroke();x.restore();return layer}
  function applyMissingPartGuide(target,o,image){if(o.type!=="missing-part"||o.missingGuide==="none"||!image)return target;const layer=buildFullGuideLayer(o,image),g=missingGeometry(o),x=target.getContext("2d");x.save();x.beginPath();x.arc(g.mx,g.my,g.r,0,Math.PI*2);x.clip();x.drawImage(layer,0,0);x.restore();return target}
  function renderPage(o,{solution=false}={}){const coreOpts=o.type==="missing-part"&&!solution?{...o,missingGuide:"none"}:o;const out=FenixCompletePicture.render(coreOpts,o.seed,0,{solution,scale:1,customImage:state.image});return solution?out:applyMissingPartGuide(out,o,state.image)}
  async function render(){const a=current();if(!a){state.rendered=null;canvas.width=850;canvas.height=1100;ctx.fillStyle="#fff";ctx.fillRect(0,0,850,1100);ctx.fillStyle="#66717d";ctx.textAlign="center";ctx.font="700 30px Arial";ctx.fillText("Wybierz asset SVG lub PNG",425,540);return status("Wybierz asset z projektu, Biblioteki Feniksa albo dodaj go z PC.",true)}try{state.image=await loadAsset(a);const o=opts();state.rendered=renderPage(o,{solution:state.view==="solution"});canvas.width=850;canvas.height=1100;ctx.clearRect(0,0,850,1100);ctx.drawImage(state.rendered,0,0);$("selectedName").textContent=a.name||a.filename||"Asset";status(`Podgląd gotowy · ${$("type").selectedOptions[0].textContent}.`)}catch(e){console.error(e);status(e.message||"Błąd podglądu",true)}}
  const schedule=()=>{clearTimeout(timer);timer=setTimeout(render,120)};
  function save(){const a=current();if(!a||!state.rendered)return status("Najpierw przygotuj poprawny podgląd.",true);const o=opts(),task=renderPage(o,{solution:false}),solution=renderPage(o,{solution:true});FenixCore.addPage({module:"complete-picture",title:o.title,seed:o.seed,recipe:{module:"complete-picture",seed:o.seed,title:o.title,settings:o,content:{assetSource:"project",assetRef:a.id},meta:{createdWith:"FENIX PC",moduleVersion:15}},preview:{imageData:task.toDataURL("image/png")},solution:{available:true,imageData:solution.toDataURL("image/png")},source:{app:"fenix-desktop",version:"0.33.0",format:"native"}});status("Dodano stronę Complete the Picture wraz z Solution do projektu.")}
  $("tabProject").onclick=()=>showSource("project");$("tabLibrary").onclick=()=>showSource("library");$("importAsset").onclick=()=>$("assetFile").click();$("assetFile").onchange=async()=>{await importFiles([...($("assetFile").files||[])]);$("assetFile").value=""};$("type").onchange=updateType;$("taskTab").onclick=()=>{state.view="task";$("taskTab").classList.add("active");$("solutionTab").classList.remove("active");render()};$("solutionTab").onclick=()=>{state.view="solution";$("solutionTab").classList.add("active");$("taskTab").classList.remove("active");render()};$("generate").onclick=render;$("cart").onclick=save;$("png").onclick=()=>state.rendered&&FenixCore.downloadCanvas(state.rendered,`complete-picture-${state.view}-${Date.now()}.png`);
  ["difficulty","age","scale","lineWidth","shadowStrength","shadowScale","shadowAssetScale","missingGuide","missingGuideOpacity","missingGuideLineWidth","missingPartSize","missingPartPosition","showGuide","showDots","showGrid","title","instruction","seed"].forEach(id=>$(id)?.addEventListener(["title","instruction","seed","scale","lineWidth","shadowStrength","shadowScale","shadowAssetScale","missingGuideOpacity","missingGuideLineWidth","missingPartSize"].includes(id)?"input":"change",schedule));
  window.addEventListener("fenix-state-change",()=>{renderAssets();renderLibrary();schedule()});const p=FenixCore.getActiveProject();$("projectInfo").textContent=`Aktywny projekt: ${p.name} · ${p.format}`;renderAssets();renderLibrary();showSource("project");updateType();render();
})();