"use strict";
(()=>{
  const $=id=>document.getElementById(id);
  const requestedId=new URLSearchParams(location.search).get("id");
  const moduleOf=p=>p?.module||p?.recipe?.module;
  const pages=()=>FenixCore.getCart().filter(p=>moduleOf(p)==="logic-studio");
  const safe=s=>String(s||"").replace(/[&<>"']/g,"");
  function typeLabel(type){return ({sequence:"Sekwencja",odd:"Co nie pasuje?",matrix:"Brakujący element",sudoku:"Sudoku 4×4",analogy:"Analogia"})[type]||type||"Logic"}
  function installUi(){
    const actions=document.querySelector(".actions"),status=$("status");
    if(actions&&!$("newPage")){const b=document.createElement("button");b.id="newPage";b.type="button";b.textContent="Nowa strona";actions.insertBefore(b,$("cart"));}
    if(actions){actions.classList.add("logic-main-actions");const style=document.createElement("style");style.textContent=`.logic-main-actions{display:grid!important;grid-template-columns:repeat(5,minmax(0,1fr));gap:10px!important}.logic-main-actions button{appearance:none!important;-webkit-appearance:none!important;color:#fff!important;font-weight:900!important;border-radius:11px!important;padding:12px 14px!important;border:1px solid transparent!important;background-image:none!important}.logic-main-actions #generate{background:#2563eb!important;border-color:#1d4ed8!important}.logic-main-actions #newPage{background:#111!important;border-color:#111!important}.logic-main-actions #cart{background:#f97316!important;border-color:#ea580c!important}.logic-main-actions #randomSeed,.logic-main-actions #png{background:#64748b!important;border-color:#475569!important}.logic-pages{margin-top:22px;padding-top:18px;border-top:1px solid #d7dce3}.logic-pages-head{display:flex;justify-content:space-between;align-items:flex-start;gap:12px}.logic-pages-head h2{margin:0 0 5px;font-size:18px}.logic-pages-head strong{background:#f1f5f9;border-radius:999px;padding:8px 12px;white-space:nowrap}.logic-pages-list{display:grid;gap:10px;margin-top:13px}.logic-page{display:grid;grid-template-columns:58px minmax(0,1fr) auto;gap:12px;align-items:center;padding:10px;border:1px solid #d7dce3;border-radius:12px;background:#fff}.logic-page.current{border:2px solid #f97316;background:#fff7ed}.logic-page-thumb{width:56px;height:56px;border-radius:10px;background:#f4f6f8;display:grid;place-items:center;font-size:25px}.logic-page-copy{display:grid;gap:3px;min-width:0}.logic-page-copy strong{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.logic-page-copy small{color:#66717d}.logic-page-actions{display:flex;gap:8px}.logic-page-actions button{border:1px solid #d7dce3;border-radius:9px;padding:8px 11px;background:#f8fafc;cursor:pointer}.logic-page-actions .delete{color:#b42318}.logic-pages-empty{padding:14px;border:1px dashed #bcc4ce;border-radius:10px;color:#66717d}@media(max-width:760px){.logic-main-actions{grid-template-columns:1fr 1fr!important}.logic-page{grid-template-columns:48px minmax(0,1fr)}.logic-page-thumb{width:46px;height:46px}.logic-page-actions{grid-column:1/-1;justify-content:flex-end}}`;document.head.appendChild(style)}
    if(status&&!$("logicPages")){const section=document.createElement("section");section.id="logicPages";section.className="logic-pages";section.innerHTML='<div class="logic-pages-head"><div><h2>Strony Logic Studio w projekcie</h2><p class="hint">Edytuj lub usuń zapisane strony bez wracania do Dashboardu.</p></div><strong id="logicPagesCount">0 stron</strong></div><div id="logicPagesList" class="logic-pages-list"></div>';status.insertAdjacentElement("afterend",section)}
  }
  function render(){const list=pages(),box=$("logicPagesList"),count=$("logicPagesCount");if(!box||!count)return;count.textContent=`${list.length} ${list.length===1?"strona":"stron"}`;if(!list.length){box.innerHTML='<div class="logic-pages-empty">Nie zapisano jeszcze żadnej strony Logic Studio.</div>';return}box.innerHTML=list.map((p,i)=>{const s=p.recipe?.settings||{},current=String(p.id)===String(requestedId);return `<article class="logic-page${current?' current':''}"><div class="logic-page-thumb">◈</div><div class="logic-page-copy"><strong>Logic #${String(i+1).padStart(2,'0')} · ${safe(p.title||'Logic Challenge')}</strong><small>${safe(typeLabel(s.type))} · ${safe(s.difficulty||'—')} · ${safe(s.age||'—')}${current?' · EDYCJA':''}</small></div><div class="logic-page-actions"><button type="button" data-edit="${p.id}">Edytuj</button><button type="button" class="delete" data-delete="${p.id}">Usuń</button></div></article>`}).join("");box.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>location.href=`${location.pathname}?id=${encodeURIComponent(b.dataset.edit)}`);box.querySelectorAll("[data-delete]").forEach(b=>b.onclick=()=>{const p=FenixCore.getCart().find(x=>String(x.id)===String(b.dataset.delete));if(!p||!confirm(`Usunąć stronę „${p.title||'Logic Challenge'}” z projektu?`))return;FenixCore.removePage(b.dataset.delete);if(String(b.dataset.delete)===String(requestedId)){location.href=location.pathname;return}render()})}
  async function init(){await FenixCore.ready;installUi();$("newPage")?.addEventListener("click",()=>location.href=location.pathname);render();if(requestedId)setTimeout(()=>$("generate")?.click(),180);window.addEventListener("fenix-state-change",render)}
  void init();
})();
