"use strict";
(()=>{
  const $=id=>document.getElementById(id),canvas=$("page"),ctx=canvas.getContext("2d"),editId=new URLSearchParams(location.search).get("id")||null;
  const SYMBOLS=["●","▲","■","◆","★","♥","☀","✿"],state={pages:[],index:0,view:"task",selected:new Set(),oddId:null,images:new Map(),building:0};let timer=null;
  const clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),pick=(a,r)=>a[Math.floor(r()*a.length)],safe=s=>String(s||"").replace(/[&<>"']/g,"");
  function seeded(seed){let h=2166136261;for(const c of String(seed||"fenix"))h=Math.imul(h^c.charCodeAt(0),16777619);return()=>{h+=0x6D2B79F5;let t=h;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
  function shuffle(a,r){const out=a.slice();for(let i=out.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[out[i],out[j]]=[out[j],out[i]]}return out}
  const instructions={sequence:"Continue the sequence.",odd:"Circle the one that does not belong.",matrix:"Complete the matrix.",sudoku:"Use each picture once in every row and column.",analogy:"Complete the analogy."};
  const projectAssets=()=>FenixCore.listAssets().filter(a=>String(a.dataUrl||"").startsWith("data:image/"));
  function allLibrary(){const active=FenixCore.getActiveProjectId(),seen=new Set(),out=[];for(const p of FenixCore.getProjects())for(const a of Object.values(p.assets||{})){if(!String(a.dataUrl||"").startsWith("data:image/"))continue;const key=a.dataUrl||`${a.filename}|${a.sizeBytes}`;if(seen.has(key))continue;seen.add(key);out.push({...a,_projectId:p.id,_projectName:p.name,_active:p.id===active})}return out}
  const assetById=id=>projectAssets().find(a=>a.id===id)||null,selectedAssets=()=>[...state.selected].map(assetById).filter(Boolean);
  function loadImage(a){if(state.images.has(a.id))return state.images.get(a.id);const p=new Promise(resolve=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>resolve(null);im.src=a.dataUrl});state.images.set(a.id,p);return p}
  function opts(){const type=$("type").value;return{type,title:$("title").value||"Logic Challenge",instructions:$("instructions").value||instructions[type],seed:$("seed").value||"fenix-logic-001",difficulty:$("difficulty").value,age:$("age").value,language:$("language").value,count:clamp(Number($("count").value)||1,1,20),range:clamp(Number($("range").value)||20,5,100),elementMode:$("elementMode").value,assetRefs:[...state.selected],oddRef:state.oddId}}
  const makeCanvas=()=>{const c=document.createElement("canvas");c.width=850;c.height=1100;return c};
  function base(x,o){x.fillStyle="#fff";x.fillRect(0,0,850,1100);x.strokeStyle="#111827";x.lineWidth=3;x.strokeRect(36,36,778,1028);x.fillStyle="#111827";x.textAlign="center";x.font="700 38px Arial";x.fillText(String(o.title).slice(0,60),425,92);x.font="20px Arial";x.fillText(String(o.instructions).slice(0,95),425,132)}
  function solutionBase(x,o){x.fillStyle="#fff";x.fillRect(0,0,850,1100);x.strokeStyle="#111827";x.lineWidth=3;x.strokeRect(36,36,778,1028);x.fillStyle="#111827";x.textAlign="center";x.font="700 34px Arial";x.fillText(`Solution — ${String(o.title).slice(0,50)}`,425,90)}
  function circleMark(x,cx,cy,r=25){x.save();x.strokeStyle="#111";x.lineWidth=4;x.beginPath();x.arc(cx,cy,r,0,Math.PI*2);x.stroke();x.restore()}
  function drawAsset(x,img,cx,cy,size=66){if(!img)return;const iw=img.naturalWidth||img.width||1,ih=img.naturalHeight||img.height||1,fit=Math.min(size/iw,size/ih),w=iw*fit,h=ih*fit;x.drawImage(img,cx-w/2,cy-h/2,w,h)}
  function requirements(type){if(type==="sudoku")return{min:4,max:4,exact:true,label:"Sudoku 4×4 potrzebuje dokładnie 4 assetów."};if(type==="analogy")return{min:4,label:"Analogia potrzebuje minimum 4 assetów."};if(type==="matrix")return{min:3,label:"Matrix potrzebuje minimum 3 assetów."};if(type==="odd")return{min:2,label:"„Co nie pasuje?” potrzebuje minimum 2 assetów oraz wskazanego elementu OBCEGO."};return{min:2,label:"Sekwencja potrzebuje minimum 2 assetów."}}
  function selectionReady(type,n){const req=requirements(type);return req.exact?n===req.min:n>=req.min}
  function normalizeSudokuSelection(){if($("type").value!=="sudoku"||state.selected.size<=4)return;state.selected=new Set([...state.selected].slice(0,4));if(state.oddId&&!state.selected.has(state.oddId))state.oddId=null}
  function updateSudokuSlots(){const sudoku=$("type").value==="sudoku"&&$("elementMode").value==="assets",box=$("sudokuSet"),slots=$("sudokuSlots"),count=$("sudokuCount");box?.classList.toggle("on",sudoku);if(!sudoku||!slots||!count)return;const chosen=selectedAssets().slice(0,4);count.textContent=`${chosen.length} / 4`;slots.innerHTML="";for(let i=0;i<4;i++){const slot=document.createElement("div");slot.className="sudoku-slot";const a=chosen[i];slot.innerHTML=a?`<img src="${a.dataUrl}" alt="${safe(a.name||a.filename||"")}">`:`${i+1}`;slots.appendChild(slot)}}
  function updateAssetStatus(){normalizeSudokuSelection();const type=$("type").value,mode=$("elementMode").value,req=requirements(type),n=state.selected.size,box=$("assetStatus"),hint=$("assetHint");if(mode==="symbols"){box.textContent="Tryb symboli — assety nie są używane.";box.className="asset-status ready";updateSudokuSlots();return}if(type==="odd")hint.textContent="Wybierz co najmniej 2 assety i oznacz jeden jako OBCY.";else if(type==="sudoku")hint.textContent="Sudoku 4×4 używa dokładnie 4 różnych assetów.";else hint.textContent="Wybierz assety używane przez aktualny typ ćwiczenia.";const oddOk=type!=="odd"||Boolean(state.oddId&&state.selected.has(state.oddId)),ready=selectionReady(type,n)&&oddOk;box.textContent=ready?(type==="sudoku"?"Gotowe · komplet 4 / 4 assetów dla Sudoku.":`Gotowe · wybrano ${n} assetów${type==="odd"?" · OBCY ustawiony":""}.`):`${req.label} Wybrano: ${n}${type==="sudoku"?" / 4":""}.`;box.className=`asset-status ${ready?"ready":"warn"}`;updateSudokuSlots()}
  function toggleAsset(id){if(state.selected.has(id)){state.selected.delete(id);if(state.oddId===id)state.oddId=null}else{if($("type").value==="sudoku"&&state.selected.size>=4)return;state.selected.add(id)}renderAssetPanels();schedule()}
  function setOdd(id,e){e?.preventDefault();e?.stopPropagation();state.selected.add(id);state.oddId=id;renderAssetPanels();schedule()}
  function assetCard(a,library=false){const selected=state.selected.has(a.id),odd=state.oddId===a.id,slot=[...state.selected].indexOf(a.id)+1,b=document.createElement("div");b.className=`logic-asset${selected?" selected":""}${odd?" odd":""}`;const label=$("type").value==="sudoku"&&selected?`SUDOKU ${slot}/4`:odd?"OBCY":selected?"WYBRANY":"Wybierz";b.innerHTML=`<button type="button" data-pick><img src="${a.dataUrl}" alt=""><strong>${safe(a.name||a.filename||"Asset")}</strong><small>${library?safe(a._projectName||""):label}</small></button>${$("type").value==="odd"&&selected?`<button type="button" class="odd-action">${odd?"✓ OBCY":"Ustaw jako OBCY"}</button>`:""}`;b.querySelector("[data-pick]").onclick=()=>{if(library&&!a._active){let copy=projectAssets().find(x=>x.dataUrl===a.dataUrl);if(!copy)copy=FenixCore.putAsset({name:a.name,filename:a.filename,mime:a.mime,dataUrl:a.dataUrl,source:"fenix-library",tags:a.tags||["content"],meta:{...(a.meta||{}),librarySourceProject:a._projectName}});if($("type").value==="sudoku"&&state.selected.size>=4&&!state.selected.has(copy.id))return;state.selected.add(copy.id);renderAssetPanels();schedule();return}toggleAsset(a.id)};b.querySelector(".odd-action")?.addEventListener("click",e=>setOdd(a.id,e));return b}
  function renderAssetPanels(){normalizeSudokuSelection();const grid=$("assetGrid");grid.innerHTML="";projectAssets().forEach(a=>grid.appendChild(assetCard(a)));const lg=$("libraryGrid");lg.innerHTML="";allLibrary().forEach(a=>lg.appendChild(assetCard(a,true)));updateAssetStatus()}
  function showSource(which){$("projectPane").hidden=which!=="project";$("libraryPane").hidden=which!=="library"}
  async function assetBundle(o,r){if(o.elementMode!=="assets")return null;const assets=o.assetRefs.map(assetById).filter(Boolean);if(!selectionReady(o.type,assets.length))return null;const chosen=o.type==="sudoku"?assets.slice(0,4):shuffle(assets,r),images=new Map;await Promise.all(chosen.map(async a=>images.set(a.id,await loadImage(a))));return{assets:chosen,images,odd:o.oddRef?assetById(o.oddRef):null}}
  async function renderOne(o,seed){const r=seeded(seed),page=makeCanvas(),solution=makeCanvas(),p=page.getContext("2d"),s=solution.getContext("2d");base(p,o);solutionBase(s,o);p.fillStyle=s.fillStyle="#111";p.strokeStyle=s.strokeStyle="#111";p.textAlign=s.textAlign="center";const bundle=await assetBundle(o,r),useAssets=Boolean(bundle);
    if(o.type==="odd"){if(useAssets){const odd=bundle.odd&&o.assetRefs.includes(bundle.odd.id)?bundle.odd:bundle.assets[bundle.assets.length-1],commons=bundle.assets.filter(a=>a.id!==odd.id);for(let row=0;row<6;row++){const n=o.difficulty==="hard"?7:o.difficulty==="easy"?4:5,common=pick(commons,r),pos=Math.floor(r()*n);for(let i=0;i<n;i++){const x=145+i*105,y=245+row*120,a=i===pos?odd:common;drawAsset(p,bundle.images.get(a.id),x,y-16,66);drawAsset(s,bundle.images.get(a.id),x,y-16,66);if(i===pos)circleMark(s,x,y-16,42)}}}else for(let row=0;row<6;row++){const n=o.difficulty==="hard"?7:o.difficulty==="easy"?4:5,common=pick(SYMBOLS,r),odd=pick(SYMBOLS.filter(x=>x!==common),r),pos=Math.floor(r()*n);p.font=s.font="46px Arial";for(let i=0;i<n;i++){const x=145+i*105,y=245+row*120,v=i===pos?odd:common;p.fillText(v,x,y);s.fillText(v,x,y);if(i===pos)circleMark(s,x,y-15,34)}}}
    else if(o.type==="sudoku"){const grid=[[0,1,2,3],[2,3,0,1],[1,0,3,2],[3,2,1,0]],blank=new Set(["0,0","1,2","2,1","3,3"]),arr=useAssets?bundle.assets.slice(0,4):SYMBOLS.slice(0,4),gridTop=useAssets?330:270;if(useAssets){for(const x of[p,s]){x.fillStyle="#111827";x.textAlign="center";x.font="700 17px Arial";x.fillText("PICTURE SET",425,178)}arr.forEach((a,i)=>{const cx=290+i*90;drawAsset(p,bundle.images.get(a.id),cx,225,58);drawAsset(s,bundle.images.get(a.id),cx,225,58)})}for(let y=0;y<4;y++)for(let x=0;x<4;x++){const px=215+x*105,py=gridTop+y*105,val=arr[grid[y][x]];p.strokeRect(px,py,105,105);s.strokeRect(px,py,105,105);if(useAssets){const img=bundle.images.get(val.id);if(!blank.has(`${y},${x}`))drawAsset(p,img,px+52,py+52,70);drawAsset(s,img,px+52,py+52,70)}else{p.font=s.font="46px Arial";if(!blank.has(`${y},${x}`))p.fillText(val,px+52,py+68);s.fillText(val,px+52,py+68)}}}
    else if(o.type==="matrix"){const arr=useAssets?bundle.assets.slice(0,3):shuffle(SYMBOLS,r).slice(0,3);for(let y=0;y<3;y++)for(let x=0;x<3;x++){const px=245+x*120,py=280+y*120,val=arr[(x+y)%3],missing=x===2&&y===2;p.strokeRect(px,py,120,120);s.strokeRect(px,py,120,120);if(useAssets){if(!missing)drawAsset(p,bundle.images.get(val.id),px+60,py+60,78);else{p.font="50px Arial";p.fillText("?",px+60,py+78)}drawAsset(s,bundle.images.get(val.id),px+60,py+60,78)}else{p.font=s.font="48px Arial";p.fillText(missing?"?":val,px+60,py+75);s.fillText(val,px+60,py+75)}}}
    else if(o.type==="analogy"){if(useAssets){const arr=bundle.assets.slice(0,4),correct=arr[3],positions=[[315,300],[535,300],[315,455]];positions.forEach((pos,i)=>{drawAsset(p,bundle.images.get(arr[i].id),pos[0],pos[1],90);drawAsset(s,bundle.images.get(arr[i].id),pos[0],pos[1],90)});p.font=s.font="48px Arial";p.fillText("→",425,315);s.fillText("→",425,315);p.fillText("→",425,470);s.fillText("→",425,470);p.fillText("?",535,470);drawAsset(s,bundle.images.get(correct.id),535,455,90)}else{const values=shuffle(SYMBOLS,r).slice(0,4);p.font=s.font="58px Arial";p.fillText(`${values[0]}  →  ${values[1]}`,425,310);p.fillText(`${values[2]}  →  ?`,425,440);s.fillText(`${values[0]}  →  ${values[1]}`,425,310);s.fillText(`${values[2]}  →  ${values[3]}`,425,440)}}
    else{if(useAssets){const pattern=bundle.assets.slice(0,Math.min(3,bundle.assets.length));for(let row=0;row<6;row++){const n=o.difficulty==="hard"?9:7;for(let i=0;i<n;i++){const x=95+i*90,y=245+row*115,a=pattern[i%pattern.length];if(i===n-1){p.font="48px Arial";p.fillText("?",x,y)}else drawAsset(p,bundle.images.get(a.id),x,y-18,62);drawAsset(s,bundle.images.get(a.id),x,y-18,62)}}}else for(let row=0;row<6;row++){const pattern=shuffle(SYMBOLS,r).slice(0,3),n=o.difficulty==="hard"?9:7;p.font=s.font="48px Arial";for(let i=0;i<n;i++){const x=95+i*90,y=245+row*115,val=pattern[i%3];p.fillText(i===n-1?"?":val,x,y);s.fillText(val,x,y)}}}
    return{pageCanvas:page,solutionCanvas:solution,hasSolution:true,seed,options:{...o}}}
  function show(){const item=state.pages[state.index];if(!item)return;canvas.width=850;canvas.height=1100;ctx.clearRect(0,0,850,1100);ctx.drawImage(state.view==="solution"?item.solutionCanvas:item.pageCanvas,0,0);$("pageCounter").textContent=`${state.index+1} / ${state.pages.length}`}
  async function build(){const seq=++state.building,o=opts(),pages=[];$("status").textContent="Generuję Logic…";for(let i=0;i<o.count;i++)pages.push(await renderOne(o,`${o.seed}-${i+1}`));if(seq!==state.building)return;state.pages=pages;state.index=0;show();$("status").textContent=`Wygenerowano ${pages.length} stron.`}
  function schedule(){clearTimeout(timer);timer=setTimeout(build,140)}
  function pagePayload(item,index){const o=item.options,page={module:"logic-studio",title:o.title,seed:item.seed,recipe:{module:"logic-studio",seed:item.seed,title:o.title,settings:{type:o.type,difficulty:o.difficulty,age:o.age,language:o.language,range:o.range,instructions:o.instructions,pageIndex:index,elementMode:o.elementMode},content:{assetRefs:o.assetRefs,oddRef:o.oddRef},meta:{createdWith:"FPP/FPM Shared Logic",moduleVersion:5}},solution:{available:true,imageData:null},source:{app:"fenix-fp-preview",version:"shared-logic-1",format:"native"}};return FenixPageSchema.normalize(window.FenixModuleContracts?.stamp?FenixModuleContracts.stamp(page):page)}
  function save(){if(!state.pages.length)return;const o=opts(),req=requirements(o.type);if(o.elementMode==="assets"&&(!selectionReady(o.type,o.assetRefs.length)||(o.type==="odd"&&!o.oddRef))){$("status").textContent=`Nie zapisano: ${req.label}`;return}if(editId){FenixCore.updatePage(editId,pagePayload(state.pages[0],0));$("cart").textContent="✓ Zapisano";return}state.pages.forEach((item,index)=>FenixCore.addPage(pagePayload(item,index)));$("cart").textContent=state.pages.length===1?"✓ Dodano stronę":"✓ Dodano strony"}
  function loadEdit(){if(!editId)return;const raw=FenixCore.getCart().find(p=>String(p.id)===String(editId));if(!raw||FenixPageSchema.moduleOf(raw)!=="logic-studio")return;const p=FenixPageSchema.normalize(raw),s=p.recipe?.settings||{},c=p.recipe?.content||{};$("count").value=1;["type","difficulty","age","language","range","instructions","elementMode"].forEach(id=>{if(s[id]!=null&&$(id))$(id).value=s[id]});$("title").value=p.title||"Logic Challenge";$("seed").value=String(p.recipe?.seed||"fenix-logic-001").replace(/-\d+$/,'');state.selected=new Set(s.type==="sudoku"?(c.assetRefs||[]).slice(0,4):(c.assetRefs||[]));state.oddId=c.oddRef||null;$("cart").textContent="Zapisz zmiany";$("editBadge")?.classList.add("on")}
  $("generate").onclick=build;$("randomSeed").onclick=()=>{$("seed").value=`fenix-logic-${Date.now().toString(36)}`;build()};$("png").onclick=()=>{const a=document.createElement("a");a.href=canvas.toDataURL("image/png");a.download=`logic-${state.view}-${Date.now()}.png`;a.click()};$("cart").onclick=save;$("prev").onclick=()=>{if(state.index>0){state.index--;show()}};$("next").onclick=()=>{if(state.index<state.pages.length-1){state.index++;show()}};$("taskTab").onclick=()=>{state.view="task";$("taskTab").classList.add("primary");$("solutionTab").classList.remove("primary");show()};$("solutionTab").onclick=()=>{state.view="solution";$("solutionTab").classList.add("primary");$("taskTab").classList.remove("primary");show()};$("tabProject").onclick=()=>showSource("project");$("tabLibrary").onclick=()=>showSource("library");$("preset").onchange=()=>{const v={preschool:{age:"3-5",difficulty:"easy",range:10},early:{age:"5-7",difficulty:"medium",range:20},advanced:{age:"7-9",difficulty:"hard",range:50}}[$("preset").value];if(v){$("age").value=v.age;$("difficulty").value=v.difficulty;$("range").value=v.range}build()};["type","elementMode","difficulty","age","count","range","language"].forEach(id=>$(id).addEventListener("change",()=>{if(id==="type"){normalizeSudokuSelection();renderAssetPanels()}else updateAssetStatus();schedule()}));["title","instructions","seed"].forEach(id=>$(id).addEventListener("input",schedule));window.addEventListener("fenix-state-change",()=>{renderAssetPanels();schedule()});const p=FenixCore.getActiveProject();$("projectInfo").textContent=`Aktywny projekt: ${p.name} · ${p.format}`;loadEdit();renderAssetPanels();showSource("project");build()
})();